---
#title: "Macroenometrics (44343)"
output:
  html_document:
    theme: cerulean
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
---

<br><br>

Durante el curso usaremos diferentes ficheros de datos para los ejemplos y para el código en `R`. Desde esta página puedes descargarte todo el material

<br>

----------------------

<br>

### Ficheros de datos

- [**Títulos publicados**](series/libros.csv): Títulos publicados en España (fuente Instituto Nacional de Estadística). Es una serie anual de 1993 a 2018.
- [**Nacimientos**](series/nacimientos.csv): Nacimientos en España (fuente Instituto Nacional de Estadística). Serie mensual de enero de 1975 a diciembre de 2018
- [**Extracción de dinero de un cajero**](series/sucursal.csv): Extracción de dinero de un cajero de Bankia del centro de Valencia (fuente Bankia). Es una serie diaria.
- [**Aforo de vehículos en Oropesa**](series/aforo_oropesa.csv): Aforo de vehículos por Oropesa, carretera N-340, km. 996,48 (fuente Ministerio de Fomento). La serie es anual de 1960 a 2018.
- [**Consumo de alimentos per cápita**](series/alimentacionpc.csv): Consumo alimentario en hogar per cápita en España. Esta serie está construida a partir de la serie de consumo alimentario en hogar (fuente Ministerio de Agricultura, Alimentación y Medio Ambiente), y la serie de población (fuente Instituto Nacional de Estadística). Es una serie anual de 1987 a 2018 y la unidad es el Kg per cápita.
- [**Producción de Chocolate en Australia**](series/Chocolate.csv): Producción de chocolate en Australia desde enero de 1958 hasta diciembre de 1994.
- [**Defunciones por enfermedades cerebrovasculares**](series/Enfermedades cerebrovasculares.csv): Número de defunciones causadas por enfermedades cerebrovasculares (fuente Instituto Nacional de Estadística). Es una serie mensual de enero de 1980 a diciembre de 2018.

\

- [**Todos los ficheros de datos en un único fichero comprimido**](series/todoslosficherosdedatos.zip)

\
\

### Código `R`

Tienes el código para los temas de teoría aquí:

- [**Código para el tema 1**](codigo/Codigo Tema 1.R)
- [**Código para el tema 2**](codigo/Codigo Tema 2.R)
- [**Código para el tema 3**](codigo/Codigo Tema 3.R)
- [**Código para el tema 4**](codigo/Codigo Tema 4.R)
- [**Código para el tema 5**](codigo/Codigo Tema 5.R)

\

Para el ejemplo tienes el código aquí:

- [**Código para el ejemplo del tema 1**](codigo/Codigo Ejemplo 1.R)
- [**Código para el ejemplo del tema 2**](codigo/Codigo Ejemplo 2.R)
- [**Código para el ejemplo del tema 3**](codigo/Codigo Ejemplo 3.R)
- [**Código para el ejemplo del tema 4**](codigo/Codigo Ejemplo 4.R)
- [**Código para el ejemplo del tema 5**](codigo/Codigo Ejemplo 5.R)

\

Y si quieres todos los ficheros de código de golpe aqui:

- [**Todos los ficheros de código en un único fichero comprimido**](codigo/todoslosficherosdecodigo.zip)

\
\
\
\



