---
title: "Prácticas de evaluación"
output:
  html_document:
    theme: cerulean
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
---

\
\


Durante todo el módulo realizarás una serie de ejercicios que aplicarán las técnicas vistas en cada tema. Lee con atención las siguientes instrucciones generales.


Tu primera tarea es descargarte tu serie temporal. Descárgate [aqui](practica/Descripcion de las series.pdf) el fichero .pdf con la descripción de las series y localiza en él el nombre de tu serie. El este fichero encontrarás también una descripción detallada de la serie que vas a analizar: nombre, definición, unidades, fuente, fechado…

Por otro lado, descárgate [aquí](practica/Series.zip) fichero comprimido con todas las series, descomprímelo y localiza el fichero txt con tu serie.

______________________

\
\


### Características generales de las entregas

\

* La **fecha** máxima de entrega de cada trabajo se indicará al finalizar cada tema. Procura no retrasarte. Si el retraso supera la semana, tu nota en la práctica será de cero.
* En Aulavirtual, en la tarea "SERIES: Practica n" debes **subir un fichero .pdf con los resultados** de la práctica n-ésima. Sólo se admite un único fichero en formato .pdf.
* Piensa que además de los contenidos también su ordenación, estructura, sintaxis, comentarios, etc. son parte de la evaluación.
* **Incluye siempre todo el código en R utilizado en el trabajo**. Si utilizas Markdown (o similar), haz que el código sea visible; en otro caso, añádelo como un apéndice al final del documento. 
 

\
\

### Práctica 1: Introducción a las series temporales

\

*	**Parte 1:** Descripción de la serie temporal
    - Haz una descripción detallada de tu serie (tendencia, estacionalidad, intervención, tipo de esquema...).
    - Ayúdate para ello de todos los elementos numéricos y gráficos que hemos visto: gráfica de tu serie original, gráfica de su agregación anual, gráfica localización/dispersión, descomposición...

\

* **Parte 2:** Análisis del residuo
  - Haz un análisis del residuo obtenido tras la descomposición para determinar si es ruido blanco e identificar posibles intervenciones. 
  - Ten en cuenta que si has realizado una descomposición multiplicativa de tu serie, el residuo obtenido no es válido para este análisis. Deberás previamente obtener el residuo aditivo.
  - Para este análisis haz uso de las técnicas estadísticas o gráficas que conozcas.

Si el análisis realizado así lo aconseja, indica si vas a recortar tu serie para posteriores análisis.


\
\

### Práctica 2: Alisado exponencial

\

* **Ejercicio 1:** Serie con fechado anual
    - Considera la agregación anual de tu serie temporal (que ya usaste en la primera práctica).
    - Ajusta el modelo de alisado más adecuado a tus datos.
    - Describe el modelo obtenido.
    - Interpreta el valor de los parámetros estimados.
    - Obtén los indicadores de la calidad del modelo y coméntalos. Al menos calcula los indicadores de calidad para las previsiones intra-muestrales a un periodo vista y para las previsiones extra-muestrales a varios periodos vista (validación cruzada).
    - Muestra los últimos valores estimados de nivel y pendiente y realiza una predicción a mano y con `R` para los tres siguientes años. 
    - Realiza un predicción a tres años vista con `R` y muestra los resultados de la estimación y la predicción gráficamente.
    - Obtén el residuo e identifica la presencia de valores extremos.

\

* **Ejercicio 2:** Serie con el fechado original
    - Repite el análisis previo, pero usando esta vez su serie original sin anualizar.
    - En este caso, haz la previsión _a mano_ para 12 meses y con `R` para 36 meses.

\
\

### Práctica 3: Procesos estocásticos

\

Esta práctica tiene como objetivo transformar tu serie para que sea estacionaria en media y varianza, y ergódica.

* **Ejercicio 1:** Serie con fechado anual
    - Considera la agregación anual de tu serie temporal. 
    - Determina si has de diferenciar la serie y si es conveniente la transformación logarítmica para que verifique las hipótesis de estacionariedad y ergodicidad.
    - Haz el contraste de raíces unitarias para identificar el orden de integración.

\

* **Ejercicio 2:** Serie con el fechado original
   - Transforma tu serie original usando sólo las funciones log y diff para obtener otra que sea estacionaria y ergódica.

\
\

### Práctica 4: Procesos ARIMA sin estacionalidad

A grandes rasgos el ejercicio consistirá en analizar tu serie temporal sin estacionalidad (agregación anual), siguiendo la metodología de Box y Jenkins. Por tanto, para esta práctica debes considerar solo tu serie con fechado anual.

* Las tareas para realizar son:
    - Transformar la serie para que sea estacionaria y ergódica (según determinaste en la práctica 3)
    - Identificar la serie, estimarla y validarla
    - Realizar predicciones puntuales y por intervalo
    - Comparar la calidad del ajuste y de las predicciones del modelo ARIMA con la que obtuviste con el modelo de alisado exponencial de la práctica 2.

A continuación se indican los contenidos mínimos que se deben presentar. Eres libre de elegir el orden de la presentación de los contenidos, así como la información finalmente presentada.

* Identificación del modelo ARIMA:
    - Diferenciación, parte estructural, análisis de intervención y valores atípicos.

* Estimación del modelo definitivo
    - Estimación de los coeficientes del modelo.
    - Desarrollo de la ecuación estimada.
    - Interpretación de los parámetros y de la ecuación estimada.

* Validación completa del modelo
    - Significatividad de los coeficientes (contraste de Wald).
    - Hipótesis sobre el residuo.
    - Valores extremos.
    - Cálculo de la calidad del ajuste y de las predicciones

* Previsión de la serie (al menos tres años)

* Valoración crítica del modelo ARIMA respecto de un modelo de alisado:
    - Comparación del modelo estimado para la serie en la práctica 2 y del modelo de esta práctica.
    - Comparación de la calidad de los modelos.
    - Comparación de las previsiones.

\
\

### Práctica 5: Procesos ARIMA con estacionalidad

Los objetivos de esta práctica son idénticos a los de la práctica previa, pero considerando tu serie original con estacionalidad.

* Las tareas para realizar son:
    - Transformar la serie para que sea estacionaria y ergódica (según determinaste en la práctica 3)
    - Identificar la serie, estimarla y validarla
    - Realizar predicciones puntuales y por intervalo
    - Comparar la calidad del ajuste y de las predicciones del modelo ARIMA con la que obtuviste con el modelo de alisado exponencial de la práctica 2.


* Identificación del modelo ARIMA:
    - Diferenciación, parte estructural, análisis de intervención y valores atípicos.

* Estimación del modelo definitivo
    - Estimación de los coeficientes del modelo.
    - Desarrollo de la ecuación estimada.
    - Interpretación de los parámetros y de la ecuación estimada.

* Validación completa del modelo
    - Significatividad de los coeficientes (contraste de Wald).
    - Hipótesis sobre el residuo.
    - Valores extremos.
    - Cálculo de la calidad del ajuste y de las predicciones

* Previsión de la serie (al menos tres años)

* Valoración crítica del modelo ARIMA respecto de un modelo de alisado:
    - Comparación del modelo estimado para la serie en la práctica 2 y del modelo de esta práctica.
    - Comparación de la calidad de los modelos.
    - Comparación de las previsiones.

\
\
\
\

