---
title: "Guía del Curso"
number-sections: false
toc: true
toc-float: true
---

\
\
\

## Introducción

El módulo de Series Temporales pertenece al Máster de Bioestadística y se configura como un módulo impartido en el segundo cuatrimestre con 10 sesiones de cinco horas.

El objetivo general es aprender a manejarse con datos de corte temporal, **Series Temporales**. Es decir, ser capaces de aplicar los métodos para describir, analizar, modelizar y predecir series de datos que evolucionan en el tiempo. Además, hay que saber evaluar la calidad de las predicciones en el contexto de la estadística tradicional y con técnicas de *Machine Learning*.

Para ello, veremos la teoría necesaria y, sobre todo, practicaremos utilizando el programa estadístico **R** y el lenguaje **Markdown** (o **Quarto**) a través de **RStudio**. A estas alturas del grado ya debes estar familiarizado con este programa.

\

------------------------------------------------------------------------

\

## Contenidos

El programa de la asignatura contiene 5 temas distribuidos en **10 sesiones de 5 horas**:

* Sesión 1 y 2:		Tema 1. Definición y Componentes
* Sesión 3 y 4:		Tema 2. Métodos de Alisado Exponencial
* Sesión 5:		    Tema 3. Procesos estocásticos
* Sesión 6 y 7:		Tema 4. Modelos ARIMA
* Sesión 8 y 9:		Tema 5. Modelos ARIMA con estacionalidad
* Sesión 10:		  Repaso general

Pasar de un tema al siguiente supone incrementar la complejidad de las técnicas empleadas para el análisis de una serie temporal, de forma que podréis valorar con datos reales la relación entre complejidad--tiempo--resultados y optar por la metodología más adecuada.

\

------------------------------------------------------------------------

\


## Metodología

Dado el carácter eminentemente práctico del módulo, todas las sesiones se impartirán con el ordenador a mano y se alternará entre teoría y práctica según convenga:

1. *Tiempo de teoría*: os plantearé los conceptos nucleares de cada tema, de forma precisa y rigurosa, en lenguaje natural, gráfico y formal. El material teórico lo podéis encontrar en la sección **Diapos**. 
2. *Tiempo de práctica*: a partir del código y de los ficheros de datos que podéis encontrar en la sección [**Recursos de R**](https://iarribasf.github.io/SeriesTemporales-MASTER/05-Recursos-R.html) practicaréis los conceptos teóricos y aprenderéis el manejo de R para el análisis de series temporales.
3. *Tiempo de evaluación*: tras cada tema realizaréis una breve prueba tipo test, con tiempo limitado, para valorar si habéis adquirido los conocimientos teóricos y las habilidades practicas básicas.
4. *Trabajo práctico de evaluación*: también en clase os daré tiempo para realizar parte de los trabajos prácticos que servirán de evaluación del módulo.

\

Todo el material necesario para este curso lo tenéis disponible en esta página web así como en [**Aula Virtual**](https://aulavirtual.uv.es/?lang=es). También podéis encontrar los detalles en la sección [Logística](https://iarribasf.github.io/SeriesTemporales-MASTER/02-Logistica.html) de la web.

\

------------------

\

## Evaluación

Tanto la parte teórica como la práctica se evaluarán exclusivamente a través de breves pruebas y trabajos prácticos que se irán realizando a lo largo del curso. No habrá, por tanto, examen de evaluación. En caso de suspender en primera convocatoria, deberéis hablar conmigo para coordinar el trabajo de recuperación, puesto que esta se realizará también a través de trabajos prácticos.

Tras cada una de las cinco unidades temáticas se realizará una **breve prueba tipo test**. La prueba contendrá preguntas de respuesta múltiple, numérica, verdadero/falso, etc. Este conjunto de pruebas supondrá un **20%** de la nota de la asignatura y **no es recuperable**.

Además, tras cada unidad temática, os daré una **práctica de evaluación** que deberéis entregar en el plazo establecido. La valoración de estos trabajos supondrá el restante **80%** de la nota de la asignatura, que sí es **recuperable**.

Las prácticas de evaluación deben realizarse utilizando el **programa estadístico R** y recomiendo que uséis para la escritura del trabajo el lenguaje **Markdown** o **Quatro**.


\
\
\
\


