<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Series Temporales - Series Temporales: Procesos Estocásticos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Series Temporales</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html"> 
<span class="menu-text">Guía del curso</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html"> 
<span class="menu-text">Logística</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Diapos</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html">
 <span class="dropdown-text">Tema 1: Definicion y Componentes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html">
 <span class="dropdown-text">Tema 2: Alisado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html">
 <span class="dropdown-text">Tema 3: Procesos estocásticos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html">
 <span class="dropdown-text">Tema 4: ARIMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html">
 <span class="dropdown-text">Tema 5: SARIMA</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-06-Ejemplo1.html">
 <span class="dropdown-text">Ejemplo Tema 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Ejemplo2.html">
 <span class="dropdown-text">Ejemplo Tema 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-08-Ejemplo3.html">
 <span class="dropdown-text">Ejemplo Tema 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-09-Ejemplo4.html">
 <span class="dropdown-text">Ejemplo Tema 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo5.html">
 <span class="dropdown-text">Ejemplo Tema 5</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo-Pasajeros.html">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Píldoras</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Nacimientos.html">
 <span class="dropdown-text">Efecto de la Covid-19 en Nacimientos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-07-Combinando_predicciones.html">
 <span class="dropdown-text">Combinación de predicciones</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-08-Series_interrumpidas.html">
 <span class="dropdown-text">Series interrumpidas</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html"> 
<span class="menu-text">Recursos de la asignatura</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Practica.html"> 
<span class="menu-text">Practica</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Más</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#proceso-estocástico" id="toc-proceso-estocástico" class="nav-link" data-scroll-target="#proceso-estocástico"><span class="header-section-number">2</span> Proceso estocástico</a>
  <ul class="collapse">
  <li><a href="#definición" id="toc-definición" class="nav-link" data-scroll-target="#definición"><span class="header-section-number">2.1</span> Definición</a></li>
  <li><a href="#proceso-estacionario" id="toc-proceso-estacionario" class="nav-link" data-scroll-target="#proceso-estacionario"><span class="header-section-number">2.2</span> Proceso estacionario</a>
  <ul class="collapse">
  <li><a href="#proceso-estacionario-en-sentido-estricto" id="toc-proceso-estacionario-en-sentido-estricto" class="nav-link" data-scroll-target="#proceso-estacionario-en-sentido-estricto">Proceso estacionario en sentido estricto</a></li>
  <li><a href="#proceso-estacionario-en-media" id="toc-proceso-estacionario-en-media" class="nav-link" data-scroll-target="#proceso-estacionario-en-media">Proceso estacionario en media</a></li>
  <li><a href="#proceso-estacionario-en-sentido-amplio" id="toc-proceso-estacionario-en-sentido-amplio" class="nav-link" data-scroll-target="#proceso-estacionario-en-sentido-amplio">Proceso estacionario en sentido amplio</a></li>
  </ul></li>
  <li><a href="#proceso-ergódico" id="toc-proceso-ergódico" class="nav-link" data-scroll-target="#proceso-ergódico"><span class="header-section-number">2.3</span> Proceso ergódico</a></li>
  <li><a href="#normalidad" id="toc-normalidad" class="nav-link" data-scroll-target="#normalidad"><span class="header-section-number">2.4</span> Normalidad</a></li>
  </ul></li>
  <li><a href="#transformaciones-de-una-serie" id="toc-transformaciones-de-una-serie" class="nav-link" data-scroll-target="#transformaciones-de-una-serie"><span class="header-section-number">3</span> Transformaciones de una serie</a>
  <ul class="collapse">
  <li><a href="#ideas-generales" id="toc-ideas-generales" class="nav-link" data-scroll-target="#ideas-generales"><span class="header-section-number">3.1</span> Ideas generales</a></li>
  <li><a href="#diferenciación" id="toc-diferenciación" class="nav-link" data-scroll-target="#diferenciación"><span class="header-section-number">3.2</span> Diferenciación</a>
  <ul class="collapse">
  <li><a href="#diferenciación-regular-k1" id="toc-diferenciación-regular-k1" class="nav-link" data-scroll-target="#diferenciación-regular-k1">Diferenciación regular (<span class="math inline">\(k=1\)</span>)</a></li>
  <li><a href="#diferenciación-estacional-km" id="toc-diferenciación-estacional-km" class="nav-link" data-scroll-target="#diferenciación-estacional-km">Diferenciación estacional (<span class="math inline">\(k=m\)</span>)</a></li>
  <li><a href="#diferenciación-con-r" id="toc-diferenciación-con-r" class="nav-link" data-scroll-target="#diferenciación-con-r">Diferenciación con <code>R</code></a></li>
  </ul></li>
  <li><a href="#transformación-de-box-cox" id="toc-transformación-de-box-cox" class="nav-link" data-scroll-target="#transformación-de-box-cox"><span class="header-section-number">3.3</span> Transformación de Box-Cox</a>
  <ul class="collapse">
  <li><a href="#transformación-logarítmica" id="toc-transformación-logarítmica" class="nav-link" data-scroll-target="#transformación-logarítmica">Transformación logarítmica</a></li>
  <li><a href="#box-cox" id="toc-box-cox" class="nav-link" data-scroll-target="#box-cox">Box-Cox</a></li>
  <li><a href="#transformación-de-box-cox-con-r" id="toc-transformación-de-box-cox-con-r" class="nav-link" data-scroll-target="#transformación-de-box-cox-con-r">Transformación de Box-Cox con <code>R</code></a></li>
  </ul></li>
  <li><a href="#diferencia-logaritmo-y-tasa-de-variación" id="toc-diferencia-logaritmo-y-tasa-de-variación" class="nav-link" data-scroll-target="#diferencia-logaritmo-y-tasa-de-variación"><span class="header-section-number">3.4</span> Diferencia, Logaritmo y Tasa de variación</a></li>
  </ul></li>
  <li><a href="#funciones-de-autocorrelación-y-autocorrelación-parcial" id="toc-funciones-de-autocorrelación-y-autocorrelación-parcial" class="nav-link" data-scroll-target="#funciones-de-autocorrelación-y-autocorrelación-parcial"><span class="header-section-number">4</span> Funciones de autocorrelación y autocorrelación parcial</a>
  <ul class="collapse">
  <li><a href="#función-de-autocorrelación" id="toc-función-de-autocorrelación" class="nav-link" data-scroll-target="#función-de-autocorrelación"><span class="header-section-number">4.1</span> Función de autocorrelación</a></li>
  <li><a href="#función-de-autocorrelación-parcial" id="toc-función-de-autocorrelación-parcial" class="nav-link" data-scroll-target="#función-de-autocorrelación-parcial"><span class="header-section-number">4.2</span> Función de autocorrelación parcial</a></li>
  </ul></li>
  <li><a href="#raíces-unitarias" id="toc-raíces-unitarias" class="nav-link" data-scroll-target="#raíces-unitarias"><span class="header-section-number">5</span> Raíces unitarias</a>
  <ul class="collapse">
  <li><a href="#tipos-de-tendencia" id="toc-tipos-de-tendencia" class="nav-link" data-scroll-target="#tipos-de-tendencia"><span class="header-section-number">5.1</span> Tipos de tendencia</a></li>
  <li><a href="#contraste-de-raíz-unitaria-kpss" id="toc-contraste-de-raíz-unitaria-kpss" class="nav-link" data-scroll-target="#contraste-de-raíz-unitaria-kpss"><span class="header-section-number">5.2</span> Contraste de raíz unitaria KPSS</a>
  <ul class="collapse">
  <li><a href="#teoría" id="toc-teoría" class="nav-link" data-scroll-target="#teoría">Teoría</a></li>
  <li><a href="#procedimiento-de-contraste" id="toc-procedimiento-de-contraste" class="nav-link" data-scroll-target="#procedimiento-de-contraste">Procedimiento de contraste</a></li>
  <li><a href="#contraste-kpss-en-r" id="toc-contraste-kpss-en-r" class="nav-link" data-scroll-target="#contraste-kpss-en-r">Contraste KPSS en <code>R</code></a></li>
  </ul></li>
  <li><a href="#ejemplos" id="toc-ejemplos" class="nav-link" data-scroll-target="#ejemplos"><span class="header-section-number">5.3</span> Ejemplos</a>
  <ul class="collapse">
  <li><a href="#ejemplo-con-residuos" id="toc-ejemplo-con-residuos" class="nav-link" data-scroll-target="#ejemplo-con-residuos">Ejemplo con Residuos</a></li>
  <li><a href="#ejemplo-con-nacimientos-anual" id="toc-ejemplo-con-nacimientos-anual" class="nav-link" data-scroll-target="#ejemplo-con-nacimientos-anual">Ejemplo con Nacimientos (anual)</a></li>
  <li><a href="#pruebas-alternativas-para-contraste-de-raíces-unitarias" id="toc-pruebas-alternativas-para-contraste-de-raíces-unitarias" class="nav-link" data-scroll-target="#pruebas-alternativas-para-contraste-de-raíces-unitarias">Pruebas alternativas para contraste de raíces unitarias</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#resumen-de-los-comandos-utilizados" id="toc-resumen-de-los-comandos-utilizados" class="nav-link" data-scroll-target="#resumen-de-los-comandos-utilizados"><span class="header-section-number">6</span> Resumen de los comandos utilizados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Series Temporales: Procesos Estocásticos</h1>
<p class="subtitle lead">Máster de Bioestadística (Modelización Estadística)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>En este tema vamos a definir una serie de conceptos que permitirán entender mejor <strong>una serie temporal como una muestra de un proceso generador de datos</strong> (PGD). Veremos también herramientas para realizar una descriptiva de una la serie temporal (muestra) que permitirá estimar el PGD que hay detrás y así poder hacer predicciones (inferencia).</p>
<p>Como en el estudio de muestras transversales, la <strong>hipótesis de normalidad</strong> es conveniente, pero a esta hay que añadir las hipótesis de <strong>estacionariedad</strong> y <strong>ergodicidad</strong>.</p>
<p>En los temas siguientes haremos uso constante de los conceptos aquí definidos.</p>
<p><br>
<br>
</p>
</section>
<section id="proceso-estocástico" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Proceso estocástico</h1>
<p><br>
</p>
<section id="definición" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="definición"><span class="header-section-number">2.1</span> Definición</h2>
<p>Un <strong>proceso estocástico</strong> <span class="math inline">\(Y_t\)</span> es (sin excesiva precisión) una variable aleatoria que corresponde a momentos sucesivos del tiempo.</p>
<p>Como toda variable aleatoria, su caracterización puede hacerse a través de su función de distribución o a partir de sus momentos.</p>
<ul>
<li>La caracterización de un proceso estocástico mediante los momentos de primer y segundo orden (medias y covarianzas) es más incompleta que cuando se hace mediante funciones de distribución.</li>
<li>Bajo la <strong>hipótesis de normalidad</strong> el proceso estocástico queda completamente caracterizado a través de los dos primeros momentos.</li>
</ul>
<p>Nosotros contamos con una sola realización del proceso estocástico <span class="math inline">\(Y_t\)</span>, la serie temporal observada <span class="math inline">\(\{y_t\}_{t=1}^T\)</span>.</p>
<ol type="1">
<li>A partir de <span class="math inline">\(\{y_t\}_{t=1}^T\)</span> estimaremos los momentos de primer y segundo orden (medias y covarianzas).</li>
<li>Estos momentos nos permitirán identificar el PGD.</li>
<li>Una vez identificado, estimaremos el PGD y podremos realizar inferencia (contrastes de hipótesis y predicciones).</li>
</ol>
<p>Para que esta línea de razonamiento sea válida es necesario que el proceso sea <strong>estacionario y ergódico</strong>.</p>
<p><br>
</p>
</section>
<section id="proceso-estacionario" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="proceso-estacionario"><span class="header-section-number">2.2</span> Proceso estacionario</h2>
<section id="proceso-estacionario-en-sentido-estricto" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="proceso-estacionario-en-sentido-estricto">Proceso estacionario en sentido estricto</h3>
<p>Un proceso es <strong>estacionario en sentido estricto</strong> cuando la distribución conjunta no varía al realizar un desplazamiento en el tiempo de todas las variables.</p>
<ul>
<li>Si <span class="math inline">\(F(Y_{t_1},..., Y_{t_k})\)</span> es la función de distribución conjunta y <span class="math inline">\(h&gt;0\)</span>, entonces el proceso es estacionario en sentido estricto si <span class="math display">\[F(Y_{t_1},..., Y_{t_k}) = F(Y_{t_1+h},..., Y_{t_k+h})\]</span></li>
</ul>
<p>Intuitivamente, viendo aisladamente algunos los datos de la serie es imposible saber a que periodo temporal corresponden.</p>
<p>Comprobar si un proceso es estacionario en sentido estricto es muy difícil, así que vamos a encontrar condiciones suficientes: <em>estacionariedad en media</em> y en <em>sentido amplio</em> (covarianza).</p>
</section>
<section id="proceso-estacionario-en-media" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="proceso-estacionario-en-media">Proceso estacionario en media</h3>
<p>Un proceso es estacionario en media (o de primer orden) si su nivel se mantiene en el tiempo: <span class="math display">\[E[Y_t] = \mu \; \; \forall t\]</span></p>
</section>
<section id="proceso-estacionario-en-sentido-amplio" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="proceso-estacionario-en-sentido-amplio">Proceso estacionario en sentido amplio</h3>
<p>Un proceso (ya estacionario en media) es estacionario en sentido amplio, o de segundo orden, si sus momentos de orden dos no dependen del tiempo:</p>
<ul>
<li>La (auto)covarianza entre dos periodos de tiempo es finita y sólo depende del intervalo de tiempo transcurrido entre estos dos periodos: <span class="math display">\[Cov[Y_t, Y_{t+k}] = E[(Y_t - \mu)(Y_{t+k} - \mu)] = \gamma_k,\,\,\,\forall t\]</span></li>
</ul>
<p>Observa que la varianza será entonces <span class="math inline">\(Var[Y_t] = E[(Y_t - \mu)^2] = \gamma_0\)</span>.</p>
<p>Si en el contexto de series temporales la autocovarianza la interpretamos como la información de la serie que se transmite entre dos periodos de tiempo <span class="math inline">\(t\)</span> y <span class="math inline">\(t'\)</span>, el supuesto de estacionariedad en sentido amplio nos dice que la información transmitida solo depende de la distancia temporal entre los dos periodos <span class="math inline">\(t - t'\)</span> y no los periodos en si mismos. Por ejemplo, los nacimientos en enero de un año me dan información sobre los nacimientos en enero del año siguiente, y esta información es la misma e independiente del año en consideración. Además, la información transmitida entre dos eneros consecutivos es la misma que entre dos febreros o dos marzos consecutivos porque la distancia es la misma, 12 meses.</p>
<p><br>
</p>
<p>La <a href="#fig-Nacimientos" class="quarto-xref">Figura&nbsp;1</a> muestra la serie Nacimientos que no es estacionaria ni en media, ni en varianza. No lo es en media por que presenta tendencia y, por tanto, el valor medio de la serie cambia en el tiempo; y no es estacionaria en varianza por que al inicio de la serie los datos presenta más variabilidad que a finales del siglo pasado.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-Nacimientos" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Nacimientos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-Nacimientos-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Nacimientos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Nacimientos mensuales
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
</p>
<p>Un proceso estacionario en sentido estricto también es estacionario en sentido amplio, pero lo contrario no es cierto. Ahora bien, <strong>bajo normalidad</strong> un proceso estacionario en sentido amplio también lo será en sentido estricto.</p>
<p><br>
</p>
</section>
</section>
<section id="proceso-ergódico" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="proceso-ergódico"><span class="header-section-number">2.3</span> Proceso ergódico</h2>
<p>En el tema siguiente se verá que la estimación de los momentos de primer y segundo orden de la serie temporal permite identificar y estimar el PGD.</p>
<p>Para que la estimación de los momentos sea consistente el proceso debe ser <strong>ergódico</strong>: <span class="math display">\[\lim_{T\rightarrow \infty} Var(\frac{1}{T}\sum_{t=1}^T Y_t)=0. \]</span></p>
<p>Para que un proceso sea ergódico las observaciones nuevas tienen que aportar suficiente información para que la varianza del valor medio converja a 0. Esto no ocurre si la dependencia entre las variables es muy fuerte.</p>
<p>Una condición necesaria pero no suficiente para que un proceso estacionario sea ergódico es:</p>
<p><span class="math display">\[\lim_{k\rightarrow \infty} \gamma_k = 0.\]</span> Es decir, que cuanto más distancia hay entre dos periodos, menos información se transmite. Alternativamente, que el pasado cada vez ayuda menos a entender el presente.</p>
<p><br>
</p>
</section>
<section id="normalidad" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="normalidad"><span class="header-section-number">2.4</span> Normalidad</h2>
<p>Asumiremos que el error del modelo se distribuye como una variable aleatoria normal. Esta hipótesis se puede relajar si la serie tiene suficientes datos.</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="transformaciones-de-una-serie" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Transformaciones de una serie</h1>
<p><br>
</p>
<section id="ideas-generales" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="ideas-generales"><span class="header-section-number">3.1</span> Ideas generales</h2>
<p>Una serie temporal <span class="math inline">\(\{y_t\}_{t=1}^T\)</span> no tiene porque verificar las condiciones de estacionariedad, ergodicidad y normalidad.</p>
<p>A continuación, veremos una serie de transformaciones que convierten una serie no estacionaria en estacionaria; no ergódica en ergódica; y, de paso, facilitan la verificación de la hipótesis de normalidad, que dejaremos para más adelante.</p>
<p>En el panel superior de la <a href="#fig-Nacimientos2" class="quarto-xref">Figura&nbsp;2</a> vuelves a tener la serie de nacimientos, que denominaremos <span class="math inline">\(y_t\)</span>; en el segundo panel la diferencia de la serie, <span class="math inline">\(y_t - y_{t-1}\)</span>; y en el panel inferior tienes la diferencia de la transformación logarítmica de la serie, <span class="math inline">\(log(y_t) - log(y_{t-1})\)</span>. La serie nacimientos no es estacionaria en media ni en varianza, su diferencia es estacionaria en media, pero no en varianza. Sin embargo, la transformación logarítmica y la diferencia han logrado que sea estacionaria en ambos sentidos.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-Nacimientos2" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Nacimientos2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-Nacimientos2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Nacimientos2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Serie Nacimientos, su diferencia y la diferencia del logaritmo
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
<section id="diferenciación" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="diferenciación"><span class="header-section-number">3.2</span> Diferenciación</h2>
<p><strong>La diferenciación permite transformar una serie no estacionaria en media en estacionaria en media</strong>.</p>
<p>Diferenciar de orden <span class="math inline">\(k\)</span> consiste en restar a la observación de un periodo la de <span class="math inline">\(k\)</span> periodos antes: <span class="math display">\[\nabla_k y_t = y_t - y_{t-k}.\]</span></p>
<section id="diferenciación-regular-k1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diferenciación-regular-k1">Diferenciación regular (<span class="math inline">\(k=1\)</span>)</h3>
<p>Un caso concreto es la <strong>diferenciación regular o diferenciación de orden uno</strong>, que consiste en restar a la observación de un periodo la del periodo precedente:</p>
<p><span class="math display">\[\nabla y_t = y_t - y_{t-1}.\]</span></p>
<p>Si <span class="math inline">\(\nabla y_t\)</span> no fuera estacionaria, se diferenciaría (regularmente) una segunda vez para obtener una doble diferenciación de primer orden:</p>
<p><span class="math display">\[\nabla^{2} y_t = \nabla(\nabla y_t) = \nabla y_t - \nabla y_{t-1} = (y_t - y_{t-1}) - (y_{t-1} - y_{t-2}) = y_t - 2y_{t-1} + y_{t-2}\]</span></p>
<p>En la práctica una sola diferenciación suele ser suficiente para obtener la estacionariedad en media; diferenciar dos veces es excepcional; y diferenciar tres o más veces no se da.</p>
<p>Además, en series sin estacionalidad <strong>la diferenciación también permite alcanzar la ergodicidad</strong>.</p>
</section>
<section id="diferenciación-estacional-km" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diferenciación-estacional-km">Diferenciación estacional (<span class="math inline">\(k=m\)</span>)</h3>
<p>La <strong>diferencia estacional</strong> consiste en restar a la observación de un periodo la observación precedente de la misma estación. Si el orden estacional es <span class="math inline">\(m\)</span>, entonces la diferencia estacional de <span class="math inline">\(y_t\)</span> es</p>
<p><span class="math display">\[\nabla_m y_t = y_t - y_{t-m}.\]</span></p>
<p>Una serie no estacionaria en media puede pasar a serlo tras diferenciarla estacionalmente. Es general, cualquiera de las dos diferenciaciones vistas (regular o estacional) o ambas a la vez son alternativas para obtener la estacionariedad.</p>
<p>Además, <strong>la diferenciación (regular, estacional o ambas) también permite alcanzar la ergodicidad</strong>.</p>
<p>La <a href="#fig-NacimientosDif" class="quarto-xref">Figura&nbsp;3</a> muestra un ejemplo de diferenciación regular y/o estacional. En el primer panel aparece la serie original Nacimientos <span class="math inline">\(y_t\)</span>; el segundo panel muestra la serie diferenciada regularmente <span class="math inline">\(\nabla y_t\)</span>; en el tercer panel la serie diferenciada estacionalmente <span class="math inline">\(\nabla_{12} y_t\)</span>; y en el cuarto panel muestra la serie diferenciada regular y estacionalmente <span class="math inline">\(\nabla\nabla_{12} y_t\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-NacimientosDif" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NacimientosDif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosDif-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NacimientosDif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Nacimientos mensuales y diferenciaciones
</figcaption>
</figure>
</div>
</div>
</div>
<p><em>¿Qué transformación para nacimientos consideras que genera una serie estacionaria, tanto en media como en varianza?</em> Siempre hay un cierto grado de subjetividad en la elección de las diferencias que hay que aplicar a una serie. En la figura 4 podemos considerar que la diferenciación regular (panel 2) es suficiente para lograr la estacionariedad en media y en varianza y terminar el proceso de diferenciación. Pero también podemos considerar que la serie es estacionaria en media pero no en varianza, y optar por la doble diferenciación, regular y estacional (panel 4). Existen contrastes para ayudarnos en esta decisión (véase epígrafe 5), pero la conclusión puede depender el tipo de contraste elegido o de ciertos parámetros técnicos usados en los contrastes. Muchas veces la decisión final se realiza durante el proceso de modelización o simplemente se opta por la que mejores predicciones genere.</p>
</section>
<section id="diferenciación-con-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diferenciación-con-r">Diferenciación con <code>R</code></h3>
<p><code>R</code> dispone de la función <code>diff</code> para diferenciar una serie:</p>
<ul>
<li><code>diff(x, lag = k)</code> calcula la diferencia de orden <span class="math inline">\(k\)</span>, <span class="math inline">\(\nabla_k y_t\)</span></li>
<li><code>diff(x)</code> calcula la diferencia regular o de orden <span class="math inline">\(1\)</span>, <span class="math inline">\(\nabla y_t\)</span> (el valor por defecto de <code>lag</code> es 1)</li>
<li><code>diff(x, difference = d)</code> calcula <span class="math inline">\(d\)</span> diferencias regulares, <span class="math inline">\(\nabla^d y_t\)</span></li>
<li><code>diff(x, lag = m)</code> calcula una diferencia estacional, <span class="math inline">\(\nabla_m y_t\)</span></li>
</ul>
<p>Si necesitas calcular una diferencia regular y otra estacional, <span class="math inline">\(\nabla\nabla_m y_t\)</span>, debes usar <code>diff(diff(x, lag = m))</code>. El orden de las diferenciaciones no cambia el resultado.</p>
<p>Además, en <code>forecast</code> están disponibles las funciones <code>ndiffs</code> y <code>nsdiffs</code> que estiman, respectivamente, el número de diferencias regulares y estacionales necesarias. En el primer caso se usa un contraste de raíces unitarias (epígrafe 5) y en el segundo un criterio <em>ad-hoc</em>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nsdiffs</span>(nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Para nacimientos estas dos funciones sugieren la doble diferenciación regular y estacional. La doble diferenciación es muy usual.</p>
<p><br>
</p>
</section>
</section>
<section id="transformación-de-box-cox" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="transformación-de-box-cox"><span class="header-section-number">3.3</span> Transformación de Box-Cox</h2>
<p>En el tema 2 vimos el argumento <code>lambda</code>, que fijado a 0 indicaba que había que transformar la serie logarítmicamente. Veamos en detalle que hay detrás de este argumento.</p>
<section id="transformación-logarítmica" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-logarítmica">Transformación logarítmica</h3>
<p>Si la serie original no es estacionaria en varianza porque los datos crecen con el nivel de la serie, es posible obtener la estacionariedad por medio de transformaciones simples.</p>
<p>La transformación logarítmica de una serie es una alternativa. La <a href="#fig-BoxCox" class="quarto-xref">Figura&nbsp;4</a> muestra la serie Nacimientos y su logaritmo. La variabilidad estacional con la transformación logarítmica (panel segundo) es menor que en la serie original (panel superior).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-BoxCox" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-BoxCox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-BoxCox-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-BoxCox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Serie Nacimientos y algunas transformaciones Box-Cox
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="box-cox" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="box-cox">Box-Cox</h3>
<p>La transformación logarítmica es un caso concreto de otra más general, la transformación de Box-Cox: <span class="math display">\[
z_t =
    \begin{cases}
      (y_t^{\lambda}-1)/\lambda &amp; \,\,\,\lambda \neq 0 \\
      \log(y_t) &amp; \,\,\, \lambda = 0
    \end{cases}
\]</span></p>
<p>Se puede demostrar que <span class="math inline">\(\lim_{\lambda \rightarrow 0} \;\; (y_t^{\lambda}-1)/\lambda = log(y_t)\)</span>.</p>
</section>
<section id="transformación-de-box-cox-con-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-box-cox-con-r">Transformación de Box-Cox con <code>R</code></h3>
<p><code>R</code> dispone de una serie de funciones en el paquete <code>forecast</code> que nos facilitan el uso de la transformación de Box-Cox:</p>
<ul>
<li><code>BoxCox(y, lambda)</code> realiza la transformación Box-Cox para un valor de <span class="math inline">\(\lambda\)</span> determinado.</li>
<li><code>InvBoxCox(z, lambda)</code> realiza la transformación inversa</li>
<li><code>BoxCox.lambda(y)</code> calcula el valor de <span class="math inline">\(\lambda\)</span> más adecuado. Usa <code>help</code> para saber más sobre los métodos de estimación de <span class="math inline">\(\lambda\)</span>.</li>
</ul>
<p>Para la serie Nacimientos el valor óptimo de <span class="math inline">\(\lambda\)</span> es:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BoxCox.lambda</span>(nacimientos) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.08823508</code></pre>
</div>
</div>
<p>En la <a href="#fig-BoxCox" class="quarto-xref">Figura&nbsp;4</a>, el panel inferior muestra la transformación <em>óptima</em> de Box-Cox para Nacimientos usado el valor <span class="math inline">\(\lambda= -0.09\)</span>. Por un lado, el valor obtenido es muy cercano a cero. Por otro lado, no hay grandes diferencias (al menos visuales) entre el resultado de la transformación logarítmica y el resultado de la transformación de Box-Cox con <span class="math inline">\(\lambda= -0.09\)</span>. Finalmente, ¿qué interpretación tiene <span class="math inline">\((nacimientos_t^{-0.09}-1)/(-0.09)\)</span>? En general, y con independencia del resultado de la transformación óptima, se opta por la transformación logarítmica por ser más sencilla y sobre todo más interpretable.</p>
<p>Por último, ten presente que <strong>si se estima y predice una serie transformada, luego hay que deshacer la transformación para obtener la predicción de la serie original</strong>.</p>
<p>El argumento <code>lambda</code> que hemos usado en algunas funciones de la librería <code>forecast</code> hace referencia al parámetro <span class="math inline">\(\lambda\)</span> de la transformación Box-Cox. Siempre lo hemos fijado a cero, indicando la transformación logarítmica.</p>
<p><br>
</p>
</section>
</section>
<section id="diferencia-logaritmo-y-tasa-de-variación" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="diferencia-logaritmo-y-tasa-de-variación"><span class="header-section-number">3.4</span> Diferencia, Logaritmo y Tasa de variación</h2>
<p>La transformación <span class="math inline">\(\nabla y_t\)</span> se puede interpretar como variaciones en nivel. Sin embargo, cuando una serie tiene que ser diferenciada para conseguir su estacionariedad, vale la pena probar una transformación alternativa que también es interpretable: <span class="math inline">\(\nabla \log(y_t)\)</span>.</p>
<p>Para la <strong>diferencia regular</strong> se tiene que, <span class="math display">\[\nabla \log(y_t) = \log(y_t) - \log(y_{t-1}) = \log\big(\frac{y_t}{y_{t-1}} \big) \approx \frac{y_t}{y_{t-1}} - 1 = \frac{y_t - y_{t-1}}{y_{t-1}} =TV y_t.\]</span></p>
<p>Es decir, la <em>diferencia regular del logaritmo (natural) es la Tasa de Variación de la serie</em>, que tiene una clara interpretación como variación porcentual. Por ejemplo, para una serie anual la diferencia regular del logaritmo (natural) es la Tasa de Variación Anual de la serie <span class="math inline">\((\nabla \log(y_t)=TVA y_t)\)</span>; y para una serie mensual la diferencia regular del logaritmo (natural) es la Tasa de Variación Mensual de la serie <span class="math inline">\((\nabla \log(y_t)=TVM y_t)\)</span>.</p>
<p>Para la <strong>diferencia estacional</strong> se tiene que, <span class="math display">\[\nabla_m \log(y_t) \approx \frac{y_t - y_{t-m}}{y_{t-m}} =TV_m y_t.\]</span></p>
<p>Es decir, para una serie mensual la diferencia estacional del logaritmo es la Tasa de Variación Anual de la serie <span class="math inline">\((\nabla_{12} \log(y_t)=TVA y_t)\)</span>; y para una serie diaria la diferencia estacional del logaritmo es la Tasa de Variación Semanal de la serie <span class="math inline">\((\nabla_{7} \log(y_t)=TVS y_t)\)</span>.</p>
<p><br>
</p>
<p>Cuando una serie tiene que ser <strong>diferenciada tanto regular como estacionalmente</strong> para conseguir su estacionariedad también vale la pena usar la transformación logarítmica para ganar en interpretabilidad. Es decir, frente a <span class="math inline">\(\nabla \nabla_m y_t\)</span> es preferible usar <span class="math inline">\(\nabla \nabla_m \log(y_t)\)</span>. Así, podemos escribir</p>
<p><span class="math display">\[\nabla_m \nabla \log(y_t) = \nabla_m TV y_t = TV y_t - TV y_{t-m},\]</span> que para una serie mensual se puede interpretar como una diferencia estacional de tasas mensuales <span class="math inline">\(TVM y_t - TVM y_{t-12}\)</span>. Es decir, como cambia de año en año la tasa de variación mensual.</p>
<p>También podemos escribir</p>
<p><span class="math display">\[\nabla \nabla_m \log(y_t) = \nabla TV_m y_t = TV_m y_t - TV_m y_{t-1},\]</span></p>
<p>que para una serie mensual se puede interpretar como una diferencia regular de tasas anuales <span class="math inline">\(TVA y_t - TVA y_{t-1}\)</span>. Es decir, Es decir, como cambia de mes en mes la tasa de variación anual.</p>
<p>La <a href="#fig-NacimientosTasa" class="quarto-xref">Figura&nbsp;5</a> muestra para la serie Nacimientos la serie original (panel superior), las tasas de variación mensual y anual (paneles dos y tres, respectivamente) y la doble diferencia regular y estacional del logaritmo de nacimientos (panel inferior). Parece que la tasa de variación mensual de los nacimientos y la doble diferencia son, de todas las transformaciones probadas en este epígrafe, las series más estacionarias en media y varianza.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-NacimientosTasa" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NacimientosTasa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosTasa-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NacimientosTasa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Serie Nacimientos y diversas transformaciones
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
La diferenciacion y el logaritmo
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Si se tiene una serie sin estacionalidad y no estacionaria, bastará diferenciarla regularmente una o, a lo sumo, dos veces para que sea estacionaria en media, en sentido amplio y ergódica.</p></li>
<li><p>Si se tiene una serie con estacionalidad y no estacionaria, lo usual es tener que diferenciarla una vez (regular o estacionalmente) o aplicar ambas diferenciaciones para que sea estacionaria en media, en sentido amplio y ergódica.</p></li>
<li><p>En ambos casos, la transformación logarítmica se puede usar para ganar en interpretabilidad o para intentar mejorar las predicciones.</p></li>
<li><p>La transformación logarítmica no es necesaria para alcanzar la estacionariedad de la serie.</p></li>
</ul>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="funciones-de-autocorrelación-y-autocorrelación-parcial" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Funciones de autocorrelación y autocorrelación parcial</h1>
<p><br>
</p>
<section id="función-de-autocorrelación" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="función-de-autocorrelación"><span class="header-section-number">4.1</span> Función de autocorrelación</h2>
<p>Ya hemos indicado que bajo ciertas hipótesis los momentos primero y segundo de la serie caracterizan perfectamente el proceso estocástico. En el contexto de series temporales, si se da la estacionariedad en media, el primer momento de la serie es constante y, por tanto, no informativo. <strong>Son los segundos momentos de la serie (covarianzas) los que caracterizan el proceso estocástico</strong>.</p>
<p>Recordemos que <span class="math inline">\(\gamma_k=Cov(y_t,y_{t-k})\)</span> es la autocovarianza de orden k. Por tanto <span class="math inline">\(\gamma_0\)</span> es la varianza de la serie <span class="math inline">\(y_t\)</span>. Sea <span class="math inline">\(\rho_k\)</span> la autocorrelación se orden <span class="math inline">\(k\)</span>. Se puede verificar que: <span class="math display">\[\rho_k = cor(y_t, y_{t-k}) =\frac{\gamma_k}{\gamma_0}.\]</span></p>
<ul>
<li><span class="math inline">\(\rho_1\)</span> mide la información que se transmite de un periodo al siguiente periodo.</li>
<li><span class="math inline">\(\rho_k\)</span> mide la información que se transmite k periodos hacia adelante.</li>
</ul>
<p>Las autocorrelaciones caracterizan el proceso estocástico, y <strong>la función de autocorrelación o correlograma (FAC, o ACF en inglés) es el gráfico de <span class="math inline">\(r_k\)</span> contra <span class="math inline">\(k\)</span></strong>, donde <span class="math inline">\(r_k\)</span> es la estimación de <span class="math inline">\(\rho_k\)</span> obtenida con las observaciones.</p>
<p>La <a href="#fig-NacimientosFAC" class="quarto-xref">Figura&nbsp;6</a> muestra la FAC para la serie Nacimientos y algunas de sus transformaciones. Observa el uso del argumento <code>lag</code>, que en la función <code>ggAcf</code> indica el orden máximo de la autocorrelación mostrada en el gráfico. La primera columna muestra la FAC para Nacimientos y varias diferenciaciones, mientras que la segunda columna muestra la FAC para el logaritmo de los nacimientos y sus diferenciaciones. Se puede observar que:</p>
<ul>
<li>la FAC de una serie y su transformación logarítmica es muy similar.</li>
<li>En los paneles de la primera y tercera fila las autocorrelaciones decrecen muy lentamente. Este es un claro indicativo de que la serie analizada no es estacionaria ni ergódica.</li>
<li>En los paneles de la segunda fila las autocorrelaciones de orden estacional (12, 24,…) también decrecen lentamente, indicando que la serie analizada no es ergódica.</li>
<li>Solo la doble diferenciación regular y estacional de la serie (original o su logaritmo) muestran un rápido descenso en los coeficiente de autocorrelación (paneles de la última fila), indicando que la serie transformada es estacionaria en media y ergódica.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(nacimientos, <span class="at">lag =</span> <span class="dv">48</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">log</span>(nacimientos), <span class="at">lag =</span> <span class="dv">48</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(nacimientos), <span class="at">lag =</span> <span class="dv">48</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientos)), <span class="at">lag =</span> <span class="dv">48</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(nacimientos, <span class="at">lag =</span> <span class="dv">12</span>),<span class="at">lag =</span> <span class="dv">48</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientos), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">lag =</span> <span class="dv">48</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(nacimientos, <span class="at">lag=</span><span class="dv">12</span>)), <span class="at">lag =</span> <span class="dv">48</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientos), <span class="at">lag=</span><span class="dv">12</span>)), <span class="at">lag =</span> <span class="dv">48</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout="[[45,-10,45],[45,-10,45],[45,-10,45],[45,-10,45]]" data-layout-align="center">
<div id="fig-NacimientosFAC" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NacimientosFAC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-1" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Serie original
</figcaption>
</figure>
</div>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 10.0%;justify-content: center;">
<p>&nbsp;</p>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-2" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Logaritmo de la serie
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-3" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Dif. regular de la serie
</figcaption>
</figure>
</div>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 10.0%;justify-content: center;">
<p>&nbsp;</p>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-4" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Dif. regular del logaritmo la serie
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-5" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) Dif. estacional de la serie
</figcaption>
</figure>
</div>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 10.0%;justify-content: center;">
<p>&nbsp;</p>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-6" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-6.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(f) Dif. estacional del logaritmo la serie
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-7" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-7.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(g) Dif. regular y estacional de la serie
</figcaption>
</figure>
</div>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 10.0%;justify-content: center;">
<p>&nbsp;</p>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFAC" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-8" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFAC-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFAC-8.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFAC">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFAC-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(h) Dif. regular y estacional del logaritmo la serie
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NacimientosFAC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: FAC para Nacimientos
</figcaption>
</figure>
</div>
</div>
<p>Las bandas azules de la FAC muestran el intervalo de confianza al 95% (IC95). Si <span class="math inline">\(\rho_k = 0\)</span>, la distribución del estimador <span class="math inline">\(r_k\)</span> se distribuye aproximadamente como una normal de media <span class="math inline">\(-1/T\)</span> y varianza <span class="math inline">\(1/T\)</span>. Las líneas punteadas de la FAC están dibujadas en las posiciones <span class="math inline">\(\frac{-1}{T} \pm \frac{1.96}{\sqrt{T}}\)</span>.</p>
<ul>
<li><p>Si un <span class="math inline">\(r_k\)</span> cae fuera del IC95 hay evidencia para rechazar la hipótesis nula de que <span class="math inline">\(\rho_k = 0\)</span> a un nivel del 5%. Recordemos que incluso si todos los <span class="math inline">\(\rho_k\)</span> son cero, cabe esperar que un 5% de sus estimaciones <span class="math inline">\(r_k\)</span> caigan fuera del IC95.</p></li>
<li><p>Los <span class="math inline">\(\rho_k\)</span> no son independientes. Si uno cae fuera del IC95, es más probable que los valores vecinos caigan también fuera.</p></li>
</ul>
<p>Si queremos ver los valores numéricos de las autocorrelaciones debemos añadir a la función <code>ggAfc</code> el argumento <code>plot = FALSE</code>. Para la serie doblemente diferenciada vemos que la autocorrelación más elevada se da para el primer retardo (<span class="math inline">\(r_{1}=-0.338\)</span>). El segundo valor más alto es <span class="math inline">\(r_{12} = - 0.311\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(nacimientos, <span class="at">lag=</span><span class="dv">12</span>)), </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">lag =</span> <span class="dv">24</span>, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Autocorrelations of series 'diff(diff(nacimientos, lag = 12))', by lag

     0      1      2      3      4      5      6      7      8      9     10 
 1.000 -0.338 -0.038 -0.005 -0.118 -0.016  0.069 -0.056  0.058  0.102 -0.060 
    11     12     13     14     15     16     17     18     19     20     21 
 0.081 -0.311  0.060  0.052  0.053 -0.060  0.114 -0.040 -0.076  0.066 -0.061 
    22     23     24 
 0.008  0.157 -0.151 </code></pre>
</div>
</div>
<p><br>
</p>
</section>
<section id="función-de-autocorrelación-parcial" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="función-de-autocorrelación-parcial"><span class="header-section-number">4.2</span> Función de autocorrelación parcial</h2>
<p><strong>La autocorrelación parcial de orden k, <span class="math inline">\(\phi_k\)</span>, mide la información que se transmite <em>directamente</em> <span class="math inline">\(k\)</span> periodos adelante</strong>, eliminada la información que se transmite a través de los periodos intermedios.</p>
<ul>
<li><span class="math inline">\(\phi_1\)</span> mide la información que de un periodo se trasmite directamente al siguiente periodo. Por tanto <span class="math inline">\(\phi_1=\rho_1\)</span>.</li>
<li><span class="math inline">\(\phi_2\)</span> mide la información que de un periodo se trasmite 2 periodos adelante, eliminando la información que se trasmite a través del periodo intermedio.</li>
</ul>
<p>La función de autocorrelación parcial (FACP, o PACF en inglés) es el gráfico de <span class="math inline">\(r_{k.1,2,k-1}\)</span> contra <span class="math inline">\(k\)</span>, donde <span class="math inline">\(r_{k.1,2,k-1}\)</span> es la estimación de <span class="math inline">\(\phi_k\)</span> realizada con las observaciones.</p>
<p>La <a href="#fig-NacimientosFACP" class="quarto-xref">Figura&nbsp;7</a> muestra la FACP para la serie Nacimientos y su transformación para que sean estacionarias. La FACP no permite conocer si una serie es estacionaria o ergódica.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggPacf</span>(nacimientos, <span class="at">lag =</span> <span class="dv">36</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggPacf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(nacimientos, <span class="at">lag=</span><span class="dv">12</span>)), <span class="at">lag =</span> <span class="dv">36</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-nrow="1" data-layout-align="center">
<div id="fig-NacimientosFACP" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NacimientosFACP-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFACP" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-NacimientosFACP-1" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFACP-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFACP-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFACP">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFACP-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Serie original
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-NacimientosFACP" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-NacimientosFACP-2" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-NacimientosFACP-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosFACP-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-NacimientosFACP">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-NacimientosFACP-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Serie diff. regular y estacionalmente
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NacimientosFACP-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: FACP para Nacimientos
</figcaption>
</figure>
</div>
</div>
<p>También puedes obtener directamente los valores numéricos de la FACP:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggPacf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(nacimientos), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">lag =</span> <span class="dv">24</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Partial autocorrelations of series 'diff(diff(nacimientos), lag = 12)', by lag

     1      2      3      4      5      6      7      8      9     10     11 
-0.338 -0.172 -0.091 -0.187 -0.168 -0.049 -0.100 -0.032  0.104  0.043  0.133 
    12     13     14     15     16     17     18     19     20     21     22 
-0.263 -0.149 -0.069  0.018 -0.132 -0.001  0.024 -0.097  0.003  0.035  0.017 
    23     24 
 0.197 -0.150 </code></pre>
</div>
</div>
<p>Las funciones <code>tsdisplay</code> y <code>ggtsdisplay</code> muestran la serie temporal, su FAC y su FACP en un único gráfico (véase <a href="#fig-NacimientosDisplay" class="quarto-xref">Figura&nbsp;8</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtsdisplay</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(nacimientos), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacimientosDisplay" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NacimientosDisplay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-NacimientosDisplay-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NacimientosDisplay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: FAC y FACP para la Nacimientos doblemente diferenciada
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="raíces-unitarias" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Raíces unitarias</h1>
<p><br>
</p>
<section id="tipos-de-tendencia" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="tipos-de-tendencia"><span class="header-section-number">5.1</span> Tipos de tendencia</h2>
<p>La <a href="#fig-TiposTendencia" class="quarto-xref">Figura&nbsp;9</a> muestra tres posibles tipos de PGD (el residuo <span class="math inline">\(\varepsilon_t\)</span> es siempre ruido blanco):</p>
<ul>
<li>PGD con tendencia estocástica, por ejemplo <strong>Paseo aleatorio puro</strong>,</li>
</ul>
<p><span class="math display">\[y_t = y_{t-1} + \varepsilon_t = y_0 + \sum_{s=1}^t \varepsilon_s.\]</span></p>
<ul>
<li>PGD con tendencia determinista, por ejemplo <strong>Modelo lineal</strong></li>
</ul>
<p><span class="math display">\[y_t = \alpha + \mu t + \varepsilon_t.\]</span></p>
<ul>
<li>PGD con tendencia estocástica y determinista, por ejemplo <strong>Paseo aleatorio con deriva</strong></li>
</ul>
<p><span class="math display">\[y_t = \mu + y_{t-1} + \varepsilon_t = y_0 + \mu t + \sum_{s=1}^t \varepsilon_s.\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-TiposTendencia" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TiposTendencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-03-Tema3_files/figure-html/fig-TiposTendencia-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TiposTendencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Ejemplos de procesos generadores
</figcaption>
</figure>
</div>
</div>
</div>
<p>En los tres casos la serie no es estacionaria, pero es la <strong>presencia de tendencia estocástica</strong> lo que determina que el proceso tenga una <strong>raíz unitaria</strong>. Así, el paseo aleatorio puro y el paseo aleatorio con deriva presentan una <em>raíz unitaria</em>, pero los tres modelos tienen tendencia y deben ser diferenciados una vez para transformarlos en procesos estacionarios.</p>
<p>Contrastar la tendencia estocástica no es algo trivial, y la prueba es que existen múltiples contrastes para ello: Dickey-Fuller aumentado (ADF), Phillips-Perron (PP), Elliot-Rothemberg-Stock (ERS), Schmidt-Phillips (SP), Kwiatkowski-Phillips-Schmidt-Shin (KPSS), entre otros (véase <span class="citation" data-cites="Pfaff08">Pfaff (<a href="#ref-Pfaff08" role="doc-biblioref">2008</a>)</span>).</p>
<p>En muchas de las pruebas la hipótesis nula es que la serie tiene raíces unitarias (tendencia estocástica), cuando lo habitual es que la hipótesis nula sea la conservadora (en este caso que la serie no tenga tendencia estocástica). En este curso veremos la <strong>prueba de Kwiatkowski-Phillips-Schmidt-Shin</strong> que usa un contraste de Multiplicadores de Lagrange para contrastar la estacionariedad de una serie en torno a una tendencia determinista, frente a la hipótesis alternativa de existencia de una raíz unitaria. Es decir, la prueba KPSS tiene como hipótesis nula que la serie no tiene tendencia estocástica y por tanto es una prueba más conservadora que la mayoría de ellas. Sin embargo, en la prueba KPSS la ausencia de raíz unitaria no es una prueba de estacionariedad, sino de <em>estacionariedad en torno a una tendencia determinista</em>. Por ejemplo, el Modelo lineal no tiene una raíz unitaria (no tiene tendencia estocástica) pero no es estacionario.</p>
<p>También existen procesos con <em>estacionalidad estocástica</em> del tipo <span class="math inline">\(y_t = y_{t-m} + \varepsilon_t\)</span>, donde <em>m</em> es el orden estacional. Contrastar la existencia de raíces unitarias estacionales es complicado y no lo veremos en este curso (véase <span class="citation" data-cites="Ghysels94">Ghysels, Lee, and Noh (<a href="#ref-Ghysels94" role="doc-biblioref">1994</a>)</span>).</p>
<p>En lo que queda de exposición asumiremos que la serie no presenta estacionalidad.</p>
<p><br>
</p>
</section>
<section id="contraste-de-raíz-unitaria-kpss" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="contraste-de-raíz-unitaria-kpss"><span class="header-section-number">5.2</span> Contraste de raíz unitaria KPSS</h2>
<section id="teoría" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="teoría">Teoría</h3>
<p>Sea <span class="math inline">\(y_t\)</span> la serie para la que queremos contrastar la existencia de raíces unitarias. Asumimos que podemos descomponer la serie en la suma de una tendencia determinista, un paseo aleatorio y una perturbación aleatoria estacionaria: <span class="math display">\[y_t = \xi t + r_t + \varepsilon_t.\]</span> Aquí <span class="math inline">\(r_t\)</span> es el paseo aleatorio, <span class="math display">\[r_t = r_{t-1} + u_t,\]</span> donde <span class="math inline">\(u_t\)</span> son i.i.d. <span class="math inline">\((0,\sigma_u^2)\)</span> y el valor inicial <span class="math inline">\(r_0\)</span> se asume fijo y tiene el papel de un intercepto o constante del modelo.</p>
<p>Si se cumple la hipótesis <span class="math inline">\(H_0: \sigma_u^2=0\)</span>, entonces <span class="math inline">\(u_t=0\)</span> y <span class="math inline">\(r_t=r_0\)</span> para todo <span class="math inline">\(t\)</span> y la componente estocástica desaparece, quedando solo la tendencia determinista. Como el parámetro de interés es una varianza, <span class="math inline">\(H_1: \sigma_u^2&gt;0\)</span>, es decir, es un contraste de una cola por la derecha.</p>
<ul>
<li>Si <span class="math inline">\(\xi=0\)</span>, entonces bajo la hipótesis nula <span class="math inline">\(y_t = r_0 + \varepsilon_t\)</span>, es decir <span class="math inline">\(y_t\)</span> no tiene tendencia estocástica ni determinista: es estacionaria en nivel alrededor de <span class="math inline">\(r_0\)</span> (recuerda que por hipótesis <span class="math inline">\(\varepsilon_t\)</span> es estacionario).</li>
<li>Si <span class="math inline">\(\xi \neq 0\)</span>, entonces bajo la hipótesis nula <span class="math inline">\(y_t = \xi t + r_0 + \varepsilon_t\)</span>, es decir <span class="math inline">\(y_t\)</span> no tiene tendencia estocástica pero si determinista: es estacionaria alrededor de una tendencia determinista <span class="math inline">\(\xi t + r_0\)</span>.</li>
<li>En ambos casos, si se rechaza la hipótesis nula es porque la serie tiene una raíz unitaria (tendencia estocástica) y habría que diferenciarla.</li>
</ul>
<p>No hay que olvidar que esta prueba descansa bajo los supuestos de <span class="math inline">\(\varepsilon_t\)</span> es estacionario y <span class="math inline">\(u_t\)</span> i.i.d. <span class="math inline">\((0,\sigma_u^2)\)</span>.</p>
</section>
<section id="procedimiento-de-contraste" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="procedimiento-de-contraste">Procedimiento de contraste</h3>
<p><strong>Paso 1:</strong> Se estima la ecuación <span class="math inline">\(y_t = \xi t + r_0 + \varepsilon_t\)</span> para obtener los residuos estimados <span class="math inline">\(\widehat{\varepsilon}_t\)</span>.</p>
<p>Observa que este vector de residuos se puede estimar fijando <span class="math inline">\(\xi = 0\)</span>, es decir, regresando la serie <span class="math inline">\(y_t\)</span> simplemente sobre una constante; o bajo es supuesto de que <span class="math inline">\(\xi \neq 0\)</span>, es decir, regresando la serie sobre una contante y una tendencia lineal.</p>
<p><strong>Paso 2:</strong> Se definen las sumas parciales <span class="math inline">\(S_t = \sum_{i=1}^t \widehat{\varepsilon}_i\)</span>, con <span class="math inline">\(t=1,2,\ldots,T\)</span> y se calcula <span class="math inline">\(\widehat{\sigma}^2_{\varepsilon}\)</span>.</p>
<p>La forma más sencilla de calcular <span class="math inline">\(\widehat{\sigma}^2_{\varepsilon}\)</span> es <span class="math inline">\(\widehat{\sigma}^2_{\varepsilon}= \sum \widehat{\varepsilon}_t^2/T\)</span>, pero una fórmula alternativa es <span class="math inline">\(\widehat{\sigma}^2_{\varepsilon}(l) = T^{-1}\sum_{t = 1}^T \widehat{\varepsilon}_t^2 + 2T^{-1}\sum_{s=1}^l \Big[ \Big( 1 - \frac{s}{l+1} \Big) \sum_{t=s+1}^T \widehat{\varepsilon}_t \widehat{\varepsilon}_{t-s}  \Big]\)</span>, que dependen el parámetro <span class="math inline">\(l\)</span>.</p>
<p><strong>Paso 3:</strong> El estadístico de contraste es <span class="math inline">\(LM = \sum_{t=1}^T S_t^2/\widehat{\sigma}^2_{\varepsilon}\)</span>.</p>
<p><strong>Paso 4:</strong> Fijado un nivel de significatividad, el estadístico de contraste LM es comparado con el valor crítico. Si LM es mayor que el valor crítico, se rechaza la hipótesis nula, la serie tiene raíces unitarias (tendencia estocástica) y es, por tanto, no estacionaria. Si no se rechaza la hipótesis nula, entonces la serie es estacionaria en torno a un nivel (caso <span class="math inline">\(\xi = 0\)</span>) o a una tendencia determinista (caso <span class="math inline">\(\xi \neq 0\)</span>).</p>
<p>Puedes encontrar los detalles de este contraste en <span class="citation" data-cites="Kwiatkowski92">Kwiatkowski et al. (<a href="#ref-Kwiatkowski92" role="doc-biblioref">1992</a>)</span>.</p>
</section>
<section id="contraste-kpss-en-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="contraste-kpss-en-r">Contraste KPSS en <code>R</code></h3>
<p><code>R</code> proporciona dos implementaciones de esta prueba, <code>ur.kpss</code> en el paquete <code>urca</code> (que será la que usaremos) y <code>kpss.test</code> en el paquete <code>tseries</code>. En ambos casos el usuario debe decidir el valor adecuado del parámetro <span class="math inline">\(l\)</span> para el cálculo de <span class="math inline">\(\widehat{\sigma}^2_{\varepsilon}(l)\)</span>. Como los resultados pueden depender de este parámetro, es conveniente repetir el contraste para diferentes valores.</p>
<p>Además, en <code>forecast</code> está disponible la función <code>ndiffs</code> que estima el número de diferencias necesarias para que una serie sea estacionaria. Por defecto la función <code>ndiffs</code> emplea el contraste KPSS, pero también están disponibles Dickey-Fuller y Phillips-Perron.</p>
<p>Los principales argumentos de la función <code>ur.kpss</code> son:</p>
<ul>
<li><code>type</code>, puede ser <code>type = "mu"</code> para contrastar la presencia de tendencia estocástica en torno a un nivel (<span class="math inline">\(\xi = 0\)</span>); o <code>type = "tau"</code> para contrastar la presencia de tendencia estocástica en torno a una tendencia determinista (<span class="math inline">\(\xi \neq 0\)</span>).</li>
<li><code>lags</code>, el valor del parámetro <span class="math inline">\(l\)</span> en <span class="math inline">\(\widehat{\sigma}^2_{\varepsilon}(l)\)</span>. Puede ser ‘’nil’’ cuando no hay corrección (<span class="math inline">\(l=0\)</span>); ‘’short’’ usa el valor <span class="math inline">\((4T/100)^{0.25}\)</span>; y ‘’long’’ para <span class="math inline">\((12T/100)^{0.25}\)</span>.</li>
<li><code>use.lag</code> fija un valor numérico para <span class="math inline">\(l\)</span>. (La función <code>ndiffs</code> fija este valor a <span class="math inline">\(3\sqrt{T/13}\)</span>.)</li>
</ul>
</section>
</section>
<section id="ejemplos" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="ejemplos"><span class="header-section-number">5.3</span> Ejemplos</h2>
<section id="ejemplo-con-residuos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-con-residuos">Ejemplo con Residuos</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.kpss</span>(residuos, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"tau"</span>, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">lags =</span> <span class="st">"short"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: tau with 2 lags. 

Value of test-statistic is: 0.1384 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.119 0.146  0.176 0.216</code></pre>
</div>
</div>
<p>En el caso en que se asume tendencia determinista, y para <span class="math inline">\(l=2\)</span>, el estadístico de contraste vale 0.138 y el valor crítico al 5% vale 0.146. Como el estadístico de contraste es menor que el valor crítico, se acepta la hipótesis nula, la serie no tiene una raíz unitaria, es decir tiene tendencia determinista, pero no tendencia determinista. Observa que al 1% no se rechaza la hipótesis nula.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.kpss</span>(residuos, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"mu"</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">lags =</span> <span class="st">"short"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: mu with 2 lags. 

Value of test-statistic is: 0.6834 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.347 0.463  0.574 0.739</code></pre>
</div>
</div>
<p>Ahora, bajo el supuesto de que no hay tendencia determinista, el estadístico de contraste vale 0.683 y el valor crítico al 5% vale 0.463. Se rechaza la hipótesis nula, la serie tiene tendencia estocástica alrededor de un nivel.</p>
<p>En cualquiera de los dos casos, la serie tiene tendencia, sea determinista o estocástica, así que hay que diferenciarla.</p>
<p><br>
</p>
<p>Si aplicamos el primer contraste (<span class="math inline">\(\xi \neq 0\)</span>) para diferentes valores de <span class="math inline">\(l\)</span> desde 1 hasta 5, los estadísticos de contraste valen:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5 
0.187 0.138 0.116 0.106 0.102 </code></pre>
</div>
</div>
<p>En todos los casos el valor crítico al 5% sigue siendo <span class="math inline">\(0.146\)</span>. Se observa siempre se acepta la hipótesis nula, si la serie tiene tendencia determinista, no la tiene estocástica.</p>
<p>Si se repite este ejercicio fijando <code>tau = "mu"</code> (<span class="math inline">\(\xi = 0\)</span>), se rechaza la hipótesis nula sólo para <span class="math inline">\(l \leq 3\)</span>. Ahora el estadístico de contraste es <span class="math inline">\(0.463\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5 
0.989 0.683 0.534 0.448 0.393 </code></pre>
</div>
</div>
<p>Si optamos por aceptar que la serie Residuos no es estacionaria y la diferenciamos una vez, debemos repetir el contraste para la serie diferenciada a fin de determinar si una diferencia es suficiente para alcanzar la estacionariedad. Esta vez, lo más conveniente es considerar que la tendencia determinista ya ha sido eliminada y fijar <code>tau = "mu"</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.kpss</span>(<span class="fu">diff</span>(residuos), </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"mu"</span>, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">lags =</span> <span class="st">"short"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: mu with 2 lags. 

Value of test-statistic is: 0.2761 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.347 0.463  0.574 0.739</code></pre>
</div>
</div>
<p>Otra opción es usar la función <code>ndiffs</code> que aplica el contraste KPSS reiteradamente para identificar el número adecuado de diferenciaciones. Esta función permite fijar el nivel de significatividad, el tipo de contraste y el tipo de tendencia determinista.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(residuos, <span class="at">alpha =</span> <span class="fl">0.05</span>, <span class="at">test =</span> <span class="st">"kpss"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>También existe la función <code>nsdiffs</code> que identifica el número de diferenciaciones estacionales adecuado. En este caso se basa de una regla de decisión empírica, sin soporte teórico.</p>
</section>
<section id="ejemplo-con-nacimientos-anual" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-con-nacimientos-anual">Ejemplo con Nacimientos (anual)</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>nacimientosAnual<span class="ot">&lt;-</span><span class="fu">aggregate</span>(nacimientos, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">FUN =</span> sum)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.kpss</span>(nacimientosAnual, </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"tau"</span>, </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">lags =</span> <span class="st">"short"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: tau with 3 lags. 

Value of test-statistic is: 0.1998 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.119 0.146  0.176 0.216</code></pre>
</div>
</div>
<p>El estadístico de contraste vale 0.1998 y el valor crítico al 5% vale 0.146. Como el estadístico de contraste es mayor que el valor crítico, se rechaza la hipótesis nula, la serie tiene tendencia estocástica alrededor de una tendencia determinista, no es estacionaria.</p>
<p>De nuevo, aplicando el contraste para diferentes valores de <span class="math inline">\(l\)</span> se tiene que para todos los valores de <span class="math inline">\(l\)</span> se rechaza la hipótesis nula.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5 
0.371 0.256 0.200 0.167 0.147 </code></pre>
</div>
</div>
<p>Si aplicamos <code>ndiffs</code> obtenemos que hay que diferenciar la serie dos veces para que sea estacionaria.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(nacimientosAnual, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">alpha =</span> <span class="fl">0.05</span>, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">test =</span> <span class="st">"kpss"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
</section>
<section id="pruebas-alternativas-para-contraste-de-raíces-unitarias" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="pruebas-alternativas-para-contraste-de-raíces-unitarias">Pruebas alternativas para contraste de raíces unitarias</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Prueba</th>
<th style="text-align: left;">Función</th>
<th style="text-align: left;">Package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">KPSS</td>
<td style="text-align: left;"><code>ur.kpss</code></td>
<td style="text-align: left;">urca</td>
</tr>
<tr class="even">
<td style="text-align: left;">KPSS</td>
<td style="text-align: left;"><code>kpss.test</code></td>
<td style="text-align: left;">tseries</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ADF</td>
<td style="text-align: left;"><code>ur.df</code></td>
<td style="text-align: left;">urca</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADF</td>
<td style="text-align: left;"><code>adf.test</code></td>
<td style="text-align: left;">tseries</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ADF</td>
<td style="text-align: left;"><code>adftest</code></td>
<td style="text-align: left;">fUnitRoots</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADF</td>
<td style="text-align: left;"><code>ADF.test</code></td>
<td style="text-align: left;">uroot</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PP</td>
<td style="text-align: left;"><code>ur.pp</code></td>
<td style="text-align: left;">urca</td>
</tr>
<tr class="even">
<td style="text-align: left;">PP</td>
<td style="text-align: left;"><code>pp.test</code></td>
<td style="text-align: left;">tseries</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ERS</td>
<td style="text-align: left;"><code>ur.ers</code></td>
<td style="text-align: left;">urca</td>
</tr>
<tr class="even">
<td style="text-align: left;">SP</td>
<td style="text-align: left;"><code>ur.sp</code></td>
<td style="text-align: left;">urca</td>
</tr>
</tbody>
</table>
<p><br>
<br>
</p>
</section>
</section>
</section>
<section id="resumen-de-los-comandos-utilizados" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Resumen de los comandos utilizados</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Función</th>
<th style="text-align: left;">Paquete</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>lag</code></td>
<td style="text-align: left;">stats</td>
<td style="text-align: left;">crea una serie desfasada</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>diff</code></td>
<td style="text-align: left;">base</td>
<td style="text-align: left;">diferencia a serie, por defecto una vez</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ur.kpss</code></td>
<td style="text-align: left;">urca</td>
<td style="text-align: left;">contraste de raíz unitaria KPSS</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>ndiffs</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">identifica el número necesario de diferenciaciones regulares</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>nsdiffs</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">identifica el número necesario de diferenciaciones estacionales</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>ggAcf</code>, <code>ggPacf</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">función de autocorrelación y autocorrelación parcial</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ggtsdisplay</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">dibuja la serie, junto con su ACF y PACF</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>BoxCox.lambda</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">estima el parámetro de la transformación de Box-Cox más adecuado</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>BoxCox</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">realiza la transformación de Box-Cox</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>InvBoxCox</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">realiza la inversa de la transformación de Box-Cox</td>
</tr>
</tbody>
</table>
<p><br>
<br>
<br>
<br>
</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Ghysels94" class="csl-entry" role="listitem">
Ghysels, Eric, Hahn S. Lee, and Jaesum Noh. 1994. <span>“Testing for Unit Roots in Seasonal Time Series: Some Theoretical Extensions and a Monte Carlo Investigation.”</span> <em>Journal of Econometrics</em> 62 (2): 415–42. https://doi.org/<a href="https://doi.org/10.1016/0304-4076(94)90030-2">https://doi.org/10.1016/0304-4076(94)90030-2</a>.
</div>
<div id="ref-Kwiatkowski92" class="csl-entry" role="listitem">
Kwiatkowski, Denis, Peter C. B. Phillips, Peter Schmidt, and Yongcheol Shin. 1992. <span>“Testing the Null Hypothesis of Stationarity Against the Alternative of a Unit Root: How Sure Are We That Economic Time Series Have a Unit Root?”</span> <em>Journal of Econometrics</em> 54 (1): 159–78. https://doi.org/<a href="https://doi.org/10.1016/0304-4076(92)90104-Y">https://doi.org/10.1016/0304-4076(92)90104-Y</a>.
</div>
<div id="ref-Pfaff08" class="csl-entry" role="listitem">
Pfaff, Bernhard. 2008. <em>Analysis of Integrated and Cointegrated Time Series with r</em>. Springer New York. <a href="https://doi.org/10.1007/978-0-387-75967-8">https://doi.org/10.1007/978-0-387-75967-8</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2023, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.es</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This page is built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>