<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Predicción con Datos Temporales - Series con estacionalidad</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predicción con Datos Temporales</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html"> 
<span class="menu-text">Guía del curso</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html"> 
<span class="menu-text">Logística</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Diapos</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html">
 <span class="dropdown-text">Tema 1: Introducción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html">
 <span class="dropdown-text">Tema 2: Definición</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html">
 <span class="dropdown-text">Tema 3: Métodos de predicción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html">
 <span class="dropdown-text">Tema 4: Series sin tendencia ni estacionalidad</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html">
 <span class="dropdown-text">Tema 5: Evaluación de las predicciones</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-06-Tema6.html">
 <span class="dropdown-text">Tema 6: Series sin tendencia y sin estacionalidad</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Tema7.html">
 <span class="dropdown-text">Tema 7: Series con tendencia y estacionalidad (Alisado)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-08-Tema8.html">
 <span class="dropdown-text">Tema 8: Series con tendencia y estacionalidad (Arima)</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo1.html">
 <span class="dropdown-text">Ejemplo: Descriptiva</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo2.html">
 <span class="dropdown-text">Ejemplo: Métodos sencillos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-13-Ejemplo3.html">
 <span class="dropdown-text">Ejemplo: Alisado exponencial</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-14-Ejemplo4.html">
 <span class="dropdown-text">Ejemplo: Arima sin estacionalidad</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-15-Ejemplo5.html">
 <span class="dropdown-text">Ejemplo: Arima con estacionalidad</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-20-Ejemplo-Pasajeros.html">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Píldoras</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Nacimientos.html">
 <span class="dropdown-text">Efecto de la Covid-19 en Nacimientos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-07-Combinando_predicciones.html">
 <span class="dropdown-text">Combinación de predicciones</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-08-Series_interrumpidas.html">
 <span class="dropdown-text">Series interrumpidas</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html"> 
<span class="menu-text">Recursos de la asignatura</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Evaluacion_Continua.html"> 
<span class="menu-text">Evaluacion Continua</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Más</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#métodos-sencillos-de-predicción" id="toc-métodos-sencillos-de-predicción" class="nav-link" data-scroll-target="#métodos-sencillos-de-predicción"><span class="header-section-number">2</span> Métodos sencillos de predicción</a>
  <ul class="collapse">
  <li><a href="#método-ingenuo-con-estacionalidad" id="toc-método-ingenuo-con-estacionalidad" class="nav-link" data-scroll-target="#método-ingenuo-con-estacionalidad"><span class="header-section-number">2.1</span> Método ingenuo con estacionalidad</a></li>
  <li><a href="#ejemplo-de-aplicación-a-la-serie-nacimientos" id="toc-ejemplo-de-aplicación-a-la-serie-nacimientos" class="nav-link" data-scroll-target="#ejemplo-de-aplicación-a-la-serie-nacimientos"><span class="header-section-number">2.2</span> Ejemplo de aplicación a la serie Nacimientos</a></li>
  </ul></li>
  <li><a href="#alisado-exponencial" id="toc-alisado-exponencial" class="nav-link" data-scroll-target="#alisado-exponencial"><span class="header-section-number">3</span> Alisado exponencial</a>
  <ul class="collapse">
  <li><a href="#definición" id="toc-definición" class="nav-link" data-scroll-target="#definición"><span class="header-section-number">3.1</span> Definición</a></li>
  <li><a href="#casos-posibles" id="toc-casos-posibles" class="nav-link" data-scroll-target="#casos-posibles"><span class="header-section-number">3.2</span> Casos posibles</a></li>
  </ul></li>
  <li><a href="#alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m" id="toc-alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m" class="nav-link" data-scroll-target="#alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m"><span class="header-section-number">4</span> Alisado de Holt-Winters aditivo (A, A, A) y multiplicativo (M, A, M)</a>
  <ul class="collapse">
  <li><a href="#alisado-de-holt-winters-aditivo-a-a-a" id="toc-alisado-de-holt-winters-aditivo-a-a-a" class="nav-link" data-scroll-target="#alisado-de-holt-winters-aditivo-a-a-a"><span class="header-section-number">4.1</span> Alisado de Holt-Winters aditivo (A, A, A)</a></li>
  <li><a href="#alisado-de-holt-winters-multiplicativo-m-a-m1" id="toc-alisado-de-holt-winters-multiplicativo-m-a-m1" class="nav-link" data-scroll-target="#alisado-de-holt-winters-multiplicativo-m-a-m1"><span class="header-section-number">4.2</span> Alisado de Holt-Winters multiplicativo (M, A, M)</a></li>
  <li><a href="#ejemplo-con-nacimientos" id="toc-ejemplo-con-nacimientos" class="nav-link" data-scroll-target="#ejemplo-con-nacimientos"><span class="header-section-number">4.3</span> Ejemplo con Nacimientos</a>
  <ul class="collapse">
  <li><a href="#identificación-y-estimación-del-mejor-modelo" id="toc-identificación-y-estimación-del-mejor-modelo" class="nav-link" data-scroll-target="#identificación-y-estimación-del-mejor-modelo">Identificación y estimación del mejor modelo</a></li>
  <li><a href="#predicción" id="toc-predicción" class="nav-link" data-scroll-target="#predicción">Predicción</a></li>
  <li><a href="#análisis-del-error" id="toc-análisis-del-error" class="nav-link" data-scroll-target="#análisis-del-error">Análisis del error</a></li>
  </ul></li>
  <li><a href="#ejemplo-con-nacimiento-y-con-transformación-logarítmica" id="toc-ejemplo-con-nacimiento-y-con-transformación-logarítmica" class="nav-link" data-scroll-target="#ejemplo-con-nacimiento-y-con-transformación-logarítmica"><span class="header-section-number">4.4</span> Ejemplo con Nacimiento y con transformación logarítmica</a></li>
  <li><a href="#calidad-de-las-predicciones-para-los-modelos-con-y-sin-transformación-logarítmica" id="toc-calidad-de-las-predicciones-para-los-modelos-con-y-sin-transformación-logarítmica" class="nav-link" data-scroll-target="#calidad-de-las-predicciones-para-los-modelos-con-y-sin-transformación-logarítmica"><span class="header-section-number">4.5</span> Calidad de las predicciones para los modelos con y sin transformación logarítmica</a></li>
  </ul></li>
  <li><a href="#ejemplo-de-aplicación-para-la-serie-consumo-eléctrico" id="toc-ejemplo-de-aplicación-para-la-serie-consumo-eléctrico" class="nav-link" data-scroll-target="#ejemplo-de-aplicación-para-la-serie-consumo-eléctrico"><span class="header-section-number">5</span> Ejemplo de aplicación para la serie Consumo eléctrico</a>
  <ul class="collapse">
  <li><a href="#método-sencillo" id="toc-método-sencillo" class="nav-link" data-scroll-target="#método-sencillo"><span class="header-section-number">5.1</span> Método sencillo</a></li>
  <li><a href="#alisado-exponencial-1" id="toc-alisado-exponencial-1" class="nav-link" data-scroll-target="#alisado-exponencial-1"><span class="header-section-number">5.2</span> Alisado Exponencial</a>
  <ul class="collapse">
  <li><a href="#identificación-y-estimación-del-mejor-modelo-1" id="toc-identificación-y-estimación-del-mejor-modelo-1" class="nav-link" data-scroll-target="#identificación-y-estimación-del-mejor-modelo-1">Identificación y estimación del mejor modelo</a></li>
  <li><a href="#predicción-1" id="toc-predicción-1" class="nav-link" data-scroll-target="#predicción-1">Predicción</a></li>
  <li><a href="#análisis-del-error-1" id="toc-análisis-del-error-1" class="nav-link" data-scroll-target="#análisis-del-error-1">Análisis del error</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#otras-alternativas-para-ajustar-un-modelo-y-predecir" id="toc-otras-alternativas-para-ajustar-un-modelo-y-predecir" class="nav-link" data-scroll-target="#otras-alternativas-para-ajustar-un-modelo-y-predecir"><span class="header-section-number">6</span> Otras alternativas para ajustar un modelo y predecir</a></li>
  <li><a href="#resumen-de-los-comandos-utilizados" id="toc-resumen-de-los-comandos-utilizados" class="nav-link" data-scroll-target="#resumen-de-los-comandos-utilizados"><span class="header-section-number">7</span> Resumen de los comandos utilizados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Series con estacionalidad</h1>
<p class="subtitle lead">Previsión con Datos Temporales (GBIA)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><br>
<br>
</p>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>La mayoría de las series con fechado más fino que el anual (mensual, diario, horario…) tienen componente estacional. Esta componente tiene diversas causas: pautas sociales, climatología, estructura laboral, calendario… Así, vamos a finalizar nuestro recorrido a través de los diferentes tipos de series analizando y prediciendo las series con estacionalidad, con independencia de que tengan o no tendencia.</p>
<p>La <a href="#fig-ejemplos_con_estacionalidad" class="quarto-xref">Figura&nbsp;1</a> muestra ejemplos de este tipo de series. El panel (a) muestra los nacimientos mensuales en España desde enero de 1975 hasta diciembre de 2023. Es una serie cuya tendencia ha sufrido varios cambios en el periodo de análisis y con una marcada estacionalidad debida, principalmente, al número de días del mes (véase <a href="https://iarribasf.github.io/PrediccionSeriesTemporales-GBIA/03-02-Tema2.html">Tema 2</a>). El mes con menor número de nacimientos es febrero y, en general, los meses con más nacimientos son los de 31 días. El panel (b) muestra el consumo diario de electricidad (GWh) en España desde el 1 de enero de 2023 hasta el 31 de diciembre de 2023. Esta serie tiene una marcada estacionalidad, con un nivel de consumo elevado de lunes a viernes que alcanza su máximo el miércoles, y una caída importante en el consumo el fin de semana, especialmente el domingo (véase <a href="https://iarribasf.github.io/PrediccionSeriesTemporales-GBIA/03-02-Tema2.html">Tema 2</a>). Como de la serie de consumo eléctrico se muestran solo un año, no es posible ver si tiene tendencia. Los cambios de nivel en el consumo de electricidad dentro del año no deben confundirse con tendencia y son realmente producidos por una segunda componente estacional de orden 365 asociada a la temperatura y el uso de sistemas de climatización en oficinas y hogares.</p>
<div class="cell" data-layout="[[50,50]]" data-layout-align="center">
<div id="fig-ejemplos_con_estacionalidad" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ejemplos_con_estacionalidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ejemplos_con_estacionalidad" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ejemplos_con_estacionalidad-1" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ejemplos_con_estacionalidad-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-ejemplos_con_estacionalidad-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-ejemplos_con_estacionalidad">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ejemplos_con_estacionalidad-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Nacimientos
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ejemplos_con_estacionalidad" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ejemplos_con_estacionalidad-2" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ejemplos_con_estacionalidad-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-ejemplos_con_estacionalidad-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-ref-parent="fig-ejemplos_con_estacionalidad">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ejemplos_con_estacionalidad-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Consumo eléctrico
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ejemplos_con_estacionalidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Ejemplos de series con estacionalidad
</figcaption>
</figure>
</div>
</div>
<p>Aunque para que exista componente estacional el fechado debe ser mas frecuente que el anual, no todas las series con fechado mensual o diario tienen estacionalidad. Por ejemplo, la serie de Defunciones diarias analizada en el <a href="https://iarribasf.github.io/PrediccionSeriesTemporales-GBIA/03-03-Tema3.html">Tema 3</a> no tenía estacionalidad, y las ventas mensuales de un producto básico de alimentación (leche, patatas…) en un supermercado tampoco presentan estacionalidad.</p>
<p>El análisis de estas series es necesariamente más complejo y por ese motivo en este tema revisitaremos solo dos de los métodos vistos en los temas precedentes: los métodos sencillos y los métodos de Alisado exponencial. Los modelos Arima con estacionalidad los dejaremos para un tema aparte.</p>
<p><br>
<br>
</p>
</section>
<section id="métodos-sencillos-de-predicción" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Métodos sencillos de predicción</h1>
<p><br>
</p>
<section id="método-ingenuo-con-estacionalidad" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="método-ingenuo-con-estacionalidad"><span class="header-section-number">2.1</span> Método ingenuo con estacionalidad</h2>
<p>En el método ingenuo con estacionalidad la predicción para un periodo es la <strong>última observación disponible de la misma estación que la fecha que se desea predecir</strong>. Es decir, <span class="math inline">\(\hat{y}_{T+h}=y_{T-m(k+1)}\)</span>, donde</p>
<ul>
<li><span class="math inline">\(k\)</span> es la parte entera de <span class="math inline">\((h-1)/m\)</span>, el número de estaciones completas en el periodo de predicción previo al periodo <span class="math inline">\(T+h\)</span>.</li>
<li>Este método asume que <strong>la serie no tiene tendencia</strong>.</li>
<li>Función de <code>R</code>: <code>snaive(y, h)</code></li>
<li>Para series con estacionalidad este es el método ingenuo de comparación del MASE</li>
</ul>
<p><strong>No hay métodos sencillos cuando la serie tiene tendencia y estacionalidad</strong>, así que se suele usar el método ingenuo con estacionalidad.</p>
</section>
<section id="ejemplo-de-aplicación-a-la-serie-nacimientos" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="ejemplo-de-aplicación-a-la-serie-nacimientos"><span class="header-section-number">2.2</span> Ejemplo de aplicación a la serie Nacimientos</h2>
<p>Podemos usar el método ingenuo con estacionalidad con la serie Nacimientos para obtener una previsión a dos años vista. Consideraremos la serie sólo desde enero de 2020.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/Nacimientos.csv"</span>, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">ts</span>(nacimientos[, <span class="dv">2</span>],</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1975</span>, <span class="dv">1</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">window</span>(nacimientos, <span class="at">start =</span> <span class="dv">2000</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>snaive.nacimientos <span class="ot">&lt;-</span> <span class="fu">snaive</span>(nacimientos, </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                              <span class="at">h =</span> <span class="dv">24</span>, </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                              <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(snaive.nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    ME     RMSE     MAE      MPE     MAPE MASE      ACF1
Training set -273.0399 1703.946 1367.75 -1.04244 3.941892    1 0.7367184</code></pre>
</div>
</div>
<p>El error absoluto porcentual medio es del 3.9% (que corresponde a unos 1700 bebés según RMSE). Es decir, aplicando algo tan simple como predecir el número de nacimientos para un mes como los nacimientos del mismo mes del año previo, tenemos ya un error de ajuste muy bajo. Sin embargo, este método en general sobreestima algo el número de nacimientos (MPE inferior a -1%) y sus predicciones por intervalo no son fiables.</p>
<p>La <a href="#fig-nacimientossencillo" class="quarto-xref">Figura&nbsp;2</a> muestra la serie y la predicción que, debido al método usado, no incorpora la tendencia decreciente de los últimos años.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(snaive.nacimientos,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Nacimientos"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">PI =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nacimientossencillo" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nacimientossencillo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-nacimientossencillo-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nacimientossencillo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Nacimientos y predicción por el método Ingenuo con estacionalidad
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="alisado-exponencial" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Alisado exponencial</h1>
<p><br>
</p>
<section id="definición" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="definición"><span class="header-section-number">3.1</span> Definición</h2>
<p>En las series con tendencia y estacionalidad, para obtener una predicción en el periodo <span class="math inline">\(t+1\)</span> con datos hasta el periodo <span class="math inline">\(t\)</span> necesitamos tres componentes:</p>
<ul>
<li>La estimación del nivel de la serie en el periodo <span class="math inline">\(t\)</span>: <span class="math inline">\(l_t\)</span></li>
<li>La estimación de la pendiente de la serie en el periodo <span class="math inline">\(t\)</span>: <span class="math inline">\(b_t\)</span></li>
<li>La estimación de la estacionalidad en el mes correspondiente al periodo <span class="math inline">\(t+1\)</span> con datos hasta <span class="math inline">\(t\)</span>: <span class="math inline">\(s_{t + 1 - m}\)</span> (recuerda, <span class="math inline">\(m\)</span> es el orden estacional)</li>
</ul>
<p>A partir de estas componentes obtenidas en el periodo <span class="math inline">\(t\)</span> y para un esquema aditivo, se tendría que la predicción en el periodo <span class="math inline">\(t+1\)</span> es:</p>
<p><span class="math display">\[\widehat{y}_{t+1} = l_t + b_t + s_{t+1-m}.\]</span></p>
<p>En general, las componentes pueden <strong>existir o no</strong> y se pueden combinar entre ellas <strong>aditiva o multiplicativamente</strong>. Veamos algunos casos:</p>
<ul>
<li><p>Existen todas y son multiplicativas: <span class="math inline">\(\widehat{y}_{t+1}=l_t \cdot b_t \cdot s_{t + 1 - m}\)</span></p></li>
<li><p>Existen todas, nivel y pendiente aditivas, y estacionalidad multiplicativa: <span class="math inline">\(\widehat{y}_{t+1}=(l_t+b_t)s_{t + 1 - m}\)</span></p></li>
<li><p>No hay pendiente y la estacionalidad es aditiva: <span class="math inline">\(\widehat{y}_{t+1}=l_t+s_{t + 1 - m}\)</span></p></li>
</ul>
<p>En las expresiones previas hemos supuesto que se quería obtener una predicción a un periodo vista (<span class="math inline">\(\widehat{y}_{t+1}\)</span>). Si el objetivo es estimar una previsión <span class="math inline">\(h\)</span> periodos hacia delante desde el periodo <span class="math inline">\(t\)</span>, <span class="math inline">\(\widehat{y}_{t+h}\)</span>, hay que modificar la ecuación de predicción adecuadamente. Por ejemplo, para el caso aditivo se tendría que</p>
<p><span class="math display">\[\widehat{y}_{t+h} = l_t+hb_t+s_{t+h-m(k+1)}\]</span> donde <span class="math inline">\(k = \lfloor (h-1)/m\rfloor\)</span>.</p>
<p><br>
</p>
</section>
<section id="casos-posibles" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="casos-posibles"><span class="header-section-number">3.2</span> Casos posibles</h2>
<p>Recordemos que en función del tipo de tendencia de la serie teníamos cinco posibilidades (N, A, Ad, M y Md). Por otro lado, si la serie tiene estacionalidad, este puede ser aditiva (A) o multiplicativa (M). Por tanto, dentro de las series con estacionalidad hay 10 posibles casos, mostrados en la <a href="#tbl-taxonomia" class="quarto-xref">Tabla&nbsp;1</a>. En la tabla, la primera letra hace referencia al tipo de tendencia y la segunda al tipo de estacionalidad.</p>
<div id="tbl-taxonomia" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-taxonomia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Casos de alisado según el tipo de tendencia y estacionalidad
</figcaption>
<div aria-describedby="tbl-taxonomia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Tendencia</th>
<th style="text-align: center;"></th>
<th style="text-align: center;">Estacionalidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Aditiva (A)</td>
<td style="text-align: center;">Multiplicativa (M)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ninguna (N)</td>
<td style="text-align: center;">N, A</td>
<td style="text-align: center;">N, M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aditiva (A)</td>
<td style="text-align: center;"><strong>A, A</strong></td>
<td style="text-align: center;">A, M</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aditiva Amortiguada (Ad)</td>
<td style="text-align: center;"><strong>Ad, A</strong></td>
<td style="text-align: center;">Ad, M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Multiplicativa (M)</td>
<td style="text-align: center;">M, A</td>
<td style="text-align: center;">M, M</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multiplicativa Amortiguada (Md)</td>
<td style="text-align: center;">Md, A</td>
<td style="text-align: center;">Md, M</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Cada caso difiere en las componentes que se observan y su esquema, dando lugar a un conjunto diferente de ecuaciones recursivas de actualización.</p>
<p>Si a los 10 casos de la <a href="#tbl-taxonomia" class="quarto-xref">Tabla&nbsp;1</a> se añade que el error puede ser aditivo (A) o multiplicativo (M), obtenemos 20 posibilidades. Si, además, incluimos los 10 casos vistos en el <a href="https://iarribasf.github.io/PrediccionSeriesTemporales-GBIA/03-06-Tema6.html">Tema 6</a> para series sin estacionalidad, tenemos que una serie cualquiera se puede clasificar dentro de 30 posibilidades. <strong>Podemos estimar cualquiera de los treinta modelos usando la función <code>ets</code> del paquete <code>forecast</code>.</strong></p>
<p>Acude al artículo de <span class="citation" data-cites="Hyndman08">Hyndman and Khandakar (<a href="#ref-Hyndman08" role="doc-biblioref">2008</a>)</span> para saber más de cada modelo, o al libro de <span class="citation" data-cites="Hyndman08b">Hyndman et al. (<a href="#ref-Hyndman08b" role="doc-biblioref">2008</a>)</span>.</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Alisado de Holt-Winters aditivo (A, A, A) y multiplicativo (M, A, M)</h1>
<p>El método más usual de Alisado exponencial para una serie con tendencia y estacionalidad es el de Holt-Winters. Existen dos versiones según que el esquema sea aditivo o multiplicativo:</p>
<ul>
<li>(A, A, A): Alisado de Holt-Winters aditivo</li>
<li>(M, A, M): Alisado de Holt-Winters multiplicativo</li>
</ul>
<p>donde recordemos que las letras indican: error, tendencia y estacionalidad.</p>
<p><br>
</p>
<section id="alisado-de-holt-winters-aditivo-a-a-a" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="alisado-de-holt-winters-aditivo-a-a-a"><span class="header-section-number">4.1</span> Alisado de Holt-Winters aditivo (A, A, A)</h2>
<p>Las <strong>ecuaciones recursivas</strong> de actualización son:</p>
<p><span class="math display">\[
\begin{aligned}
l_t &amp; =\alpha (y_t - s_{t-m} ) + (1-\alpha)(l_{t-1}+b_{t-1}) \\
b_t &amp; =\beta (l_t - l_{t-1}) + (1-\beta)b_{t-1} \\
s_t &amp; =\gamma (y_t - l_{t-1} - b_{t-1}) + (1 - \gamma)s_{t-m}
\end{aligned}
\]</span> con <span class="math inline">\(0 \leq \alpha, \beta, \gamma \leq 1\)</span>.</p>
<p>La ecuación de la <strong>predicción intramuestral</strong> a un periodo vista es <span class="math display">\[\widehat{y}_{t+1}  = l_t + b_t + s_{t+1-m},\]</span> de forma que la ecuación de <strong>predicción extramuestral es</strong>: <span class="math display">\[\widehat{y}_{T+h}=l_T + h b_T + s_{T+h - m(k+1)},\]</span> con <span class="math inline">\(k = \lfloor(h-1)/m\rfloor\)</span>.</p>
<p>Observa que las ecuaciones para el nivel y la pendiente son similares a las ya vistas en el <a href="https://iarribasf.github.io/PrediccionSeriesTemporales-GBIA/03-06-Tema6.html">Tema 6</a> para el método de Holt. Respecto de la ecuación de actualización de la estacionalidad, dos estimaciones razonables de esta componente en el periodo <span class="math inline">\(t\)</span> son su valor estimado a partir de la serie menos su tendencia <span class="math inline">\(y_t-l_{t-1} - b_{t-1}\)</span>, y la estimación que ya teníamos de la estacionalidad previamente, <span class="math inline">\(s_{t-m}\)</span>. La estimación final es una media ponderada, parametrizada por <span class="math inline">\(0 \leq \gamma &lt; 1 - \alpha\)</span>.</p>
<p><strong>Interpretación del parámetro</strong> <span class="math inline">\(\gamma\)</span>:</p>
<ul>
<li>Si <span class="math inline">\(\gamma = 1\)</span>, <span class="math inline">\(s_t = y_t - l_{t-1} - b_{t-1}\)</span>, la estacionalidad se actualiza constantemente porque varía periodo a periodo</li>
<li>Si <span class="math inline">\(\gamma = 0\)</span>, <span class="math inline">\(s_t = s_{t-m}= \ldots = s_0\)</span>, la estacionalidad se mantiene constante en el tiempo.</li>
</ul>
<p><br>
</p>
</section>
<section id="alisado-de-holt-winters-multiplicativo-m-a-m1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="alisado-de-holt-winters-multiplicativo-m-a-m1"><span class="header-section-number">4.2</span> Alisado de Holt-Winters multiplicativo (M, A, M)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></h2>
<p>Las <strong>ecuaciones recursivas</strong> de actualización son:</p>
<p><span class="math display">\[
\begin{aligned}
l_t &amp; =\alpha \frac{y_t}{s_{t-m}} + (1-\alpha)(l_{t-1}+b_{t-1}) \\
b_t &amp; =\beta (l_t - l_{t-1}) + (1-\beta)b_{t-1} \\
s_t &amp; =\gamma \frac{y_t}{l_{t-1} + b_{t-1}} + (1 - \gamma)s_{t-m}
\end{aligned}
\]</span></p>
<p>La ecuación de la <strong>predicción intramuestral</strong> a un periodo vista es <span class="math display">\[\widehat{y}_{t+1}  = (l_t + b_t)s_{t+1-m},\]</span> de forma que la ecuación de <strong>predicción extramuestral es</strong>: <span class="math display">\[\widehat{y}_{T+h}=(l_T + h b_T)s_{T+h - m(k+1)}.\]</span><br>
</p>
</section>
<section id="ejemplo-con-nacimientos" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="ejemplo-con-nacimientos"><span class="header-section-number">4.3</span> Ejemplo con Nacimientos</h2>
<p>Vamos a usar el método de Alisado para predecir la serie Nacimientos.</p>
<section id="identificación-y-estimación-del-mejor-modelo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación-del-mejor-modelo">Identificación y estimación del mejor modelo</h3>
<p>Usaremos la función <code>ets</code> sin ningún tipo de restricción para que localice el modelo (de entre los 30 posibles) que mejor se ajusta a los datos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nacimientosEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(nacimientos)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nacimientosEts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,A,A) 

Call:
ets(y = nacimientos)

  Smoothing parameters:
    alpha = 0.4892 
    beta  = 0.0107 
    gamma = 1e-04 

  Initial states:
    l = 33052.834 
    b = 143.8979 
    s = -11.4659 3.8886 1957.737 1463.932 1013.289 1255.209
           -953.4959 217.809 -1369.601 -172.4478 -3318.506 -86.3485

  sigma:  906.7055

     AIC     AICc      BIC 
5570.926 5573.193 5633.196 

Training set error measures:
                    ME     RMSE      MAE        MPE    MAPE      MASE
Training set -64.51908 881.1593 672.4836 -0.2064835 1.96789 0.4916715
                   ACF1
Training set 0.05973202</code></pre>
</div>
</div>
<p>El mejor modelos (A, A, A) tiene error, tendencia y estacionalidad aditivas: <span class="math inline">\(y_t = l_{t-1} + b_{t-1} + s_{t + 1 - m}\)</span>.</p>
<p>El bajo valor de <span class="math inline">\(\beta\)</span> y <span class="math inline">\(\gamma\)</span> indican que ambas, la pendiente y la estacionalidad, varían muy lentamente en el tiempo (véase la <a href="#fig-nacimientoscomponentes" class="quarto-xref">Figura&nbsp;3</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(nacimientosEts,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Periodo"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nacimientoscomponentes" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nacimientoscomponentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-nacimientoscomponentes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nacimientoscomponentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Componentes del modelo óptimo para Nacimientos
</figcaption>
</figure>
</div>
</div>
</div>
<p>Respecto de la calidad del modelo, el MAPE de 2% indica que estamos ante un modelo que se ajusta muy bien a los datos; y el valor de MASE igual a 0.49 indica que este modelo reduce en un 51% el error del método ingenuo con estacionalidad, el más sencillo posible. El modelo no tiene sesgo y el valor de ACF1 de 0.06, inferior a 0.1, indica que el intervalo de confianza de las predicciones está bien calculado.</p>
<p>Podemos ver los últimos valores estimados del nivel, la pendiente y la estacionalidad para interpretarlos. Como el último dato de la serie es diciembre de 2023, los valores del nivel <span class="math inline">\(l\)</span> y la pendiente <span class="math inline">\(b\)</span> mostrados corresponden a ese mes. Sin embargo, <em>los valores de la componente estacional están ordenados al revés</em>: s1 es el valor estacional para diciembre (mes del último dato), s2 el de noviembre, hasta s12 que sería enero.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">nrow</span>(nacimientosEts<span class="sc">$</span>states)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>nacimientosEts<span class="sc">$</span>states[TT,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           l            b           s1           s2           s3           s4 
27041.914738   -55.737267   -11.607442     3.801462  1957.628722  1463.714031 
          s5           s6           s7           s8           s9          s10 
 1013.175595  1255.001436  -953.711757   217.589514 -1369.784143  -172.610401 
         s11          s12 
-3318.617718   -86.437475 </code></pre>
</div>
</div>
<p>Febrero es el mes con menor número de nacimientos: nacen 3318 bebés menos, respecto de la media anual. En octubre es cuando más bebés nacen: 1957 más que la media anual.</p>
<p>Podemos usar estos valores para predecir los próximos 12 meses de 2024 (ojo, el etiquetado de la salida no tiene sentido):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nacimientosEts<span class="sc">$</span>states[TT, <span class="dv">1</span>] <span class="sc">+</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>) <span class="sc">*</span> nacimientosEts<span class="sc">$</span>states[TT, <span class="dv">2</span>] <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  nacimientosEts<span class="sc">$</span>states[TT, <span class="dv">14</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     s12      s11      s10       s9       s8       s7       s6       s5 
26899.74 23611.82 26702.09 25449.18 26980.82 25753.78 27906.76 27609.19 
      s4       s3       s2       s1 
28003.99 28442.17 26432.61 26361.46 </code></pre>
</div>
</div>
<p>Nuestra predicción para enero de 2024 es de 26899.74 bebés y para diciembre de 2024 de 26361.46 bebés.</p>
</section>
<section id="predicción" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción">Predicción</h3>
<p>Si pedimos los valores de predicción tenemos (sólo se muestran los primeros meses):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nacimientosEtsPre <span class="ot">&lt;-</span> <span class="fu">forecast</span>(nacimientosEts, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">h =</span> <span class="dv">24</span>, </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>nacimientosEtsPre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2024       26899.74 25122.63 28676.85
Feb 2024       23611.82 21625.03 25598.61
Mar 2024       26702.09 24517.87 28886.32
Apr 2024       25449.18 23076.55 27821.81
May 2024       26980.82 24426.68 29534.96</code></pre>
</div>
</div>
<p>La <a href="#fig-nacimientosPrediccion" class="quarto-xref">Figura&nbsp;4</a> muestra la serie Nacimientos, su predicción a dos años vista y el intervalo de confianza.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(nacimientosEtsPre,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Nacimientos"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nacimientosPrediccion" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nacimientosPrediccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-nacimientosPrediccion-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nacimientosPrediccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Nacimientos y predicción
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="análisis-del-error" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="análisis-del-error">Análisis del error</h3>
<p>Se identifica varios valores claramente atípicos –superan las 3 desviaciones típicas– que corresponden a enero de 2011 y, aproximadamente, nueves después del confinamiento por la pandemia (diciembre de 2020, y febrero y marzo de 2021). Abril de 2008 y diciembre de 2010 son otros candidatos a intervención por superar las 2.5 desviaciones típicas.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(nacimientosEts)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Periodo"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span> ,<span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2024</span>, <span class="dv">2</span>)) </span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>fechas <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2000-1-1"</span>), <span class="fu">as.Date</span>(<span class="st">"2023-12-1"</span>), <span class="st">"month"</span>), <span class="st">"%Y-%m"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>fechas[<span class="fu">abs</span>(error) <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">*</span> sderror]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2011-01" "2020-12" "2021-02" "2021-03"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-NacimientosError" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NacimientosError-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-NacimientosError-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NacimientosError-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Error + Intervención
</figcaption>
</figure>
</div>
</div>
</div>
<p>Un método alternativo para obtener valores atípicos es la prueba de Tukey (véase la píldora <em>Valores perdidos y valores atípicos</em>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>atipicos <span class="ot">&lt;-</span> <span class="fu">tsoutliers</span>(error)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>fechas[atipicos<span class="sc">$</span>index]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2020-12"</code></pre>
</div>
</div>
<p>En este caso solo se identifica como atípico el valor de diciembre de 2020.</p>
<p><br>
</p>
</section>
</section>
<section id="ejemplo-con-nacimiento-y-con-transformación-logarítmica" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="ejemplo-con-nacimiento-y-con-transformación-logarítmica"><span class="header-section-number">4.4</span> Ejemplo con Nacimiento y con transformación logarítmica</h2>
<p>Una alternativa para predecir la serie Nacimientos es predecir la transformación logarítmica de la serie. Después, se aplica la transformación inversa y se obtienen las predicciones de la serie original. Recuerda que el argumento <code>lambda = 0</code> posibilita realizar todo el proceso de forma directa y sencilla.</p>
<p>Si pedimos a la función <code>ets</code> que identifique el mejor modelo para la transformación logarítmica de la serie Nacimientos, aparece un modelo con tendencia amortiguada y un valor de <span class="math inline">\(\phi = 0.978\)</span>, cercano al máximo valor permitido. Por este motivo, vamos a solicitar la identificación y estimación del mejor modelo excluyendo aquellos con tendencia amortiguada.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nacimientosEtsl &lt;- ets(nacimientos, lambda = 0)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>nacimientosEtsl <span class="ot">&lt;-</span> <span class="fu">ets</span>(nacimientos, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nacimientosEtsl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,N,A) 

Call:
ets(y = nacimientos, damped = FALSE, lambda = 0)

  Box-Cox transformation: lambda= 0 

  Smoothing parameters:
    alpha = 0.481 
    gamma = 1e-04 

  Initial states:
    l = 10.5517 
    s = -0.0015 -0.0031 0.0572 0.0468 0.0318 0.0416
           -0.0231 0.0064 -0.0408 -0.0017 -0.1018 -0.0117

  sigma:  0.029

      AIC      AICc       BIC 
-393.7052 -391.9405 -338.7608 

Training set error measures:
                    ME     RMSE      MAE        MPE     MAPE      MASE
Training set -72.14764 944.7309 706.6812 -0.2861817 2.063566 0.5166743
                  ACF1
Training set 0.1615821</code></pre>
</div>
</div>
<p>El modelo identificado es “ANA” que tiene error y estacionalidad aditiva y no tiene tendencia: <span class="math inline">\(\log(y_{t+1}) = l_{t} + s_{t + 1 - m} + \varepsilon_{t+1}\)</span>. En general, la transformación logarítmica de una serie sigue un esquema aditivo.</p>
<p>En este caso la calidad de las predicciones (MAPE = 2.1%) es algo inferior a la obtenida con la serie sin transformar. Además, con este modelo, las previsiones por intervalo no son fiables (solo se muestran los primeros meses).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>nacimientosfl <span class="ot">&lt;-</span> <span class="fu">forecast</span>(nacimientosEtsl,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">h =</span> <span class="dv">24</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>nacimientosfl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2024       26884.93 25401.90 28454.55
Feb 2024       24568.01 23068.81 26164.65
Mar 2024       27153.76 25352.86 29082.59
Apr 2024       26113.13 24254.13 28114.62
May 2024       27374.59 25301.98 29616.98</code></pre>
</div>
</div>
<p>La <a href="#fig-nacimientoslog" class="quarto-xref">Figura&nbsp;6</a> muestra la serie Nacimientos y las previsiones extramuestrales obtenidas con y sin la transformación logarítmica. En este caso, las previsiones con la serie sin transformar son algo mayores que las obtenidas con la serie transformada.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nacimientoslog" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nacimientoslog-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-nacimientoslog-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nacimientoslog-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Nacimientos y dos predicciones con alisado de Holt-Winters
</figcaption>
</figure>
</div>
</div>
</div>
<p>Recuerda, <strong>ni la transformación logarítmica ni el uso de predicciones insesgadas (<code>biasadj = TRUE</code>) aseguran mejores predicciones respecto de otras opciones</strong>.</p>
<p><br>
</p>
</section>
<section id="calidad-de-las-predicciones-para-los-modelos-con-y-sin-transformación-logarítmica" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="calidad-de-las-predicciones-para-los-modelos-con-y-sin-transformación-logarítmica"><span class="header-section-number">4.5</span> Calidad de las predicciones para los modelos con y sin transformación logarítmica</h2>
<p>Hemos visto que en calidad de ajuste, el modelo de Alisado sobre la serie sin transformar es superior a la del modelo sobre el logaritmo de la serie: mejores indicadores de calidad de ajuste e intervalo de confianza de las predicciones correctos.</p>
<p>Veamos ahora qué método ofrece las predicciones con menor error con origen de previsión móvil. Consideraremos que son necesarios 15 años para ajustar bien los modelos y haremos previsiones a 12 meses vista. Como criterio de calidad de las predicciones vamos a usar el MAPE.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">180</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">12</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">length</span>(nacimientos)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> TT <span class="sc">-</span> k <span class="sc">-</span> h</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>mapeAli <span class="ot">&lt;-</span> mapeAliL <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(nacimientos, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(nacimientos, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">ets</span>(train.set, <span class="at">model =</span> <span class="st">"AAA"</span>, <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  mapeAli[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">ets</span>(train.set, <span class="at">model =</span> <span class="st">"ANA"</span>, <span class="at">damped =</span> <span class="cn">FALSE</span>, <span class="at">lambda =</span> <span class="dv">0</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  mapeAliL[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>mapeAliMedia <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeAli)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>mapeAliLMedia <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeAliL)</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mapeAliMedia, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.40 2.73 2.89 2.97 2.90 2.89 3.12 3.17 3.28 3.30 3.10 3.07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mapeAliLMedia, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.44 2.91 3.24 3.44 3.46 3.51 3.93 4.11 4.21 4.35 4.38 4.54</code></pre>
</div>
</div>
<p>El método de Alisado sobre la serie original ofrece mejores predicciones para todos los horizontes temporales. A doce meses vista la diferencia es de 1.5 p.p.</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="ejemplo-de-aplicación-para-la-serie-consumo-eléctrico" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Ejemplo de aplicación para la serie Consumo eléctrico</h1>
<p><br>
</p>
<section id="método-sencillo" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="método-sencillo"><span class="header-section-number">5.1</span> Método sencillo</h2>
<p>Podemos usar el método ingenuo con estacionalidad con la serie Demanda eléctrica, que tiene una estacionalidad de orden 7, pero no parece presentar tendencia.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>snaive.electricidad <span class="ot">&lt;-</span> <span class="fu">snaive</span>(electricidad, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">h =</span> <span class="dv">28</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(snaive.electricidad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    ME    RMSE      MAE        MPE     MAPE MASE      ACF1
Training set 0.4959497 45.1574 31.82282 -0.1492087 4.743026    1 0.7470267</code></pre>
</div>
</div>
<p>El error absoluto porcentual medio es del 4.7% o 45 GWh (RMSE), un error razonablemente reducido y el método no presenta sesgo. Sin embargo, la fórmula usada para el cálculo del intervalo de confianza de las predicciones no es válida.</p>
<p>La <a href="#fig-electricidadsencillo" class="quarto-xref">Figura&nbsp;7</a> muestra la serie y la predicción a cuatro semanas vista. Debido a que la semana de referencia para predecir es la semana de Navidad, donde el consumo eléctrico es inferior al usual, las predicciones resultan ser claramente incorrectas. Este es un buen ejemplo de la diferencia entre calidad de ajuste y precisión de las predicciones.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(snaive.electricidad,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"GWh"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-electricidadsencillo" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-electricidadsencillo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-electricidadsencillo-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-electricidadsencillo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: Demanda eléctrica y predicción por el método Ingenuo con estacionalidad
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
<section id="alisado-exponencial-1" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="alisado-exponencial-1"><span class="header-section-number">5.2</span> Alisado Exponencial</h2>
<section id="identificación-y-estimación-del-mejor-modelo-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación-del-mejor-modelo-1">Identificación y estimación del mejor modelo</h3>
<p>El modelo óptimo sin restricciones es (MAdM) con un valor de <span class="math inline">\(\phi\)</span> cercano al máximo de 0.98, por lo que se solicita el modelo óptimo excluyendo modelos con tendencia amortiguada.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#electricidadEts &lt;- ets(electricidad)</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>electricidadEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(electricidad,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(electricidadEts) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,N,A) 

Call:
ets(y = electricidad, damped = FALSE)

  Smoothing parameters:
    alpha = 0.8585 
    gamma = 1e-04 

  Initial states:
    l = 696.9707 
    s = -49.2724 22.6105 35.9717 38.7919 33.4117 9.8245
           -91.3378

  sigma:  24.5881

     AIC     AICc      BIC 
4502.001 4502.623 4541.000 

Training set error measures:
                     ME     RMSE      MAE         MPE     MAPE      MASE
Training set -0.0244328 24.28306 14.89251 -0.08339514 2.300161 0.4679821
                 ACF1
Training set 0.024706</code></pre>
</div>
</div>
<p>Ahora el mejor modelo no presenta tendencia y tiene error y estacionalidad aditiva, es decir, <span class="math inline">\(y_{t+1} = l_t + s_{t+1-m} + \varepsilon_{t+1}\)</span>.</p>
<p>El valor <span class="math inline">\(\gamma = 0\)</span> indica que las estacionalidad se mantiene contante en el tiempo, mientras que el elevado valor de <span class="math inline">\(\alpha\)</span> indica que el nivel de la serie cambia de forma constante. Este cambio de nivel está relacionado con las variaciones en el consumo eléctrico debido a los cambios en la temperatura y el uso de aparatos de climatización.</p>
<p>Respecto de la calidad del modelo, el MAPE de 2.3% indica que estamos ante un modelo que se ajusta muy bien a los datos; no hay sesgo (MPE es casi cero); y el valor de ACF1, muy bajo, indica que la fórmula usada para el cálculo del intervalo de confianza de las predicciones es válida.</p>
<p>Podemos ver los últimos valores estimados del nivel y la estacionalidad para interpretarlos. Recuerda que los valores de la componente estacional están ordenados alrevés (s1 es domingo y s7 es lunes).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">nrow</span>(electricidadEts<span class="sc">$</span>states)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>electricidadEts<span class="sc">$</span>states[TT,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        l        s1        s2        s3        s4        s5        s6        s7 
689.31491 -91.33788 -49.26566  22.61608  35.97953  38.78392  33.40487   9.81824 </code></pre>
</div>
</div>
<p>El domingo la demanda eléctrica cae 91 GWh respecto de la media semanal. Por el contrario, el miércoles es el día de mayor incremento de demanda respecto de la media semanal, 39 GWh.</p>
<p>También podemos usar los últimos valores estimados del nivel y la estacionalidad para predecir una semana,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>electricidadEts<span class="sc">$</span>states[TT, <span class="dv">1</span>] <span class="sc">+</span> electricidadEts<span class="sc">$</span>states[TT, <span class="dv">8</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      s7       s6       s5       s4       s3       s2       s1 
699.1331 722.7198 728.0988 725.2944 711.9310 640.0493 597.9770 </code></pre>
</div>
</div>
</section>
<section id="predicción-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-1">Predicción</h3>
<p>Si pedimos los valores de predicción para las cuatro semanas siguientes, tenemos (sólo se muestran la primera):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>electricidadEtsPre <span class="ot">&lt;-</span> <span class="fu">forecast</span>(electricidadEts, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">h =</span> <span class="dv">28</span>, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>electricidadEtsPre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
54.00000       699.1331 650.9414 747.3249
54.14286       722.7198 659.2057 786.2338
54.28571       728.0988 652.2990 803.8987
54.42857       725.2944 638.9394 811.6495
54.57143       711.9310 616.1772 807.6848
54.71429       640.0493 535.7402 744.3583
54.85714       597.9770 485.7614 710.1927</code></pre>
</div>
</div>
<p>La <a href="#fig-electricidadPrediccion" class="quarto-xref">Figura&nbsp;8</a> muestra la serie Demanda eléctrica, su predicción a cuatro semanas vista y el intervalo de confianza.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(electricidadEtsPre,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"GWh"</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-electricidadPrediccion" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-electricidadPrediccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-electricidadPrediccion-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-electricidadPrediccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Demanda eléctrica y predicción
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="análisis-del-error-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="análisis-del-error-1">Análisis del error</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(electricidadEts)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Semana"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span> ,<span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">6</span>, <span class="dv">26</span>, <span class="dv">2</span>)) </span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>fechas <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2023-1-1"</span>), <span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>), <span class="st">"day"</span>), <span class="st">"%Y-%m-%d"</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>fechas[<span class="fu">abs</span>(error) <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">*</span> sderror]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "2023-01-01" "2023-01-06" "2023-01-07" "2023-04-06" "2023-04-08"
 [6] "2023-05-01" "2023-08-15" "2023-08-27" "2023-10-12" "2023-11-01"
[11] "2023-11-02" "2023-12-06" "2023-12-25"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-electricidadError" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-electricidadError-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-07-Tema7_files/figure-html/fig-electricidadError-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-electricidadError-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Error + Intervención
</figcaption>
</figure>
</div>
</div>
</div>
<p>El la <a href="#fig-electricidadError" class="quarto-xref">Figura&nbsp;9</a> se identifican múltiples días atípicos asociados con un consumo inferior al esperado debido a festividades: Año nuevo, Reyes, Semana Santa (el Viernes Santo fue el 7 de abril), Día del trabajador, Virgen de agosto, Día de la hispanidad, Todos los Santos, Día de la Constitución y Navidad. El Día de la Inmaculada (8 de diciembre) no aparece por caer en domingo.</p>
<p>También se observan tres días con un consumo mayor de lo esperado justo después de un festivo, el 7 de enero (tras Reyes), el 8 de abril (Sábado Santo) y el 2 de noviembre (tras Todos los Santos). Aquí la causa no es tanto un incremento inesperado del consumo, como la dinámica del propio método de estimación. Al llegar un día festivo, el método de Alisado falla ofreciendo una predicción más alta de la real y dando lugar a un error negativo. Al día siguiente, el método de Alisado ajusta su predicción a la baja, pero por no ser festivo vuelve a fallar, esta vez ofreciendo una predicción más baja de la real y dando lugar a un error positivo.</p>
<p>Veamos como en este caso la prueba de Tukey identifica las mismas fechas.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>atipicos <span class="ot">&lt;-</span> <span class="fu">tsoutliers</span>(error)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>fechas[atipicos<span class="sc">$</span>index]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "2023-01-01" "2023-01-06" "2023-01-07" "2023-04-06" "2023-04-08"
 [6] "2023-05-01" "2023-08-15" "2023-08-27" "2023-10-12" "2023-11-01"
[11] "2023-11-02" "2023-12-06" "2023-12-25"</code></pre>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
</section>
<section id="otras-alternativas-para-ajustar-un-modelo-y-predecir" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Otras alternativas para ajustar un modelo y predecir</h1>
<p>A la hora de ajustar un modelo a una serie y predecir hay que ser un poco imaginativos, dedicarle tiempo y probar cosas. Por ejemplo, podríamos considerar la transformación logarítmica de la serie. O podríamos cambiar el criterio de estimación de los parámetros o el de selección del modelo óptimo.</p>
<p>Yendo un poco más lejos, para una serie mensual (como Nacimientos) dado que el valor de la serie dependerá forzosamente del número de días del mes, podríamos ajustar y predecir el valor medio de la serie por día del mes. Por ejemplo, los nacimientos medios por día: cociente entre los nacimientos de cada mes y el número de días del mes. Esta serie tendrá una componente estacional más suave, al eliminar el efecto de los meses de febrero bisiestos, y tendrá, previsiblemente, un mejor ajuste.</p>
<p>También podemos mezclar varios de los enfoques previos o ser aún más imaginativos.</p>
<p>El siguiente código muestra el MAPE (para previsiones intramuestrales a un periodo vista) para la serie Nacimientos usando varias de estas opciones. Puedes deducir que se está haciendo en cada caso a partir del código. Sería más adecuado usar otro criterio de validación diferente, pero el objetivo de este epígrafe es recalcar que no hay que quedarse con lo inmediato (predecir una serie con las opciones por defecto de las funciones), sino probar y probar.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Serie Nacimientos</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.96789</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.967941</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.994566</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformación logarítmica</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.930586</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.930586</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.009007</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformación logarítmica insesgada</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">biasadj =</span> <span class="cn">TRUE</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.934107</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">biasadj =</span> <span class="cn">TRUE</span>,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.934107</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos, </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">biasadj =</span> <span class="cn">TRUE</span>,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.012254</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nacimientos por dia</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos<span class="sc">/</span><span class="fu">monthdays</span>(nacimientos)))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.871131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos<span class="sc">/</span><span class="fu">monthdays</span>(nacimientos), </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.871131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientos<span class="sc">/</span><span class="fu">monthdays</span>(nacimientos), </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.920431</code></pre>
</div>
</div>
<p>La principal conclusión en este caso es que salirse de la estimación directa sobre la serie original no reduce el error significativamente. Sin embargo, cabe destacar que,</p>
<ul>
<li>El error de estimación de los nacimientos por día es menor que el error obtenido con la serie original de nacimiento. Véanse los tres últimos modelos respecto de los tres primeros.</li>
<li>Usar la transformación logarítmica (con o sin predicciones insesgadas) puede mejorar o no la capacidad predictiva del modelo, dependiendo del resto de parámetros. Véanse los modelos 4 a 9 respecto de los modelos 1 a 3.</li>
<li>El mejor modelo estima los nacimientos por día y estima los parámetros minimizando la verosimilitud o el error cuadrático medio (“mse”). No siempre el uso directo de la serie ofrece los mejores resultados.</li>
</ul>
<p><br>
<br>
</p>
</section>
<section id="resumen-de-los-comandos-utilizados" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Resumen de los comandos utilizados</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Función</th>
<th style="text-align: left;">Paquete</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>monthdays</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">da el número de días de cada mes</td>
</tr>
</tbody>
</table>
<p><br>
<br>
<br>
<br>
</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Hyndman08" class="csl-entry" role="listitem">
Hyndman, Rob J., and Y. Khandakar. 2008. <span>“Automatic Time Series Forecasting: The Forecast Package for r.”</span> <em>Journal of Statistical Software</em> 27 (3): 1–22. <a href="https://doi.org/10.18637/jss.v027.i03">https://doi.org/10.18637/jss.v027.i03</a>.
</div>
<div id="ref-Hyndman08b" class="csl-entry" role="listitem">
Hyndman, Rob J., A. Koehler, K. Ord, and R. Snyder. 2008. <em>Forecasting with Exponential Smoothings. The State Space Approach</em>. Springer Berlin, Heidelberg. <a href="https://doi.org/10.1007/978-3-540-71918-2">https://doi.org/10.1007/978-3-540-71918-2</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Formalmente en el modelo de Holt-Winters multiplicativo el error es aditivo. Es decir, debería ser (A, A, M). Sin embargo, debido a que desde un punto de vista teórico este modelo, junto con otros, puede tener varianza infinita, la función <code>ets</code> no permite por defecto su estimación. Para poder estimar con la función <code>ets</code> el modelo (A, A, M) es necesario añadir el argumento <code>restrict = FALSE</code>. Los modelos que para poder ser estimados requieren este argumento son: ANM, AAM, AAdM, MMA, MMdA, AMN, AMdN, AMA, AMdA, AMM y AMdM.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Recuerda que el valor de 3 es uno de los posibles y debe ajustarse a las características de la serie y el análisis.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2024, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.es</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This page is built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>