<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Series Temporales - Series Temporales: Procesos ARIMA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Series Temporales</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Inicio</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html">Guía del curso</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html">Logística</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false">Diapos</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html">
 <span class="dropdown-text">Tema 1: Definicion y Componentes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html">
 <span class="dropdown-text">Tema 2: Alisado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html">
 <span class="dropdown-text">Tema 3: Procesos estocásticos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html">
 <span class="dropdown-text">Tema 4: ARIMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html">
 <span class="dropdown-text">Tema 5: SARIMA</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-06-Ejemplo1.html">
 <span class="dropdown-text">Ejemplo Tema 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Ejemplo2.html">
 <span class="dropdown-text">Ejemplo Tema 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-08-Ejemplo3.html">
 <span class="dropdown-text">Ejemplo Tema 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-09-Ejemplo4.html">
 <span class="dropdown-text">Ejemplo Tema 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo5.html">
 <span class="dropdown-text">Ejemplo Tema 5</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo-Pasajeros.html">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">Píldoras</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Nacimientos.html">
 <span class="dropdown-text">Efecto de la Covid-19 en Nacimientos</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html">Recursos de la asignatura</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Practica.html">Practica</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false">Más</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"> <span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#operador-retardo" id="toc-operador-retardo" class="nav-link" data-scroll-target="#operador-retardo"> <span class="header-section-number">2</span> Operador Retardo</a></li>
  <li><a href="#hipótesis" id="toc-hipótesis" class="nav-link" data-scroll-target="#hipótesis"> <span class="header-section-number">3</span> Hipótesis</a>
  <ul class="collapse">
  <li><a href="#sobre-el-proceso-estocástico" id="toc-sobre-el-proceso-estocástico" class="nav-link" data-scroll-target="#sobre-el-proceso-estocástico"> <span class="header-section-number">3.1</span> Sobre el proceso estocástico</a></li>
  <li><a href="#sobre-el-vector-de-residuos" id="toc-sobre-el-vector-de-residuos" class="nav-link" data-scroll-target="#sobre-el-vector-de-residuos"> <span class="header-section-number">3.2</span> Sobre el vector de residuos</a></li>
  </ul></li>
  <li><a href="#procesos-arima" id="toc-procesos-arima" class="nav-link" data-scroll-target="#procesos-arima"> <span class="header-section-number">4</span> Procesos ARIMA</a>
  <ul class="collapse">
  <li><a href="#procesos-autorregresivos-arp" id="toc-procesos-autorregresivos-arp" class="nav-link" data-scroll-target="#procesos-autorregresivos-arp"> <span class="header-section-number">4.1</span> Procesos autorregresivos AR(p)</a>
  <ul class="collapse">
  <li><a href="#definición" id="toc-definición" class="nav-link" data-scroll-target="#definición">Definición</a></li>
  <li><a href="#propiedades" id="toc-propiedades" class="nav-link" data-scroll-target="#propiedades">Propiedades</a></li>
  <li><a href="#ejemplos" id="toc-ejemplos" class="nav-link" data-scroll-target="#ejemplos">Ejemplos</a></li>
  <li><a href="#simulación-de-procesos-autorregresivos" id="toc-simulación-de-procesos-autorregresivos" class="nav-link" data-scroll-target="#simulación-de-procesos-autorregresivos">Simulación de procesos autorregresivos</a></li>
  </ul></li>
  <li><a href="#procesos-en-medias-móviles-maq" id="toc-procesos-en-medias-móviles-maq" class="nav-link" data-scroll-target="#procesos-en-medias-móviles-maq"> <span class="header-section-number">4.2</span> Procesos en medias móviles MA(q)</a>
  <ul class="collapse">
  <li><a href="#definición-1" id="toc-definición-1" class="nav-link" data-scroll-target="#definición-1">Definición</a></li>
  <li><a href="#propiedades-1" id="toc-propiedades-1" class="nav-link" data-scroll-target="#propiedades-1">Propiedades</a></li>
  <li><a href="#ejemplos-1" id="toc-ejemplos-1" class="nav-link" data-scroll-target="#ejemplos-1">Ejemplos</a></li>
  <li><a href="#simulación-de-procesos-en-medias-móviles" id="toc-simulación-de-procesos-en-medias-móviles" class="nav-link" data-scroll-target="#simulación-de-procesos-en-medias-móviles">Simulación de procesos en medias móviles</a></li>
  </ul></li>
  <li><a href="#procesos-armapq" id="toc-procesos-armapq" class="nav-link" data-scroll-target="#procesos-armapq"> <span class="header-section-number">4.3</span> Procesos ARMA(p,q)</a>
  <ul class="collapse">
  <li><a href="#definición-2" id="toc-definición-2" class="nav-link" data-scroll-target="#definición-2">Definición</a></li>
  <li><a href="#propiedades-2" id="toc-propiedades-2" class="nav-link" data-scroll-target="#propiedades-2">Propiedades</a></li>
  <li><a href="#ejemplos-2" id="toc-ejemplos-2" class="nav-link" data-scroll-target="#ejemplos-2">Ejemplos</a></li>
  <li><a href="#simulación-de-procesos-arma" id="toc-simulación-de-procesos-arma" class="nav-link" data-scroll-target="#simulación-de-procesos-arma">Simulación de procesos ARMA</a></li>
  </ul></li>
  <li><a href="#proceso-arimapdq" id="toc-proceso-arimapdq" class="nav-link" data-scroll-target="#proceso-arimapdq"> <span class="header-section-number">4.4</span> Proceso ARIMA(p,d,q)</a>
  <ul class="collapse">
  <li><a href="#ejemplos-3" id="toc-ejemplos-3" class="nav-link" data-scroll-target="#ejemplos-3">Ejemplos</a></li>
  <li><a href="#simulación-de-procesos-no-estacionarios" id="toc-simulación-de-procesos-no-estacionarios" class="nav-link" data-scroll-target="#simulación-de-procesos-no-estacionarios">Simulación de procesos no estacionarios</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#aproximación-de-box-jenkins" id="toc-aproximación-de-box-jenkins" class="nav-link" data-scroll-target="#aproximación-de-box-jenkins"> <span class="header-section-number">5</span> Aproximación de Box-Jenkins</a></li>
  <li><a href="#ejemplos-4" id="toc-ejemplos-4" class="nav-link" data-scroll-target="#ejemplos-4"> <span class="header-section-number">6</span> Ejemplos</a>
  <ul class="collapse">
  <li><a href="#títulos-de-libros-y-panfletos" id="toc-títulos-de-libros-y-panfletos" class="nav-link" data-scroll-target="#títulos-de-libros-y-panfletos"> <span class="header-section-number">6.1</span> Títulos de libros y panfletos</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie" id="toc-transformación-de-la-serie" class="nav-link" data-scroll-target="#transformación-de-la-serie">Transformación de la serie</a></li>
  <li><a href="#identificación" id="toc-identificación" class="nav-link" data-scroll-target="#identificación">Identificación</a></li>
  <li><a href="#estimación" id="toc-estimación" class="nav-link" data-scroll-target="#estimación">Estimación</a></li>
  <li><a href="#validación" id="toc-validación" class="nav-link" data-scroll-target="#validación">Validación</a></li>
  <li><a href="#predicción" id="toc-predicción" class="nav-link" data-scroll-target="#predicción">Predicción</a></li>
  <li><a href="#identificación-automática" id="toc-identificación-automática" class="nav-link" data-scroll-target="#identificación-automática">Identificación automática</a></li>
  </ul></li>
  <li><a href="#aforo-de-vehículos" id="toc-aforo-de-vehículos" class="nav-link" data-scroll-target="#aforo-de-vehículos"> <span class="header-section-number">6.2</span> Aforo de vehículos</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie-1" id="toc-transformación-de-la-serie-1" class="nav-link" data-scroll-target="#transformación-de-la-serie-1">Transformación de la serie</a></li>
  <li><a href="#identificación-y-estimación" id="toc-identificación-y-estimación" class="nav-link" data-scroll-target="#identificación-y-estimación">Identificación y estimación</a></li>
  <li><a href="#validación-1" id="toc-validación-1" class="nav-link" data-scroll-target="#validación-1">Validación</a></li>
  <li><a href="#interpretación-del-modelo" id="toc-interpretación-del-modelo" class="nav-link" data-scroll-target="#interpretación-del-modelo">Interpretación del modelo</a></li>
  <li><a href="#predicción-1" id="toc-predicción-1" class="nav-link" data-scroll-target="#predicción-1">Predicción</a></li>
  <li><a href="#validación-con-origen-de-predicción-móvil" id="toc-validación-con-origen-de-predicción-móvil" class="nav-link" data-scroll-target="#validación-con-origen-de-predicción-móvil">Validación con origen de predicción móvil</a></li>
  </ul></li>
  <li><a href="#consumo-de-alimentos-en-el-hogar-per-cápita" id="toc-consumo-de-alimentos-en-el-hogar-per-cápita" class="nav-link" data-scroll-target="#consumo-de-alimentos-en-el-hogar-per-cápita"> <span class="header-section-number">6.3</span> Consumo de alimentos en el hogar per cápita</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie-2" id="toc-transformación-de-la-serie-2" class="nav-link" data-scroll-target="#transformación-de-la-serie-2">Transformación de la serie</a></li>
  <li><a href="#identificación-y-estimación-1" id="toc-identificación-y-estimación-1" class="nav-link" data-scroll-target="#identificación-y-estimación-1">Identificación y Estimación</a></li>
  <li><a href="#validación-2" id="toc-validación-2" class="nav-link" data-scroll-target="#validación-2">Validación</a></li>
  <li><a href="#interpretación-del-modelo-1" id="toc-interpretación-del-modelo-1" class="nav-link" data-scroll-target="#interpretación-del-modelo-1">Interpretación del modelo</a></li>
  <li><a href="#predicciones-de-la-serie" id="toc-predicciones-de-la-serie" class="nav-link" data-scroll-target="#predicciones-de-la-serie">Predicciones de la serie</a></li>
  </ul></li>
  <li><a href="#comparación-con-alisado-exponencial" id="toc-comparación-con-alisado-exponencial" class="nav-link" data-scroll-target="#comparación-con-alisado-exponencial"> <span class="header-section-number">6.4</span> Comparación con alisado exponencial</a></li>
  </ul></li>
  <li><a href="#resumen-de-los-comandos-utilizados" id="toc-resumen-de-los-comandos-utilizados" class="nav-link" data-scroll-target="#resumen-de-los-comandos-utilizados"> <span class="header-section-number">7</span> Resumen de los comandos utilizados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Series Temporales: Procesos ARIMA</h1>
<p class="subtitle lead">Máster de Bioestadística (Modelización Estadística)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<div class="cell">

</div>
<div class="cell" data-layout-align="center">

</div>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Los <strong>modelos ARIMA</strong> han mostrado ser uno se los métodos de ajuste de series temporales más valiosos desde que fueran formalizados en 1976 por Box y Jenkins <span class="citation" data-cites="BoxJenkins76">(<a href="#ref-BoxJenkins76" role="doc-biblioref">Box and Jenkins 1976</a>)</span>. Además, dieron las pautas a seguir en el ajuste de una serie temporal para alcanzar buenas predicciones (véase epígrafe 5).</p>
<p>En este tema y el siguiente, definiremos estos procesos y aprenderemos a identificarlos, estimarlos y hacer predicciones.</p>
<p><strong>Los procesos ARIMA son ahora el tronco de una amplia familia de procesos</strong> que requieren menos hipótesis para su aplicación: ARCH, GARCH, NGARCH, IGARCH, EGARCH, GARCH-M, QGARCH, GJR-GARCH, TGARCH, fGARCH…</p>
<p><strong>Los procesos ARIMA y los métodos de Alisado Exponencial son complementarios</strong>:</p>
<ul>
<li>Los modelos de Alisado lineales son casos especiales de modelos Arima,</li>
<li>Los modelos de Alisado no lineales no tienen su contrapartida en modelos Arima</li>
<li>Muchos modelos Arima no tiene contrapartida en los modelos de Alisado.</li>
</ul>
<p><br>
<br>
</p>
</section>
<section id="operador-retardo" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Operador Retardo</h1>
<p>Definimos el <strong>operador retardo</strong> <span class="math inline">\(L\)</span> como <span class="math inline">\(Ly_t = y_{t-1}\)</span>, es decir, retrasa un periodo la serie. En inglés se denomina <em>lag operator</em> (L) o <em>backward shift</em> (B)</p>
<p>Así, se tiene que</p>
<p><span class="math display">\[L^k y_t  = y_{t-k}.\]</span></p>
<p>y por tanto que</p>
<span class="math display">\[\begin{aligned}
  \nabla y_t &amp; =  y_t - y_{t-1} = y_t - Ly_t = (1-L)y_t \\
  \nabla^d y_t &amp; =  (1-L)^d y_t \\
  \nabla_m y_t &amp; =  (1-L^m) y_t \\
  \nabla_m^D y_t &amp; =  (1-L^m)^D y_t
\end{aligned}\]</span>
<p>La <a href="#tbl-operadorretardo">Tabla&nbsp;1</a> muestra un sencillo ejemplo del efecto del operador retardo sobre la serie <span class="math inline">\(y_t\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-operadorretardo" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabla 1: Ejemplo de aplicación del operador retardo</caption>
<thead>
<tr class="header">
<th style="text-align: right;">y</th>
<th style="text-align: right;">lag1_y</th>
<th style="text-align: right;">lag2_y</th>
<th style="text-align: right;">lag3_y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
<section id="hipótesis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Hipótesis</h1>
<p><br>
</p>
<section id="sobre-el-proceso-estocástico" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sobre-el-proceso-estocástico"><span class="header-section-number">3.1</span> Sobre el proceso estocástico</h2>
<p>A lo largo de este tema asumiremos que:</p>
<ul>
<li><p><span class="math inline">\(\{y_t\}_{t=1}^T\)</span> es una realización de un proceso estocástico desconocido.</p></li>
<li><p>El proceso estocástico es <strong>estacionario en sentido amplio</strong>:</p></li>
</ul>
<p><span class="math display">\[E[y_t]  = \mu &lt; \infty \;\;\; \forall t,\]</span></p>
<p><span class="math display">\[Cov[y_t, y_{t-k}]  = \gamma_k  \;\;\; \forall k.\]</span></p>
<ul>
<li>El proceso estocástico es <strong>ergódico</strong>, o su condición suficiente:</li>
</ul>
<p><span class="math display">\[\lim_{k \rightarrow \infty} \gamma_k  = 0.\]</span></p>
<p><br>
</p>
</section>
<section id="sobre-el-vector-de-residuos" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sobre-el-vector-de-residuos"><span class="header-section-number">3.2</span> Sobre el vector de residuos</h2>
<p>También asumiremos que el residuo del modelo <span class="math inline">\(\{\varepsilon_t\}_{t=1}^T\)</span> es <strong>ruido blanco</strong>:</p>
<ul>
<li>Media cero: <span class="math inline">\(E[\varepsilon_t]=0\)</span></li>
</ul>
<ul>
<li>Varianza constante (homocedástico): <span class="math inline">\(E[\varepsilon_t^2]=\sigma^2\)</span></li>
</ul>
<ul>
<li>Incorrelación: <span class="math inline">\(E[\varepsilon_t \cdot \varepsilon_{s}]=0 \;\;\; t \neq s\)</span></li>
</ul>
<ul>
<li>Distribución Normal: <span class="math inline">\(\varepsilon_t \sim N\)</span></li>
</ul>
<p>Es decir, <span class="math inline">\(\varepsilon_t \sim N(0,\sigma^2)\)</span> i.i.d.</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="procesos-arima" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Procesos ARIMA</h1>
<p>ARIMA surge de combinar las siglas de tres procesos diferentes: <strong>AR</strong> de AutoRegresive, <strong>I</strong> de Integrated y <strong>MA</strong> de Moving Average. Veamos cada uno de estos tres conceptos por separado y luego su combinación.</p>
<p><br>
</p>
<section id="procesos-autorregresivos-arp" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="procesos-autorregresivos-arp"><span class="header-section-number">4.1</span> Procesos autorregresivos AR(p)</h2>
<section id="definición" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición">Definición</h3>
<p>El modelo general <strong>autorregresivo de orden p</strong>, <span class="math inline">\(y_t \sim AR(p)\)</span> viene definido por</p>
<p><span class="math display">\[y_t=c + \phi_1 y_{t-1} + \phi_2 y_{t-2} + \ldots + \phi_p y_{t-p} + \varepsilon_t,\]</span></p>
<p>que usando el operador retardo queda</p>
<p><span class="math display">\[(1 - \phi_1 L - \phi_2 L^2 - \ldots - \phi_p L^p)y_t = c + \varepsilon_t\]</span></p>
</section>
<section id="propiedades" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="propiedades">Propiedades</h3>
<p>El proceso es <strong>estacionario</strong> si quedan fuera del círculo de radio la unidad todas las raíces del polinomio autorregresivo</p>
<p><span class="math display">\[\Phi_p(z) = 1 - \phi_1 z - \phi_2 z^2 - \ldots - \phi_p z^p.\]</span></p>
<p>Es <strong>invertible</strong> siempre.</p>
<ul>
<li>Podemos transformar el proceso AR(p) en un proceso donde <span class="math inline">\(y_t\)</span> depende de la suma infinita de errores pasados, MA(<span class="math inline">\(\infty\)</span>).</li>
<li>Si conocemos las p primeras autocorrelaciones, podemos estimar los p parámetros del modelo. Por ejemplo, para un proceso AR(2) se verifica que:</li>
</ul>
<p><span class="math display">\[\rho_1 = \phi_1 + \phi_2 \rho_1\]</span></p>
<p><span class="math display">\[\rho_2 = \phi_1 \rho_1 + \phi_2\]</span></p>
<p>Estas ecuaciones se denominan <strong>Ecuaciones de Yule-Walker</strong>.</p>
<p>Observa que si tenemos una estimación de las dos primeras autocorrelaciones, estas ecuaciones nos permiten obtener una estimación de los coeficientes del proceso AR(2) como una aplicación del método de los momentos.</p>
<p><strong>Sobre todo</strong>,</p>
<ul>
<li>La FAC del proceso decae <em>exponencialmente</em> a partir del orden p</li>
<li>La FACP verifica que los p primeros valores son no nulos y todos los demás valen cero.</li>
</ul>
</section>
<section id="ejemplos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos">Ejemplos</h3>
<ul>
<li><p><span class="math inline">\(y_t \sim AR(1): \;\;y_t = c + \phi_1 y_{t-1} + \varepsilon_t\)</span> o <span class="math inline">\((1 - \phi_1 L)y_t = c + \varepsilon_t\)</span></p></li>
<li><p><span class="math inline">\(y_t \sim AR(2): \;\;y_t = c + \phi_1 y_{t-1} + \phi_2 y_{t-2} + \varepsilon_t\)</span> o <span class="math inline">\((1 - \phi_1 L - \phi_2 L^2)y_t = c + \varepsilon_t\)</span></p></li>
</ul>
</section>
<section id="simulación-de-procesos-autorregresivos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="simulación-de-procesos-autorregresivos">Simulación de procesos autorregresivos</h3>
<p>La <a href="#fig-simulAR">Figura&nbsp;1</a> muestra dos simulaciones del proceso AR(1) <span class="math inline">\(y_t = 0.8y_{t-1} + \varepsilon_t\)</span>, el panel superior con 20 datos y el inferior con 100 datos. En ambos casos <span class="math inline">\(\varepsilon_t\)</span> se distribuye como una normal con media cero y varianza la unidad. (Todas las simulaciones se han realizado con la función <code>arima.sim</code> de la librería <code>stats</code>.)</p>
<div class="cell" data-layout-align="center">

</div>
<div id="fig-simulAR" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulAR-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulAR-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulAR"></p>
<p></p><figcaption class="figure-caption">(a) n = 20</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulAR-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulAR-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulAR"></p>
<p></p><figcaption class="figure-caption">(b) n = 100</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 1: Simulación de dos procesos AR(1) con diferente tamaño muestral</figcaption><p></p>
</figure>
</div>
<p>La <a href="#fig-simulAR2">Figura&nbsp;2</a> muestra dos simulaciones de procesos AR(2), ambas con 100 datos. En el panes superior se tiene que <span class="math inline">\(y_t = 0.5y_{t-1} + 0.4 y_{t-2}+ \varepsilon_t\)</span> y en el inferior <span class="math inline">\(y_t = 0.9y_{t-1} - 0.5 y_{t-2}+ \varepsilon_t\)</span>.</p>
<div id="fig-simulAR2" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulAR2-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulAR2-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulAR2"></p>
<p></p><figcaption class="figure-caption">(a) Parámetros de igual signo</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulAR2-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulAR2-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulAR2"></p>
<p></p><figcaption class="figure-caption">(b) Parámetros de signo opuesto</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 2: Simulación de dos procesos AR(2) con n = 100</figcaption><p></p>
</figure>
</div>
<p><br>
</p>
</section>
</section>
<section id="procesos-en-medias-móviles-maq" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="procesos-en-medias-móviles-maq"><span class="header-section-number">4.2</span> Procesos en medias móviles MA(q)</h2>
<section id="definición-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición-1">Definición</h3>
<p>El modelo general <strong>en medias móviles de orden q</strong>, <span class="math inline">\(y_t \sim MA(q)\)</span> viene definido por</p>
<p><span class="math display">\[y_t=c + \varepsilon_t + \theta_1 \varepsilon_{t-1} + \theta_2 \varepsilon_{t-2} + \ldots + \theta_q \varepsilon_{t-q},\]</span></p>
<p>que usando el operador retardo queda</p>
<p><span class="math display">\[y_t = c + (1 + \theta_1 L + \theta_2 L^2 + \ldots + \theta_q L^q) \varepsilon_t\]</span></p>
</section>
<section id="propiedades-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="propiedades-1">Propiedades</h3>
<p>El proceso es <strong>invertible</strong> si quedan fuera del círculo de radio la unidad todas las raíces del polinomio en medias móviles</p>
<p><span class="math display">\[\Theta_q(z) = 1 + \theta_1 z + \theta_2 z^2 + \ldots + \theta_q z^q.\]</span></p>
<ul>
<li>Podemos transformar el proceso MA(q) en un proceso AR(<span class="math inline">\(\infty\)</span>).</li>
<li>Si conocemos las q primeras autocorrelaciones, podemos estimar los q parámetros del modelo. Por ejemplo, para un proceso MA(2) se verifica que:</li>
</ul>
<p><span class="math display">\[\rho_1 = \frac{\theta_1 + \theta_1\theta_2}{1 + \theta_1^2 + \theta_2^2}\]</span></p>
<p><span class="math display">\[\rho_2 = \frac{\theta_2}{1 + \theta_1^2 + \theta_2^2}\]</span></p>
<p>Es <strong>estacionario</strong> siempre.</p>
<p><strong>Sobre todo</strong>,</p>
<ul>
<li>La FAC verifica que los q primeros valores son no nulos y todos los demás valen cero.</li>
<li>La FACP decae <em>exponencialmente</em> a partir del orden q.</li>
</ul>
</section>
<section id="ejemplos-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-1">Ejemplos</h3>
<ul>
<li><p><span class="math inline">\(y_t \sim MA(1): \;\;y_t = c + \varepsilon_t + \theta_1 \varepsilon_{t-1}\)</span> o <span class="math inline">\(y_t = c + (1 + \theta_1 L)\varepsilon_t\)</span></p></li>
<li><p><span class="math inline">\(y_t \sim MA(2): \;\;y_t=c + \varepsilon_t + \theta_1 \varepsilon_{t-1} + \theta_2 \varepsilon_{t-2}\)</span> o <span class="math inline">\(y_t = c + (1 + \theta_1 L + \theta_2 L^2)\varepsilon_t\)</span></p></li>
</ul>
</section>
<section id="simulación-de-procesos-en-medias-móviles" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="simulación-de-procesos-en-medias-móviles">Simulación de procesos en medias móviles</h3>
<p>La <a href="#fig-simulMA">Figura&nbsp;3</a> ofrece dos simulaciones del proceso MA(1) <span class="math inline">\(y_t = 0.8\varepsilon_{t-1} + \varepsilon_t\)</span>, la primera con 20 datos y la segunda con 100 datos. En ambos casos <span class="math inline">\(\varepsilon_t\)</span> se distribuye como una normal con media cero y varianza la unidad.</p>
<div class="cell" data-layout-align="center">

</div>
<div id="fig-simulMA" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulMA-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulMA-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulMA"></p>
<p></p><figcaption class="figure-caption">(a) n = 20</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulMA-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulMA-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulMA"></p>
<p></p><figcaption class="figure-caption">(b) n = 100</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 3: Simulación de dos procesos MA(1) con diferente tamaño muestral</figcaption><p></p>
</figure>
</div>
<p>Veamos ahora dos simulaciones de procesos MA(2), ambas con 100 datos (<a href="#fig-simulMA2">Figura&nbsp;4</a>). En el panel superior se tiene que <span class="math inline">\(y_t = 0.5\varepsilon_{t-1} + 0.4 \varepsilon_{t-2}+ \varepsilon_t\)</span> y en el panel inferior <span class="math inline">\(y_t = 0.9\varepsilon_{t-1} - 0.5 \varepsilon_{t-2}+ \varepsilon_t\)</span>.</p>
<div id="fig-simulMA2" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulMA2-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulMA2-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulMA2"></p>
<p></p><figcaption class="figure-caption">(a) Parámetros de igual signo</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulMA2-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulMA2-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulMA2"></p>
<p></p><figcaption class="figure-caption">(b) Parámetros de signo opuesto</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 4: Simulación de dos procesos MA(2) con n = 100</figcaption><p></p>
</figure>
</div>
<p><br>
</p>
</section>
</section>
<section id="procesos-armapq" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="procesos-armapq"><span class="header-section-number">4.3</span> Procesos ARMA(p,q)</h2>
<section id="definición-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición-2">Definición</h3>
<p>El modelo general <span class="math inline">\(y_t \sim ARMA(p,q)\)</span> viene dado por</p>
<p><span class="math display">\[y_t = c + \phi_1 y_{t-1} + \phi_2 y_{t-2} + \ldots + \phi_p y_{t-p}  +
        \theta_1 \varepsilon_{t-1} + \theta_2 \varepsilon_{t-2} + \ldots +
        \theta_q \varepsilon_{t-q}+ \varepsilon_t,\]</span> que usando el operador retardo queda</p>
<p><span class="math display">\[(1 - \phi_1 L - \ldots - \phi_p L^p)y_t = c + (1 + \theta_1 L + \ldots + \theta_q L^q) \varepsilon_t.\]</span></p>
<p>El proceso más simple es el ARMA(1,1), <span class="math inline">\(y_t = c + \phi_1 y_{t-1} + \theta_1 \varepsilon_{t-1} + \varepsilon_{t}\)</span>.</p>
</section>
<section id="propiedades-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="propiedades-2">Propiedades</h3>
<p>El proceso es <strong>estacionario</strong> si quedan fuera del círculo de radio la unidad todas las raíces del polinomio</p>
<p><span class="math display">\[\Phi_p(z) = 1 - \phi_1 z - \phi_2 z^2 - \ldots - \phi_p z^p.\]</span></p>
<p>El proceso es <strong>invertible</strong> si quedan fuera del círculo de radio la unidad todas las raíces del polinomio</p>
<p><span class="math display">\[\Theta_q(z) = 1 + \theta_1 z + \theta_2 z^2 + \ldots + \theta_q z^q.\]</span></p>
<p><strong>Sobre todo</strong>,</p>
<ul>
<li>La FAC decae exponencialmente a partir del orden p.</li>
<li>La FACP decae exponencialmente a partir del orden q.</li>
</ul>
</section>
<section id="ejemplos-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-2">Ejemplos</h3>
<ul>
<li><p><span class="math inline">\(y_t \sim ARMA(1, 1): \;\;y_t = c + \phi_1 y_{t-1} + \theta_1 \varepsilon_{t-1} + \varepsilon_{t}\)</span> o <span class="math inline">\((1 - \phi_1 L)y_t = c + (1 + \theta_1 L)\varepsilon_t\)</span>.</p></li>
<li><p><span class="math inline">\(y_t \sim ARMA(0, 0): \;\;y_t = c + \varepsilon_{t}\)</span>. Si <span class="math inline">\(c = 0\)</span>, a este proceso se le denomina <strong>ruido blanco</strong>.</p></li>
</ul>
</section>
<section id="simulación-de-procesos-arma" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="simulación-de-procesos-arma">Simulación de procesos ARMA</h3>
<p>La <a href="#fig-simulARMA1">Figura&nbsp;5</a> muestra las FAC y FACP de una simulación de tamaño 200 para un proceso ARMA(1,1), la <a href="#fig-simulARMA2">Figura&nbsp;6</a> para un proceso ARMA(2,1) y la <a href="#fig-simulARMA3">Figura&nbsp;7</a> para un ARMA(1,2). En todos los casos <span class="math inline">\(\varepsilon_t\)</span> se distribuye como una normal con media cero y varianza la unidad.</p>
<div class="cell" data-layout-align="center">

</div>
<p><span class="math inline">\(y_t = 0.7y_{t-1} + 0.6\varepsilon_{t-1} + \varepsilon_t\)</span></p>
<div id="fig-simulARMA1" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-simulARMA1-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARMA1-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulARMA1"></p>
<p></p><figcaption class="figure-caption">(a) Función de autocorrelación</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-simulARMA1-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARMA1-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulARMA1"></p>
<p></p><figcaption class="figure-caption">(b) Función de autocorrelación parcial</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 5: Simulación de un proceso ARMA(1, 1)</figcaption><p></p>
</figure>
</div>
<p><span class="math inline">\(y_t = 0.7y_{t-1}- 0.5y_{t-2} + 0.6\varepsilon_{t-1} + \varepsilon_t\)</span></p>
<div id="fig-simulARMA2" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-simulARMA2-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARMA2-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulARMA2"></p>
<p></p><figcaption class="figure-caption">(a) Función de autocorrelación</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-simulARMA2-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARMA2-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulARMA2"></p>
<p></p><figcaption class="figure-caption">(b) Función de autocorrelación parcial</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 6: Simulación de un proceso ARMA(2, 1)</figcaption><p></p>
</figure>
</div>
<p><span class="math inline">\(y_t = 0.6y_{t-1} + 0.5\varepsilon_{t-1} + 0.3\varepsilon_{t-2} + \varepsilon_t\)</span></p>
<div id="fig-simulARMA3" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-simulARMA3-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARMA3-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulARMA3"></p>
<p></p><figcaption class="figure-caption">(a) Función de autocorrelación</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-simulARMA3-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARMA3-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulARMA3"></p>
<p></p><figcaption class="figure-caption">(b) Función de autocorrelación parcial</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 7: Simulación de un proceso ARMA(2, 1)</figcaption><p></p>
</figure>
</div>
<p><br>
</p>
</section>
</section>
<section id="proceso-arimapdq" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="proceso-arimapdq"><span class="header-section-number">4.4</span> Proceso ARIMA(p,d,q)</h2>
<p><strong>Si la serie <span class="math inline">\(y_t\)</span> no es estacionaria pero tras diferenciarla <span class="math inline">\(d\)</span> veces se hace estacionaria, diremos que la serie es integrada de orden <span class="math inline">\(d\)</span></strong>: <span class="math inline">\(y_t \sim I(d)\)</span>. Por tanto,</p>
<ul>
<li>una serie estacionaria se indicará como <span class="math inline">\(y_t \sim I(0)\)</span></li>
<li><span class="math inline">\(y_t \sim I(d)\)</span> es equivalente a <span class="math inline">\(\nabla^d y_t = (1 - L)^d y_t \sim I(0)\)</span></li>
</ul>
<p>Una serie <span class="math inline">\(y_t\)</span> sigue un proceso <strong><span class="math inline">\(ARIMA(p,d,q)\)</span></strong> si:</p>
<ol type="1">
<li><span class="math inline">\(y_t \sim I(d)\)</span> (hay que diferenciarla <span class="math inline">\(d\)</span> veces para hacerla estacionaria), y</li>
<li><span class="math inline">\(\nabla^d y_t \sim ARMA(p,q)\)</span>.</li>
</ol>
<p>Entonces, podemos escribir: <span class="math display">\[\begin{equation*}
\begin{array}{c@{\qquad}c@{\quad}ccc}
  y_t \sim  ARIMA(p,d,q): &amp; (1 - \phi_1 L - \ldots - \phi_p L^p) &amp; (1- L)^d y_t &amp; = &amp; c + (1 + \theta_1 L + \ldots + \theta_q L^q) \varepsilon_t \\
                          &amp; \uparrow                            &amp; \uparrow      &amp;   &amp; \uparrow \\
                          &amp; AR(p)                               &amp; I(d)          &amp;   &amp; MA(q)
\end{array}
\end{equation*}\]</span></p>
<section id="ejemplos-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-3">Ejemplos</h3>
<ul>
<li><p><span class="math inline">\(y_t \sim ARIMA(1, 1, 1): \;\;(1 - \phi_1 L)(1- L) y_t = c + (1 + \theta_1 L) \varepsilon_t\)</span> o <span class="math inline">\(y_t = c + y_{t-1} + \phi_1(y_{t-1} - y_{t-2}) + \theta_1 \varepsilon_{t-1} + \varepsilon_t\)</span>.</p></li>
<li><p><span class="math inline">\(\log(y_t) \sim ARIMA(1, 1, 1): \;\;(1 - \phi_1 L)(1- L) \log(y_t) = (1 - \phi_1 L)TVy_t = c + (1 + \theta_1 L) \varepsilon_t\)</span> o <span class="math inline">\(TVy_t = c + \phi_1 TVy_{t-1} + \theta_1 \varepsilon_{t-1} + \varepsilon_t\)</span>.</p></li>
<li><p><span class="math inline">\(y_t \sim ARIMA(0, 1, 0): \;\;(1- L) y_t = c + \varepsilon_t\)</span> o <span class="math inline">\(y_t = c + y_{t-1} + \varepsilon_t\)</span>. Si <span class="math inline">\(c=0\)</span>, tenemos un <strong>paseo aleatorio</strong>; si <span class="math inline">\(c \neq 0\)</span>, tenemos un <strong>paseo aleatorio con deriva</strong>.</p></li>
</ul>
</section>
<section id="simulación-de-procesos-no-estacionarios" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="simulación-de-procesos-no-estacionarios">Simulación de procesos no estacionarios</h3>
<p>Veamos la FAC de tres series simuladas no estacionarias (<a href="#fig-simulARIMA">Figura&nbsp;8</a>): un paseo aleatorio, un paseo aleatorio con deriva y un modelo lineal. Sus FAC son indistinguibles, pero los tres casos revelan claramente su carácter no estacionario.</p>
<div class="cell" data-layout-align="center">

</div>
<div id="fig-simulARIMA" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulARIMA-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARIMA-1.png" class="img-fluid figure-img" data-ref-parent="fig-simulARIMA"></p>
<p></p><figcaption class="figure-caption">(a) Paseo aleatorio</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulARIMA-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARIMA-2.png" class="img-fluid figure-img" data-ref-parent="fig-simulARIMA"></p>
<p></p><figcaption class="figure-caption">(b) Determinista lineal</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-simulARIMA-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-simulARIMA-3.png" class="img-fluid figure-img" data-ref-parent="fig-simulARIMA"></p>
<p></p><figcaption class="figure-caption">(c) Paseo aleatorio con deriva</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 8: FAC para tres procesos no estacionarios simulados</figcaption><p></p>
</figure>
</div>
<p><br>
<br>
</p>
</section>
</section>
</section>
<section id="aproximación-de-box-jenkins" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Aproximación de Box-Jenkins</h1>
<p>La <a href="#fig-AproximaciónBoxJenkins">Figura&nbsp;9</a> muestra el flujo de procesos asociado a la modelización por modelos ARIMA, con cuatro grandes áreas:</p>
<ul>
<li><p><strong>Identificación</strong>, que requiere primero transformar la serie para que sea estacionaria y ergódica, para después identificar los valores de p y q.</p>
<p>La FAC y la función de autocorrelación parcial teóricas son diferentes en cada tipo de proceso. Por tanto, idealmente estas funciones podría servir de ayuda en la identificación del modelo. En la práctica, la funciones estimadas son tan diferentes de las teóricas que resultan de muy poca ayuda.</p>
<p>Nosotros haremos uso de algunas funciones de <em>auto</em> identificación que nos ayudaran en este punto.</p></li>
<li><p><strong>Estimación</strong> de los parámetros del modelo, incluidas las variables de intervención y obtención del error. El método usual de estimación de los parámetros es por máxima verosimilitud.</p></li>
<li><p><strong>Validación</strong> de las hipótesis sobre el modelo. Analizaremos que no es necesaria más intervención y veremos la pertinencia de los parámetros del modelo (bien contrastando su significatividad o bien por alguna regla más sencilla).</p>
<p>Si la validación no se pasa, puede ser necesario volver al proceso inicial y realizar una nueva identificación del modelo.</p></li>
<li><p><strong>Predicción</strong> e interpretación del modelo válido. Si las predicciones se alejan de los valores reales más de lo esperado o presentan sesgo, puede ser necesario identificar y estimar un nuevo modelo.</p></li>
</ul>
<div id="fig-AproximaciónBoxJenkins" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./imagenes/BoxJenkins.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figura 9: Esquema de la aproximación de Box-Jenkins a la modelización de procesos ARIMA</figcaption><p></p>
</figure>
</div>
<p><br>
<br>
</p>
</section>
<section id="ejemplos-4" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Ejemplos</h1>
<p><br>
</p>
<section id="títulos-de-libros-y-panfletos" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="títulos-de-libros-y-panfletos"><span class="header-section-number">6.1</span> Títulos de libros y panfletos</h2>
<p>Vamos a aplicar la metodología de Box-Jenkins a la serie Libros (número de títulos publicados anualmente en España desde 1993 hasta 2019).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/libros.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">ts</span>(libros[, <span class="dv">2</span>], <span class="at">start =</span> <span class="dv">1993</span>, <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(libros,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Titulos"</span>, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Libros" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-Libros-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 10: Títulos publicados</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="transformación-de-la-serie" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie">Transformación de la serie</h3>
<p>El primer paso es transformar la serie original para que sea estacionaria. En el tema 3 ya vimos que la primera diferencia de la serie Libros es estacionaria y ergódica. Es decir, <span class="math inline">\(d=1\)</span> o <span class="math inline">\(libros_t \sim I(1)\)</span>. Como recordatorio, la <a href="#fig-LibrosFAC">Figura&nbsp;11</a> muestra la gráfica temporal y la FAC para la serie original y su primera diferencia.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(libros, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(<span class="fu">diff</span>(libros), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(libros, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(libros), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-LibrosFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-LibrosFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-LibrosFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(b) Dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-LibrosFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(c) FAC serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-LibrosFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(d) FAC dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 11: Gráfica y FAC para Libros</figcaption><p></p>
</figure>
</div>
</section>
<section id="identificación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación">Identificación</h3>
<p>Tras diferenciar la serie, vamos a identificar los valores de <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span> a partir de las FAC y FACP de la serie diferenciada (<a href="#fig-LibrosDisplay">Figura&nbsp;12</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtsdisplay</span>(<span class="fu">diff</span>(libros), <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-LibrosDisplay" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-LibrosDisplay-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 12: Libros (primera diferencia</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Observamos que:</p>
<ul>
<li>En la FAC ninguna autocorrelación sobrepasa las líneas que marcan el intervalo de confianza al 95%.</li>
<li>En la FACP tampoco las autocorrelaciones parciales sobrepasan el intervalo de confianza.</li>
</ul>
<p>Parece, por tanto, ruido blanco, <span class="math inline">\(p=q=0\)</span>. La identificación inicial es <span class="math inline">\(libros_t \sim ARIMA(0,1,0)\)</span>, paseo aleatorio, que inicialmente asumiremos con deriva:</p>
<p><span class="math display">\[libros_t = c + libros_{t-1} + \varepsilon_t\]</span></p>
</section>
<section id="estimación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estimación">Estimación</h3>
<p>Aunque existe la función <code>arima</code> de <code>stats</code>, vamos a usar la función <code>Arima</code> de la librería <code>forecast</code> para estimar el modelo identificado por ser más versátil. El argumento <code>order</code> indica los valores de (p, d , q) como un vector y el argumento lógico <code>include.constant</code> fuerza a que se incluya la constante <span class="math inline">\(c\)</span> en el modelo. (Mira en la ayuda de la función <code>Arima</code> la diferencia entre los argumentos <code>include.mean</code>, <code>include.drift</code> e <code>include.constant</code>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>arima010 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(libros, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.constant =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>arima010</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: libros 
ARIMA(0,1,0) with drift 

Coefficients:
          drift
       899.8462
s.e.  1145.2509

sigma^2 = 35465569:  log likelihood = -262.38
AIC=528.75   AICc=529.27   BIC=531.27</code></pre>
</div>
</div>
<p>Una forma rápida, aunque imprecisa, de determinar si un coeficiente es relevante (significativo) es compararlo con su error estándar (standard error, s.e). Si el coeficiente es mayor que dos veces su error estándar, hay evidencia de que es significativo. En la salida de <code>R</code>, en la tabla <code>Coefficients</code> tienes en la primera fila el nombre de los coeficientes; su valor estimado aparece en la segunda fila de la tabla; y los errores estándar en la tercera fila (encabezada por s.e.). Con esta regla, parece que la constante (<code>drift</code>) no es significativa.</p>
<p>A fin de poner un poco de <em>objetividad</em> en la decisión, podemos ver si sus coeficientes son significativos (distintos de cero). La prueba de Wald permite contrastar si un subconjunto de coeficientes es significativo (se precisa la librería <code>aod</code>). Esta función requiere de tres argumentos: el vector de coeficientes (<code>b</code>), su matriz de covarianzas (<code>Sigma</code>) y la posición del coeficiente cuya significatividad deseamos contrastar (<code>Terms</code>). Los dos primeros argumentos los podemos obtener del objeto <code>arima210</code> con las funciones <code>coef</code> y <code>vcov</code>.</p>
<p>Vamos a usar la función <code>wald.test</code> para contrastar si la contante (primer y único coeficiente del modelo) es significativo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima010), </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima010), </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">Terms =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 0.62, df = 1, P(&gt; X2) = 0.43</code></pre>
</div>
</div>
<p>Como el valor de p, igual a 0.432 es mayor que la significatividad <span class="math inline">\(\alpha =\)</span> 0.05, se concluye que la constante no es significativa, no hay deriva.</p>
<p>Reestimamos el modelo como un paseo aleatorio sin deriva,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>arima010 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(libros, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.constant =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>arima010</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: libros 
ARIMA(0,1,0) 

sigma^2 = 34911235:  log likelihood = -262.68
AIC=527.36   AICc=527.53   BIC=528.62</code></pre>
</div>
</div>
<p>Nuestro modelo estimado es: <span class="math inline">\(\widehat{libros}_t = libros_{t-1}\)</span> ¡el método ingenuo I!</p>
</section>
<section id="validación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación">Validación</h3>
<p>Veamos si el residuo verifica todas las hipótesis indicadas en el epígrafe 3.2</p>
<p><strong>Media cero</strong></p>
<p>No se puede contrastar si el residuo tiene <strong>media cero</strong>, pero el error medio es <span class="math inline">\(ME=\)</span> 868.03, relativamente bajo en comparación con el valor medio de la serie.</p>
<p>Además, tenemos las diferentes medidas de bondad del ajuste. En media nos equivocamos en 5798 títulos (RMSE) y el error porcentual medio (MAPE) es 6.9%.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(arima010)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                 ME    RMSE     MAE  MPE MAPE MASE  ACF1
Training set 868.03 5798.12 4358.32 1.29 6.88 0.96 -0.04</code></pre>
</div>
</div>
<p><br>
</p>
<p><strong>Incorrelación</strong></p>
<p>Lo veremos con el test de Box-Ljung</p>
<ul>
<li>La hipótesis nula es <span class="math inline">\(H_0: \rho_1 = ... = \rho_k = 0\)</span></li>
<li>El valor de p = 0.894 es mayor que el nivel de significatividad 0.05. No se rechaza la hipótesis de incorrelación, hasta el orden <span class="math inline">\(k = 2\)</span>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima010)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(error, <span class="at">lag =</span> <span class="dv">2</span>,<span class="at">type =</span> <span class="st">"Ljung-Box"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  error
X-squared = 0.22466, df = 2, p-value = 0.8938</code></pre>
</div>
</div>
<p>La elección de dos retardos para la prueba, fijado con el parámetros <code>lag = 2</code>, es bastante arbitraria. Sería mejor realizar la prueba para un rango de valores de <span class="math inline">\(k\)</span> (véase <a href="#tbl-librosInco">Tabla&nbsp;2</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-librosInco" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabla 2: Prueba de incorrelacion para diferentes valores del retardo</caption>
<thead>
<tr class="header">
<th style="text-align: right;">k</th>
<th style="text-align: right;">valor.de.p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.832</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.894</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.966</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.990</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><br>
</p>
<p><strong>Homocedasticidad (varianza constante)</strong></p>
<p>Lo veremos con el test de Box-Ljung para el residuo al cuadrado. La hipótesis nula seria que las primeras <span class="math inline">\(k\)</span> autocorrelaciones estimadas sobre el cuadrado del residuo son cero.</p>
<p>El valor de p = 0.411 es mayor que el nivel de significatividad 0.05. No se rechaza la hipótesis de homocedasticidad, hasta el orden 2.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(error<span class="sc">^</span><span class="dv">2</span>, <span class="at">lag =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"Ljung-Box"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  error^2
X-squared = 1.7794, df = 2, p-value = 0.4108</code></pre>
</div>
</div>
<p>De nuevo, la elección de dos retardos es totalmente arbitraria y sería mejor realizar la prueba para un rango de valores de <span class="math inline">\(k\)</span> (véase <a href="#tbl-librosHomo">Tabla&nbsp;3</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-librosHomo" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabla 3: Prueba de homocedasticidad para diferentes valores del retardo</caption>
<thead>
<tr class="header">
<th style="text-align: right;">k</th>
<th style="text-align: right;">valor.de.p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.359</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.411</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.343</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.142</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><br>
</p>
<p><strong>Normalidad</strong></p>
<p>Recuerda que todos las pruebas de normalidad son muy sensibles al tamaño de la muestra. Siempre es recomendable empezar por un análisis gráfico (histograma, gráfico PP, gráfico QQ).</p>
<p>Sin embargo, cuando es necesario un criterio más objetivo o se precisa de un proceso automático, entonces si la muestra es reducida (30 a 50 observaciones según autores) se aplica la prueba de Shapiro-Wilk; en otro caso se aplica la prueba de Jarque-Bera (<code>tseries</code>) o Kolmogorov-Smirnov. En nuestro ejemplo, con 26 datos, lo correcto es aplicar la prueba de Shapiro-Wilk. También hemos aplicado Jarque-Bera para que veas como la conclusión difiere según la prueba empleada.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  error
W = 0.8953, p-value = 0.01046</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">jarque.bera.test</span>(error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Jarque Bera Test

data:  error
X-squared = 4.4768, df = 2, p-value = 0.1066</code></pre>
</div>
</div>
<p><br>
</p>
<p><strong>Intervención</strong></p>
<p>Se analiza si para algún año se observa un error atípico (por ejemplo 3 veces superior al error estándar). La <a href="#fig-LibrosError">Figura&nbsp;13</a> muestra que en este caso en varios periodos, años 2008, 2009 y 2013, el residuo sobrepasa los dos errores estándar pero queda lejos de los tres errores estándar así que asumiremos que no hay valores atípicos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima010)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1993</span>, <span class="dv">2019</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-LibrosError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-LibrosError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 13: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="predicción" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción">Predicción</h3>
<p>Una vez validado el modelo podemos pasar a realizar <strong>predicciones</strong>, en este caso a 5 años vista.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>parima010 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(arima010, </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>parima010</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2020          64154 52573.41 75734.59
2021          64154 47776.57 80531.43
2022          64154 44095.83 84212.17
2023          64154 40992.82 87315.18
2024          64154 38259.01 90048.99</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(parima010, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Títulos"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1993</span>, <span class="dv">2024</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-LibrosPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-LibrosPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 14: Libros (1993-2019) y predicción (2020-2024)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-LibrosPre">Figura&nbsp;14</a> muestra la serie, la previsión y el intervalo de confianza al 95%. La predicción es constante e igual al último dato. En las series diferenciadas el intervalo de confianza de las predicciones crece muy rápidamente porque los errores se van acumulando sin ningún tipo de amortiguamiento.</p>
</section>
<section id="identificación-automática" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-automática">Identificación automática</h3>
<p>El paquete <code>forecast</code> dispone de la función <code>auto.arima()</code> que localiza el mejor modelo basándose en el AIC corregido para pequeñas muestras (<code>AICc</code>). No hay que fiarse ciegamente de los resultados de esta función, pero ayuda en la identificación. Básicamente el algoritmo seguido es el siguiente:</p>
<ol type="1">
<li>Determina el orden de diferenciación regular <span class="math inline">\(0 \leq d \leq 2\)</span> usando la función <code>ndiffs</code>, que usa la prueba KPSS repetidas veces.</li>
<li>Tras diferenciar la serie:
<ul>
<li>se estiman una serie de modelos básicos predeterminados.</li>
<li>se usa el criterio AICc para seleccionar el mejor de estos modelos.</li>
<li>a partir del modelo seleccionado, se hacen pequeñas variaciones modificando en una unidad <em>p</em> y <em>q</em> y añadiendo/quitando la constante y se vuelve a seleccionar el mejor de los nuevos modelos.</li>
</ul></li>
<li>Se repite el paso 2 hasta que no se puede mejorar el AICc.</li>
</ol>
<p>Cuando usemos esta función, debemos tener cuenta que:</p>
<ul>
<li>La función <code>auto.arima</code> no permite contante si la suma de las diferenciaciones es 2 o superior.</li>
<li>Si se desea hacer una búsqueda exhaustiva entre todos los posibles modelos se debe usar el argumento <code>stepwise = FALSE</code>.</li>
<li>Si se desea que el cálculo de AICc sea exacto (por defecto para ganar tiempo calcula una aproximación), se debe usar el argumento <code>approximation = FALSE</code>.</li>
<li>Si se desea ver para todos los modelos analizados el valor de AICc, se debe incluir el argumento <code>trace = TRUE</code>.</li>
</ul>
<p>La función <code>auto.arima</code> tiende a sobreparametrizar los modelos y es muy recomendable <em>ayudarla</em> indicando las diferenciaciones y la posible intervención.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(libros, <span class="at">trace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ARIMA(2,1,2) with drift         : Inf
 ARIMA(0,1,0) with drift         : 529.2727
 ARIMA(1,1,0) with drift         : 531.8087
 ARIMA(0,1,1) with drift         : 531.8033
 ARIMA(0,1,0)                    : 527.5277
 ARIMA(1,1,1) with drift         : Inf

 Best model: ARIMA(0,1,0)                    </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: libros 
ARIMA(0,1,0) 

sigma^2 = 34911235:  log likelihood = -262.68
AIC=527.36   AICc=527.53   BIC=528.62</code></pre>
</div>
</div>
<p>Observa como la identificación automática da como mejor modelo un ARIMA(0,1,0), que es el habíamos identificado, y como segunda opción el mismo modelo, pero con deriva.</p>
<p><br>
</p>
</section>
</section>
<section id="aforo-de-vehículos" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="aforo-de-vehículos"><span class="header-section-number">6.2</span> Aforo de vehículos</h2>
<p>Vamos a aplicar de nuevo la metodología de Box-Jenkins a la serie <strong>aforo de vehículos</strong> por Oropesa, carretera N-340, km. 996,48 (fuente Ministerio de Fomento). La serie es anual de 1960 a 2019 (60 datos).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>aforo <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/aforo_oropesa.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>aforo <span class="ot">&lt;-</span> <span class="fu">ts</span>(aforo, <span class="at">start =</span> <span class="dv">1960</span>, <span class="at">freq =</span> <span class="dv">1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(aforo, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Vehículos (000)"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Aforo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-Aforo-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 15: Aforo de vehículos en N-340, Oropesa</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>En este ejemplo incluiremos, por primera vez, intervención y veremos como <strong>la presencia de valores atípicos puede distorsionar el proceso de identificación</strong>. Por ello, es conveniente realizar en paralelo ambas actividades, identificar el proceso y detectar valores atípicos.</p>
<section id="transformación-de-la-serie-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie-1">Transformación de la serie</h3>
<p>La <a href="#fig-AforoFAC">Figura&nbsp;16</a> muestra que la serie Aforo no es estacionaria. Así, el primer paso es transformar la serie original para que lo sea. La serie no es estacionaria, pero sí lo es su primera diferencia. Ten siempre presente que diferenciar más veces de las necesarias puede dificultar la identificación y la interpretación. Por otro lado, la función <code>ndiffs</code> aconseja una diferenciación. Así, optamos por fijar <span class="math inline">\(d = 1\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(aforo, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(<span class="fu">diff</span>(aforo), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(aforo, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(aforo), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-AforoFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(b) Dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(c) FAC serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(d) FAC dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 16: Gráfica y FAC para Aforo</figcaption><p></p>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(aforo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="identificación-y-estimación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación">Identificación y estimación</h3>
<p>Veamos ahora a identificar los valores de <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span> a partir de la FAC y la FACP, que se muestran en la <a href="#fig-AforoDisplay">Figura&nbsp;17</a>. La FAC podemos considerar que tiene una sola autocorrelación significativa en el orden 1, y la FACP que presenta decrecimiento. Podría tratarse de un proceso MA(1).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtsdisplay</span>(<span class="fu">diff</span>(aforo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AforoDisplay" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoDisplay-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 17: Aforo (una diferencia)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>¿Qué recomienda <code>auto.arima</code>? Sugiere un proceso ARIMA(2,1,2), con todos los coeficientes aparentemente significativos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(aforo, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">d =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: aforo 
ARIMA(2,1,2) 

Coefficients:
         ar1      ar2      ma1     ma2
      1.3202  -0.6730  -1.2817  0.9363
s.e.  0.1311   0.1194   0.0979  0.1955

sigma^2 = 642488:  log likelihood = -477.45
AIC=964.91   AICc=966.04   BIC=975.3</code></pre>
</div>
</div>
<p>Vamos a ver la gráfica de los residuos del modelo ARIMA(2,1,2) para identificar los valores extremos (intervención).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>arima212 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(aforo, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">include.constant =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima212)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2020</span>, <span class="dv">4</span>)) </span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="co">#time(error)[abs(error) &gt; 2.5*sderror]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AforoError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 18: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Se identifican dos posibles valores extremos, dos intervenciones, en los años 1979 y 2011 (el error supera las 2.5 desviaciones típicas). Cada una de las intervenciones es del tipo <em>pulso</em> porque solo afecta un periodo de la serie.</p>
<p>Ahora, creamos una variable ficticia asociada a cada intervención, que denominaremos d1979 y d2011. La forma de definir la variable ficticia asociada a un pulso consiste en crear una variable de ceros, excepto para el periodo atípico en que la variable valdrá 1.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>d1979 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">time</span>(error) <span class="sc">==</span> <span class="dv">1979</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>d2011 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">time</span>(error) <span class="sc">==</span> <span class="dv">2011</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(aforo,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">d =</span> <span class="dv">1</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">xreg =</span> <span class="fu">cbind</span>(d1979,  d2011))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: aforo 
Regression with ARIMA(2,1,0) errors 

Coefficients:
         ar1     ar2       d1979       d2011
      0.1852  0.4420  -1716.4503  -1194.6499
s.e.  0.1181  0.1206    489.4467    455.9998

sigma^2 = 593139:  log likelihood = -474.07
AIC=958.14   AICc=959.27   BIC=968.53</code></pre>
</div>
</div>
<p>Observa como la inclusión de intervención modifica la autoidentificación, que ahora es un proceso ARIMA(2,1,0).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>arima210 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(aforo, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xreg =</span> <span class="fu">cbind</span>(d1979,  d2011))</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>arima210</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: aforo 
Regression with ARIMA(2,1,0) errors 

Coefficients:
         ar1     ar2       d1979       d2011
      0.1852  0.4420  -1716.4503  -1194.6499
s.e.  0.1181  0.1206    489.4467    455.9998

sigma^2 = 593139:  log likelihood = -474.07
AIC=958.14   AICc=959.27   BIC=968.53</code></pre>
</div>
</div>
<p>La <a href="#fig-AforoError2">Figura&nbsp;19</a> muestra que para ningún año se observa un error atípico. Es decir, no es necesaria más intervención.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima210)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2020</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AforoError2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoError2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 19: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="validación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-1">Validación</h3>
<p><strong>Variables significativas</strong></p>
<p>La identificación de errores atípicos –para la posterior inclusión de sus variables de intervención asociadas– ha sido un tanto arbitraria: ¿es atípico el error que supera las 2 desviaciones típicas, las dos y media, las tres desviaciones típicas?</p>
<p>De nuevo, podemos contrastar si sus coeficientes son significativos y dejar solo aquellas variables de intervención cuyo coeficientes lo sean. Aunque si la serie es suficientemente larga, también podríamos saltarnos este paso y dejar las variables de intervención que mejoren las predicciones extramuestrales del modelo o las que recojan efectos conocidos.</p>
<p>Veamos que todas las variables son significativas.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ancho <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">nchar</span>(<span class="fu">names</span>(<span class="fu">coef</span>(arima210)))) <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">coef</span>(arima210))) {</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  wt <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima210), </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima210), </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Terms =</span> i)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Coeficiente: "</span>, </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">names</span>(<span class="fu">coef</span>(arima210))[i], <span class="at">width =</span> ancho), </span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"valor de p: "</span>, </span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">formatC</span>(wt<span class="sc">$</span>result<span class="sc">$</span>chi2[<span class="dv">3</span>], <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"f"</span>))</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Coeficiente:  ar1     valor de p:  0.1168
Coeficiente:  ar2     valor de p:  0.0002
Coeficiente:  d1979   valor de p:  0.0005
Coeficiente:  d2011   valor de p:  0.0088</code></pre>
</div>
</div>
<p>Las dos variables de intervención son significativas y el coeficiente <span class="math inline">\(\phi_2\)</span> (<code>ar2</code>) también. No es significativo el coeficiente <span class="math inline">\(\phi_1\)</span> (<code>ar1</code>), pero no lo podemos eliminar. Los modelos Arima son modelos jerárquicos donde la presencia de un coeficiente significativo de cierto orden exige que los coeficiente de orden inferior estén presentes, sean o no significativos. En nuestro caso, como el coeficiente <span class="math inline">\(\phi_2\)</span> es significativo, se debe dejar en el modelo el coeficiente <span class="math inline">\(\phi_1\)</span>.</p>
<p><strong>Medidas de error</strong></p>
<p>El error medio es 737 miles de vehículos (RMSE) y el error porcentual medio (MAPE) es 5.67%. No hay sesgo de predicción y las fórmulas empleadas para el cálculo de los intervalos de confianza de las predicciones son válidas.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(arima210)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>               ME   RMSE    MAE  MPE MAPE MASE ACF1
Training set 47.2 737.37 535.16 1.32 5.67 0.79 0.04</code></pre>
</div>
</div>
<p><br>
</p>
<p><strong>Incorrelación, Homocedasticidad y Normalidad de los residuos</strong></p>
<p>Veamos ahora si el residuo es ruido blanco:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(error, <span class="at">lag =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"Ljung-Box"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  error
X-squared = 0.1638, df = 2, p-value = 0.9214</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(error<span class="sc">^</span><span class="dv">2</span>, <span class="at">lag =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"Ljung-Box"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  error^2
X-squared = 2.34, df = 2, p-value = 0.3104</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">jarque.bera.test</span>(error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Jarque Bera Test

data:  error
X-squared = 2.1563, df = 2, p-value = 0.3402</code></pre>
</div>
</div>
<p>Las hipótesis de incorrelación y homocedasticidad se aceptan. También se aceptarían para otros valores de <span class="math inline">\(k\)</span> razonables. Igualmente, se acepta la hipótesis de normalidad.</p>
<p><br>
</p>
<p>Confirmamos que <span class="math inline">\(aforo_t \sim ARIMA(2,1,0)\)</span> con intervención.</p>
</section>
<section id="interpretación-del-modelo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretación-del-modelo">Interpretación del modelo</h3>
<p>El <strong>modelo teórico</strong> es <span class="math inline">\(aforo_t \sim ARIMA(2,1,0) + d1979 + d2011\)</span>: <span class="math display">\[(1 - \phi_1 L - \phi_2 L^2)(1 - L)aforo_t =  \varepsilon_t + \gamma_1 \cdot d1979 + \gamma_2 \cdot d2011.\]</span></p>
<p>Si desarrollamos, queda: <span class="math display">\[aforo_t = aforo_{t-1} + \phi_1(aforo_{t-1}-aforo_{t-2}) + \phi_2(aforo_{t-2}-aforo_{t-3}) +\]</span> <span class="math display">\[\gamma_1 \cdot d1979 +  \gamma_2 \cdot d2011 + \varepsilon_t.\]</span></p>
<p>Finalmente, el <strong>modelo estimado</strong> es: <span class="math display">\[\widehat{aforo}_t = aforo_{t-1} + 0.19(aforo_{t-1}-aforo_{t-2}) + 0.44(aforo_{t-2}-aforo_{t-3})\]</span> <span class="math display">\[-1716 \cdot d1979 -1195 \cdot d2011\]</span> Cada año el aforo es el mismo que el aforo del año pasado más un 19% del último incremento observado y un 44% del incremento anterior.</p>
<p>Respecto de la intervención, en 1979 hubo un 1.7 millones menos de vehículos de lo esperado, debido a la apertura de la autopista AP-7 y en 2011 hubo 1.2 millones menos de vehículos, posiblemente debido a la Gran Recesión.</p>
</section>
<section id="predicción-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-1">Predicción</h3>
<p>Como hemos incluido dos variables ficticias en el ajuste, de cara a predecir el aforo hemos de indicar cuales serán los valores futuros para estas variables. En este caso serán cero puesto que son intervenciones que no responden a un efecto calendario. Las causas detrás de estas dos intervenciones no se espera que se repitan en el futuro.</p>
<p>En <code>R</code> esto se hace incluyendo en el comando <code>forecast</code> el argumento <code>xreg = cbind(rep(0, 5), rep(0, 5))</code> que añade cinco ceros por cada variable de intervención porque la predicción va a ser a cinco años vista.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>parima210 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(arima210, </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">level =</span> <span class="dv">95</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">xreg =</span> <span class="fu">cbind</span>(<span class="at">d1979=</span><span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">d2011=</span><span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>)))</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>parima210</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2020       9700.908 8191.432 11210.38
2021       9647.604 7306.822 11988.39
2022       9643.437 6212.738 13074.14
2023       9619.103 5212.971 14025.24
2024       9612.754 4207.919 15017.59</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(parima210, </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Vehículos (000)"</span>,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2024</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AforoPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AforoPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 20: Aforo (1960-2019) y predicción (2020-2024)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
<section id="validación-con-origen-de-predicción-móvil" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-con-origen-de-predicción-móvil">Validación con origen de predicción móvil</h3>
<p>Vamos a calcular el error extramuestral según el horizonte temporal de previsión. En este caso, la presencia de variables de intervención hace el código algo más complejo.</p>
<p>Asumiremos que se precisan 30 años para estimar el modelo, fijaremos el horizonte temporal en 5 años y calcularemos el error MAPE, que para la predicción intramuestral era de 5.7%.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">30</span>                  </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">5</span>                    </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">length</span>(aforo)     </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> T <span class="sc">-</span> k <span class="sc">-</span> h    </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(d1979, d2011))</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(aforo, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(aforo, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h) </span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k),])</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>  hay <span class="ot">&lt;-</span> <span class="fu">colSums</span>(X.train)</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> X.train[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k <span class="sc">+</span> h),])</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> X.test[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">Arima</span>(train.set, </span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.constant =</span> <span class="cn">FALSE</span>,</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xreg=</span><span class="fu">as.matrix</span>(X.train))</span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>    fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h, <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.test))</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a>      fit <span class="ot">&lt;-</span> <span class="fu">Arima</span>(train.set, </span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.constant =</span> <span class="cn">FALSE</span>,</span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a>      fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a>  mapeArima[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb53-37"><a href="#cb53-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-38"><a href="#cb53-38" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-39"><a href="#cb53-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-40"><a href="#cb53-40" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeArima)</span>
<span id="cb53-41"><a href="#cb53-41" aria-hidden="true" tabindex="-1"></a>mapeArima</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  5.651824  9.691844 14.902944 19.538856 23.247141</code></pre>
</div>
</div>
<p>El error de previsión extramuestral crece notablemente con el horizonte temporal. El error de las previsiones a un año vista es del 5.7%, prácticamente igual al error intramuestral, pero para dos años vista casi alcanza el 10% y a cinco años vista supera el 20%.</p>
</section>
</section>
<section id="consumo-de-alimentos-en-el-hogar-per-cápita" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="consumo-de-alimentos-en-el-hogar-per-cápita"><span class="header-section-number">6.3</span> Consumo de alimentos en el hogar per cápita</h2>
<p>Analizaremos el <strong>consumo alimentario en hogar per cápita</strong> en España. Esta serie está construida a partir de la serie de consumo alimentario en hogar (disponible en el Ministerio de Agricultura, Alimentación y Medio Ambiente), y la serie de población (disponible en el Instituto Nacional de Estadística). Es una serie anual de 1987 a 2021 (35 datos) y la unidad es el Kg per cápita. La <a href="#fig-Alimentos">Figura&nbsp;21</a> muestra que es una serie estacionaria.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>alimentospc <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/alimentacionpc.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>alimentospc <span class="ot">&lt;-</span> <span class="fu">ts</span>(alimentospc, <span class="at">start =</span> <span class="dv">1987</span>, <span class="at">freq =</span> <span class="dv">1</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(alimentospc, </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Kg per cápita"</span>,</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">700</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Alimentos" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-Alimentos-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 21: Consumo alimentario en hogar</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>El pico en el año 2020 se debe al aumento del consumo de alimentos en el hogar causado por el periodo de confinamiento por la Covid-19 (marzo a junio) y el aumento del trabajo en casa.</p>
<section id="transformación-de-la-serie-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie-2">Transformación de la serie</h3>
<p>La <a href="#fig-AlimentosFAC">Figura&nbsp;22</a> indica que la serie original ya es estacionaria y la función <code>ndiffs</code> lo corrobora. Por tanto asumimos que <span class="math inline">\(d=0\)</span> o <span class="math inline">\(alimentospc_t \sim I(0)\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(alimentospc, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(<span class="fu">diff</span>(alimentospc), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(alimentospc, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(alimentospc), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-AlimentosFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AlimentosFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AlimentosFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(b) Dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AlimentosFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(c) FAC serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AlimentosFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(d) FAC dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 22: Gráfica y FAC para Alimentos</figcaption><p></p>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(alimentospc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="identificación-y-estimación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación-1">Identificación y Estimación</h3>
<p>Para identificar los valores de <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span> veremos que nos sugiere <code>auto.arima</code> :</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(alimentospc,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">d =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: alimentospc 
ARIMA(1,0,0) with non-zero mean 

Coefficients:
         ar1      mean
      0.3359  638.4829
s.e.  0.1711    3.8911

sigma^2 = 254.2:  log likelihood = -145.61
AIC=297.22   AICc=297.99   BIC=301.88</code></pre>
</div>
</div>
<p>La identificación automática sugiere un proceso AR(1) con constante. El coeficiente de la constante (“mean” en la salida) es significativo –su valor supera dos veces su error estándar–, pero el del proceso autorregresivo no está tan claro.</p>
<p>Vamos a ver la gráfica de los residuos de este proceso para identificar rápidamente si hay valores extremos (<a href="#fig-AlimentosError">Figura&nbsp;23</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>arima100 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(alimentospc, </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">include.constant =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima100)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1987</span>, <span class="dv">2021</span>, <span class="dv">3</span>)) </span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a><span class="co">#time(alimentospc)[abs(error) &gt; 2 * sderror]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AlimentosError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AlimentosError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 23: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Hay un claro valor extremos en 2020. Tras incluirla y estimar el nuevo modelo aparecen otras variables de intervención asociadas a los años 1993, 1995 y 2009. Aunque ninguna supera las 2.5 desviaciones típicas, su efecto es significativo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>d1993 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">1993</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>d1995 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">1995</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>d2009 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">2009</span>)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>d2020 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>arima100 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(alimentospc, </span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">include.constant =</span> <span class="cn">TRUE</span>,</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xreg =</span> <span class="fu">cbind</span>(d1993, d1995, d2009, d2020))</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>arima100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: alimentospc 
Regression with ARIMA(1,0,0) errors 

Coefficients:
         ar1  intercept    d1993     d1995    d2009    d2020
      0.8164   638.5062  21.9317  -15.8202  21.3736  55.8455
s.e.  0.1153     7.7231   7.1062    7.1049   7.1063   7.1295

sigma^2 = 101.5:  log likelihood = -127.76
AIC=269.53   AICc=273.67   BIC=280.41</code></pre>
</div>
</div>
</section>
<section id="validación-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-2">Validación</h3>
<p><strong>Coeficientes significativos</strong></p>
<p>Tanto <span class="math inline">\(\phi_1\)</span> como el intercepto <span class="math inline">\(\mu\)</span> y las variables de intervención son significativas.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>ancho <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">nchar</span>(<span class="fu">names</span>(<span class="fu">coef</span>(arima100)))) <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">coef</span>(arima100))) {</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  wt <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima100), </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima100), </span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Terms =</span> i)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Coeficiente: "</span>, </span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">names</span>(<span class="fu">coef</span>(arima100))[i], <span class="at">width =</span> ancho), </span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"valor de p: "</span>, </span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">formatC</span>(wt<span class="sc">$</span>result<span class="sc">$</span>chi2[<span class="dv">3</span>], <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"f"</span>))</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Coeficiente:  ar1         valor de p:  0.0000
Coeficiente:  intercept   valor de p:  0.0000
Coeficiente:  d1993       valor de p:  0.0020
Coeficiente:  d1995       valor de p:  0.0260
Coeficiente:  d2009       valor de p:  0.0026
Coeficiente:  d2020       valor de p:  0.0000</code></pre>
</div>
</div>
<p><br>
</p>
<p><strong>Medidas de error</strong></p>
<p>El error medio es 9.2 Kg per cápita (RMSE) y el error porcentual medio (MAPE) es 1.2%. No hay sesgo y los intervalos de confianza de las predicciones son correctos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(arima100)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                ME RMSE  MAE   MPE MAPE MASE ACF1
Training set -1.26 9.17 7.57 -0.22 1.19 0.62 0.05</code></pre>
</div>
</div>
<p><br>
</p>
<p><strong>Incorrelación, Homocedasticidad y Normalidad del residuo</strong></p>
<p>Veamos ahora si el residuo es ruido blanco:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima100)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(error, <span class="at">lag =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"Ljung-Box"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  error
X-squared = 1.0495, df = 2, p-value = 0.5917</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(error<span class="sc">^</span><span class="dv">2</span>, <span class="at">lag =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"Ljung-Box"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  error^2
X-squared = 4.4326, df = 2, p-value = 0.109</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">jarque.bera.test</span>(error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Jarque Bera Test

data:  error
X-squared = 0.34866, df = 2, p-value = 0.84</code></pre>
</div>
</div>
<p>Las hipótesis de incorrelación y homocedasticidad se aceptan. También se aceptarían para otros valores de <span class="math inline">\(k\)</span> razonables. La hipótesis de normalidad también se acepta al 5%.</p>
</section>
<section id="interpretación-del-modelo-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretación-del-modelo-1">Interpretación del modelo</h3>
<p>El <strong>modelo teórico</strong> identificado es <span class="math display">\[(1 - \phi_1 L) alimentospc_t = c + \gamma_1 d1993 + \gamma_2 d1995 + \gamma_3 d2009 + \gamma_4 d2020 + \varepsilon_t,\]</span> que desarrollando queda <span class="math display">\[alimentospc_t = c + \phi_1 alimentospc_{t-1} + \gamma_1 d1993 + \gamma_2 d1995 + \gamma_3 d2009 + \gamma_4 d2020 + \varepsilon_t.\]</span></p>
<p>Finalmente, el <strong>modelo estimado</strong> es <span class="math display">\[\widehat{alimentospc}_t = 117.2 + 0.82 \cdot alimentospc_{t-1} +\]</span> <span class="math display">\[21.93\cdot d1993 - 15.82\cdot d1995 + 21.37\cdot d2009 + 55.85\cdot d2020\]</span></p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
La contante del modelo teórico y la media del modelo estimado
</div>
</div>
<div class="callout-body-container callout-body">
<p>El término contante <span class="math inline">\(\mu\)</span> que estima <code>R</code> no es el valor “c” que hemos visto en la teoría. Para convertir la contante estimada por <code>R</code> en “c” hemos de multiplicarla por el polinomio autorregresivo. En este caso, <span class="math display">\[c = \mu \cdot (1 - \phi_1) = 638.5062\cdot(1 - 0.8164) = 117.23\]</span></p>
</div>
</div>
<p>Cada año el consumo de alimentos per cápita en el hogar es 117.2 kilos más un 82% del consumo del año pasado.</p>
<p>En 2020, debido al efecto combinado del periodo de confinamiento entre marzo y junio y el incremento del trabajo en casa, se produjo un fuerte aumento del consumo de alimentos en el hogar, estimado en 56 Kg per cápita. En 1993 y 2009 el consumo medio de alimentos per cápita fue entre 21 y 22 Kg superior a lo esperado. Posiblemente, este incremento se deba al aumento del paro y la caída de los ingresos debida a la crisis de 1993 y la Gran Recesión (2008-2014), respectivamente. Finalmente, en 1995 se observa un consumo 16 Kg menor de lo esperado.</p>
</section>
<section id="predicciones-de-la-serie" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicciones-de-la-serie">Predicciones de la serie</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>parima100 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(arima100, </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">level =</span> <span class="dv">95</span>,</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">xreg =</span> <span class="fu">cbind</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>)))</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>parima100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2022       626.9791 607.2378 646.7203
2023       629.0957 603.6114 654.5800
2024       630.8237 602.1434 659.5040
2025       632.2344 601.6088 662.8600
2026       633.3860 601.5298 665.2422</code></pre>
</div>
</div>
<p>Puedes comprobar que cada valor de la predicción se ha obtenido a partir del modelo estimado, donde <span class="math inline">\(alimentospc_{t-1}\)</span> se sustituye por la predicción del año precedente.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(parima100, </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Kilos per cápita"</span>,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1986</span>, <span class="dv">2026</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AlimentosPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-04-Tema4_files/figure-html/fig-AlimentosPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 24: Consumo de alimentos y predicción</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="comparación-con-alisado-exponencial" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="comparación-con-alisado-exponencial"><span class="header-section-number">6.4</span> Comparación con alisado exponencial</h2>
<p>Veamos una comparativa, para los tres ejemplos vistos, entre los resultados obtenidos con ARIMA y con Alisado exponencial.</p>
<ul>
<li>Libros:
<ul>
<li><p>MAPE ARIMA: <span class="math inline">\(6.88\%\)</span> - ARIMA(0,1,0) sin deriva</p></li>
<li><p>MAPE ETS: <span class="math inline">\(6.90\%\)</span> - ETS(M,N,N), <span class="math inline">\(\alpha=1\)</span></p></li>
<li><p>Ambos métodos han estimado el mismo modelo.</p></li>
</ul></li>
</ul>
<ul>
<li>Aforo:
<ul>
<li><p>MAPE ARIMA: <span class="math inline">\(5.67\%\)</span> - ARIMA(2,1,0) sin deriva, con intervención</p></li>
<li><p>MAPE ETS: <span class="math inline">\(6.09\%\)</span> - ETS(M,A,N), <span class="math inline">\(\alpha=1\)</span>, <span class="math inline">\(\beta=0.1\)</span></p></li>
<li><p>Cada método estima un modelo diferente</p></li>
<li><p>ARIMA tiene menor error a costa de incluir dos variables de intervención</p></li>
</ul></li>
</ul>
<ul>
<li>Alimentos per cápita:
<ul>
<li><p>MAPE ARIMA: <span class="math inline">\(1.19\%\)</span> - ARIMA(1,0,0) con constante e intervención</p></li>
<li><p>MAPE ETS: <span class="math inline">\(1.93\%\)</span> - ETS(A,N,N), <span class="math inline">\(\alpha = 0.37\)</span></p></li>
<li><p>Cada método ha estimado un modelo diferente</p></li>
<li><p>ARIMA tiene menor error a costa de incluir cuatro variables de intervención</p></li>
</ul></li>
</ul>
<p><br>
<br>
</p>
</section>
</section>
<section id="resumen-de-los-comandos-utilizados" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Resumen de los comandos utilizados</h1>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Función</th>
<th style="text-align: left;">Paquete</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>arima.sim</code></td>
<td style="text-align: left;">stats</td>
<td style="text-align: left;">genera una simulación de un proceso ARIMA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Arima</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">estima un proceso ARIMA</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>auto.arima</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">identificación automática de un modelo ARIMA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>wald.test</code></td>
<td style="text-align: left;">aod</td>
<td style="text-align: left;">contrasta la significatividad conjunta de varios parámetros</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>forecast</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">realiza una predicción de un modelo</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Box.test</code></td>
<td style="text-align: left;">stats</td>
<td style="text-align: left;">prueba de independencia de una serie temporal</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>shapiro.test</code></td>
<td style="text-align: left;">stats</td>
<td style="text-align: left;">prueba de normalidad de Shapiro-Wilks</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>jarque.bera.test</code></td>
<td style="text-align: left;">tseries</td>
<td style="text-align: left;">prueba de normalidad de Jarque-Bera</td>
</tr>
</tbody>
</table>
<p><br>
<br>
</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-BoxJenkins76" class="csl-entry" role="doc-biblioentry">
Box, G. E. P., and G. M. Jenkins. 1976. <em>Time Series Analysis: Forecasting and Control</em>. Holden-Day, San Francisco.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2022, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.e</a></div>   
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>