---
output:
  html_document:
    theme: cerulean
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
---

<br><br>

Durante el curso usaremos diferentes ficheros para los datos de los ejemplos y para el código en `R`. Desde esta página puedes descargarte todo el material

<br>

----------------------

<br>

### Ficheros de datos

- [**Residuos recogidos**](series/Residuos.csv): Residuos recogidos por o en nombre de las autoridades municipales y eliminados a través del sistema de gestión de residuos (fuente Instituto Nacional de Estadística). Es una serie anual de 1995 a 2022.
- [**Nacimientos**](series/Nacimientos.csv): Nacimientos en España (fuente Instituto Nacional de Estadística). Serie mensual de enero de 1975 a diciembre de 2023.
- [**Consumo eléctrico**](series/Consumo%20electrico.csv): Consumo eléctrico en España en GW (fuente Red Eléctrica de España). Es una serie horaria desde las 00:00 horas del 1 de febrero de 2021 hasta las 23:00 horas del 28 de febrero de 2021.
- [**Consumo eléctrico por hora**](series/Consumo%20por%20hora.csv): Consumo eléctrico en España en GWh (fuente Red Eléctrica de España). Es una serie diaria desde el 1 de enero de 2023 hasta el 31 de diciembre de 2023.
- [**Aforo de vehículos en Oropesa**](series/Aforo_oropesa.csv): Aforo de vehículos por Oropesa (número medio de vehículos por día), carretera N-340, km. 996,48 (fuente Ministerio de Fomento). La serie es anual de 1960 a 2022.
- [**Consumo de alimentos per cápita**](series/Alimentacionpc.csv): Consumo alimentario en hogar per cápita en España. Esta serie está construida a partir de la serie de consumo alimentario en hogar (fuente Ministerio de Agricultura, Alimentación y Medio Ambiente), y la serie de población (fuente Instituto Nacional de Estadística). Es una serie anual de 1990 a 2023 y la unidad es el kg per cápita.
- [**Exportaciones de España a la UE-27**](series/Exportaciones.csv): volumen de exportaciones de bienes, en millones de euros, desde España hacía la UE-27 (conjunto de 27 países de la Unión Europea), desde enero de 1999 hasta diciembre de 2023 (fuente Eurostat).
- [**Exportaciones de España a la UE-27 de productos químicos**](series/Productos%20quimicos.csv): volumen de exportaciones de productos químicos, en millones de euros, desde España hacía la UE-27 (conjunto de 27 países de la Unión Europea), desde enero de 1999 hasta diciembre de 2020 (fuente Eurostat).
- [**Temperatura**](series/Temperatura.csv): Temperatura media diaria en España medida en el aeropuerto de Madrid (fuente Agencia Estatal de Meteorología, AEMET). Serie diaria del 1 enero de 2023 al 31 de diciembre de 2023.
- [**Defunciones por enfermedades cerebrovasculares**](series/Enfermedades cerebrovasculares.csv): Número de defunciones causadas por enfermedades cerebrovasculares (fuente Instituto Nacional de Estadística). Es una serie mensual de enero de 1980 a diciembre de 2023.
- [**Pasajeros en transporte urbano**](series/Pasajeros.csv): Número de pasajeros en transporte urbano en España (fuente Instituto Nacional de Estadística). Serie mensual de enero 1996 a diciembre de 2023.
- [**Pernoctaciones**](series/Pernoctaciones.csv): Número de pernoctaciones que los turistas extranjeros realizan en España en alojamientos turísticos autorizados (fuente Eurostat). Es una serie mensual de enero de 2000 a diciembre de 2023.

\

- [**Todos los ficheros de datos en un único fichero comprimido**](series/todoslosficherosdedatos.zip)

\
\

### Código `R`

Tienes el código para los temas de teoría aquí:

- [**Código para el tema 1**](codigo/Codigo Tema 1.R)
- [**Código para el tema 2**](codigo/Codigo Tema 2.R)
- [**Código para el tema 3**](codigo/Codigo Tema 3.R)
- [**Código para el tema 4**](codigo/Codigo Tema 4.R)
- [**Código para el tema 5**](codigo/Codigo Tema 5.R)

\

Para el ejemplo de Defunciones por enfermedades cerebrovasculares tienes el código aquí:

- [**Código para el ejemplo del tema 1**](codigo/Codigo Ejemplo 1.R)
- [**Código para el ejemplo del tema 2**](codigo/Codigo Ejemplo 2.R)
- [**Código para el ejemplo del tema 3**](codigo/Codigo Ejemplo 3.R)
- [**Código para el ejemplo del tema 4**](codigo/Codigo Ejemplo 4.R)
- [**Código para el ejemplo del tema 5**](codigo/Codigo Ejemplo 5.R)

Y para el ejemplo de Pasajeros en transporte urbano [aquí](codigo/Codigo Ejemplo Pasajeros.R).

\

- [**Todos los ficheros de código en un único fichero comprimido**](codigo/todoslosficherosdecodigo.zip)

\
\
\
\



