---
title: "Prácticas de evaluación"
output:
  html_document:
    theme: cerulean
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
---

\
\


Durante todo el módulo realizarás una serie de ejercicios que aplicarán las técnicas vistas en cada tema. Lee con atención las siguientes instrucciones generales.

Tu primera tarea es descargarte tu serie temporal. Descárgate [aquí](practica/Descripcion de las series.pdf) el fichero .pdf con la descripción de las series y localiza en él el nombre de tu serie. El este fichero encontrarás también una descripción detallada de la serie que vas a analizar: nombre, definición, unidades, fuente, fechado…

Por otro lado, descárgate [aquí](practica/Series.zip) el fichero comprimido con todas las series, descomprímelo y localiza el fichero ''csv'' con tu serie.

______________________

\
\


### Características generales de las entregas

\

* **La siguiente descripción de las prácticas es provisional e incompleta. El contenido final se indicará en clase al finalizar cada tema.**
* La **fecha** máxima de entrega de cada trabajo se indicará al finalizar cada tema. Procura no retrasarte. Si el retraso supera la semana, tu nota en la práctica será de cero.
* En Aulavirtual, en la tarea "Practica evaluación n" debes **subir un fichero .pdf con los resultados** de la práctica n-ésima. Sólo se admite un único fichero en formato .pdf.
* Piensa que además de los contenidos también su ordenación, estructura, sintaxis, comentarios, etc. son parte de la evaluación. [Aquí](practica/Rubrica correccion practicas.pdf) tienes qué aspectos voy a valorar y la puntuación de cada uno.
* **Incluye siempre todo el código en R utilizado en el trabajo**. Si utilizas Markdown (o similar), haz que el código sea visible; en otro caso, añádelo como un apéndice al final del documento. 
 

\
\

### Práctica 1: Descripción de la serie temporal

\

* Haz una descripción detallada de tu serie (tendencia, estacionalidad, intervención, tipo de esquema...).
* Ayúdate para ello de todos los elementos numéricos y gráficos que hemos visto: gráfica de tu serie original, gráfica de su agregación anual, gráfica localización/dispersión, descomposición...

Si el análisis realizado así lo aconseja, indica si vas a recortar tu serie para posteriores análisis.


\
\

### Práctica 2: Alisado exponencial

\

* Ajusta el modelo de alisado más adecuado a tus datos.
    - Describe el modelo obtenido.
    - Obtén los indicadores de la calidad del modelo y coméntalos.
    - Realiza un predicción a tres años vista  y muestra los resultados de la predicción gráficamente.
    - Obtén la calidad de las previsiones con origen de previsión móvil.
    - Obtén el residuo e identifica la presencia de valores extremos.
    - Compara el modelo ajustado por Alisado Exponencial con el método ingenuo con estacionalidad


\
\

### Práctica 3: Procesos ARIMA sin estacionalidad

A grandes rasgos el ejercicio consistirá en analizar tu serie temporal sin estacionalidad (agregación anual), siguiendo la metodología de Box y Jenkins. Por tanto, para esta práctica debes considerar solo tu serie con fechado anual.

A continuación se indican los contenidos mínimos que se deben presentar. Eres libre de elegir el orden de la presentación de los contenidos, así como la información finalmente presentada.

* Transforma la serie para que sea estacionaria y ergódica
    - Obtén su gráfica de la serie y de su primera diferencia.
    - Realiza el contraste de raíces unitarias.
    - Diferencia la serie para obtener otra que sea estacionaria y ergódica.
    - Valor el uso de la transformación logarítmica.
    
* Identificación del modelo ARIMA
    - Identificación de la parte estructural, análisis de intervención y valores atípicos.

* Estimación del modelo definitivo
    - Estimación de los coeficientes del modelo.
    - Desarrollo de la ecuación estimada.
    - Interpretación de los parámetros y de la ecuación estimada.

* Validación completa del modelo
    - Significatividad de los coeficientes (contraste de Wald).
    - Hipótesis de homocedasticidad e incorrelación.
    - Valores extremos.
    - Cálculo de la calidad del ajuste y de las predicciones.

* Previsión de la serie (al menos tres años)

* Valoración crítica del modelo ARIMA respecto de un modelo de alisado
    - Comparación del modelo estimado en esta práctica el mejor modelo de alisado para la serie anual.
    - Comparación de la calidad de los modelos.
    - Comparación de las previsiones.

\
\

### Práctica 4: Procesos ARIMA con estacionalidad

Los objetivos de esta práctica son idénticos a los de la práctica previa, pero considerando tu serie original con estacionalidad.

* Transforma la serie para que sea estacionaria y ergódica.
    - Valor el uso de la transformación logarítmica.
    - Obtén la gráfica de la serie y de su primera diferencia (regular y/o estacional)
    - Además, calcula la FAC de la serie y de su primera diferencia (regular y/o estacional). 
    - Diferencia la serie para obtener otra que sea estacionaria y ergódica.
    
* Identificación del modelo ARIMA
    - Parte de la trasformación de la serie identificada en la práctica 3.
    - Identificación de la parte estructural, análisis de intervención y valores atípicos.

* Estimación del modelo definitivo
    - Estimación de los coeficientes del modelo.
    - Desarrollo de la ecuación estimada.
    - Interpretación de la ecuación estimada.

* Validación completa del modelo
    - Significatividad de los coeficientes (contraste de Wald).
    - Hipótesis de homocedasticidad e incorrelación.
    - Valores extremos.
    - Cálculo de la calidad del ajuste y de las predicciones.

* Previsión de la serie (al menos tres años, 36 meses)

* Valoración crítica del modelo ARIMA respecto de un modelo de alisado:
    - Comparación del modelo estimado en esta práctica con el modelo de la práctica 2
    - Comparación de la calidad de los modelos.
    - Comparación de las previsiones.

\
\
\
\

